About this notebook.

This notebook goes through all the texts and aplies on them a NLP pipeline consisting of (1) cleaning of the raw text, (2) sentence tokenization, (3) part-of-speech annotation, (4) lemmatization, and (5) named entity recognition.

The processed textual data are saved for future reuse.

In [1]:
import spacy
import os
import glob
from spacy.tokens import Doc
from spacy.language import Language
import pickle
from unidecode import unidecode
import sddk
import pandas as pd
import re
import sys
import importlib
import json
from spacy.tokens import Token
from spacy.language import Language
import google_conf
import pandas as pd
import json

/home/jupyter-vojta/notebooks/labyrinth/venv_torch_nlp/lib/python3.12/site-packages/torch/cuda/__init__.py:716: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

In [2]:
emlap_metadata = pd.read_csv("../data/emlap_metadata.csv", sep=";", index_col=0)
emlap_metadata.head(5)

,working_title,filenames,no.,is_done,is_noscemus,if_noscemus_id,AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,CONTENTS,genre,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,other_notes,tokens_N,aurhor_wd
0,"Augurello, Chrysopoeia",100001_Augurello1515_Chrysopoeia_GB_Noscemus,100001,True,True,713324.0,NaN,True,NaN,True,...,NaN,didactic poem,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,GB,Noscemus,NaN,23718,NaN
1,"Pseudo-Lull, Secretis",100002_Pseudo-Lull1518_De secretis_naturae_MDZ...,100002,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,"alchemy, medicine",NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,24673,NaN
2,"Pantheus, Ars Transmutatione",100003_Pantheus1518_Ars_Transmutationis_Metall...,100003,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,alchemy,NaN,https://www.google.co.uk/books/edition/Ars_Tra...,GB,BL,NaN,8646,NaN
3,"Anon, Vera alchemiae",100004_Anon1561_Verae_Alchemiae_MDZ_MBS,100004,True,False,NaN,NaN,True,NaN,True,...,NaN,"compendium, florilegium",alchemy,NaN,https://mdz-nbn-resolving.de/details:bsb10141168,MDZ,MBS,NaN,3521,NaN
4,"Pantheus, Voarchadumia",100005_Pantheus1530_Voarchadumia_ONB,100005,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,alchemy,NaN,https://data.onb.ac.at/rep/10588E49,ONB,ONB,NaN,20386,NaN

In [5]:
row = emlap_metadata.loc[emlap_metadata["no."]==100001].iloc[0]

In [6]:
row["working_title"]

'Augurello, Chrysopoeia'

In [7]:
import json
import ast
import re

def parse_messy_json(text):
    if not isinstance(text, str):
        return None

    # 1. Try strict JSON first
    try:
        return json.loads(text)
    except Exception:
        pass

    # 2. Fix common issues
    fixed = text.strip()

    # Replace single quotes with double quotes when appropriate
    fixed = fixed.replace("'", '"')

    # Remove trailing commas before ] or }
    fixed = re.sub(r",\s*([}\]])", r"\1", fixed)

    # Ensure keys are quoted (naively, but works for your case)
    fixed = re.sub(r"(?<=\{|\s)([A-Za-z_][A-Za-z0-9_]*)(?=\s*:)", r'"\1"', fixed)

    # 3. Try JSON again
    try:
        return json.loads(fixed)
    except Exception:
        pass

    # 4. Try Python literal (safer than eval)
    try:
        return ast.literal_eval(text)
    except Exception:
        pass

    # 5. Give up
    return None

In [8]:
emlap_metadata["if_compendium_parsed"] = emlap_metadata["if_compendium"].apply(parse_messy_json).tolist()

In [9]:
len(emlap_metadata)

100

In [10]:
#filename_id_dict = dict(zip(emlap_metadata["filename"], emlap_metadata["No."]))

For preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level one level up.

The module can be clonned from here: https://github.com/CCS-ZCU/latin-preprocessing and imported to python following the steps below:

In [40]:
# for preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level as the current project.
current_working_directory = os.getcwd()
relative_path = '../../latin-preprocessing/' # change according to your location...
module_path = os.path.abspath(os.path.join(current_working_directory, relative_path))
if module_path not in sys.path:
    sys.path.insert(0, module_path)
# Now import the module
import tomela

In [128]:
importlib.reload(tomela)

Using CPU for spaCy.

In [129]:
tomela.nlp.pipeline

[('senter', <spacy.pipeline.senter.SentenceRecognizer at 0x7a92a40ceb10>),
 ('normer', <function la_core_web_lg.functions.normer(doc)>),
 ('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7a9200360770>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7a9200360590>),
 ('morphologizer',
  <spacy.pipeline.morphologizer.Morphologizer at 0x7a92003609b0>),
 ('trainable_lemmatizer',
  <spacy.pipeline.edit_tree_lemmatizer.EditTreeLemmatizer at 0x7a9200360470>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7a92003076f0>),
 ('lookup_lemmatizer',
  <function la_core_web_lg.functions.make_lookup_lemmatizer_function(doc)>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7a90e62e84a0>),
 ('remorpher', <function la_core_web_lg.functions.remorpher(doc)>)]

In [130]:
tomela.nlp.max_length = 4000000

In [14]:
doc = tomela.nlp("Veritas, vt vlla dicit, semper est universalis et a principiis fundamentalis oritur (lib. 3, cap. VI)")
for token in doc:
    print((token.text, token.lemma_, token.pos_))

('Veritas', 'ueritas', 'NOUN')
(',', ',', 'PUNCT')
('vt', 'vt', 'ADV')
('vlla', 'vllus', 'NOUN')
('dicit', 'dico', 'VERB')
(',', ',', 'PUNCT')
('semper', 'semper', 'ADV')
('est', 'sum', 'AUX')
('universalis', 'uniuersalis', 'ADJ')
('et', 'et', 'CCONJ')
('a', 'ab', 'ADP')
('principiis', 'principium', 'NOUN')
('fundamentalis', 'fundamentalis', 'ADJ')
('oritur', 'orior', 'VERB')
('(lib', '(lib', 'NOUN')
('.', '.', 'PUNCT')
('3', '3', 'NUM')
(',', ',', 'PUNCT')
('cap', 'capitulum', 'NOUN')
('.', '.', 'PUNCT')
('VI', 'uis', 'NUM')
(')', ')', 'PUNCT')

In [15]:
source_path = "/srv/data/tome/tome-corpus/EMLAP_2025-10-31/annotated_textblocks/"
len(os.listdir(source_path))

200

In [16]:
import shutil
shutil.copytree("/srv/data/tome/tome-corpus/EMLAP_2025-10-31/annotated_textblocks/", "../data/emlap_annotated_textblocks/", dirs_exist_ok=True)

'../data/emlap_annotated_textblocks/'

In [17]:
[f for f in sorted(os.listdir(source_path)) if "_params" not in f]

['100001_Augurello1515_Chrysopoeia_GB_Noscemus.json',
 '100002_Pseudo-Lull1518_De_secretis_naturae_MDZ_MBS.json',
 '100003_Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 '100004_Anon1561_Verae_Alchemiae_MDZ_MBS.json',
 '100005_Pantheus1530_Voarchadumia_ONB.json',
 '100006_Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json',
 '100007_Anon1550_Rosarium_philosophorum_ER_ZZ.json',
 '100008_Severinus1572_Epistola_MBZ_MBS.json',
 '100009_Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json',
 '100010_Bracesco1548_De_alchemia_dialogi_duo_IA_Madrid.json',
 '100011_Anon1541_De_alchemia_MDZ_MBS.json',
 '100012_Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json',
 '100013_Ulstad1525_Coelum_philosophorum_Medica_BIUSP.json',
 '100014_Toxites1567_Spongia_stibii_MDZ_MBS.json',
 '100015_Gessner1569_Thesaurus_Euonymi_Philiatri_liber_secundus_MDZ_MBS.json',
 '100016_Bonus1546_Pretiosa_Margarita_Novella_ONB.json',
 '100017_Bodenstein1559_Isagoge_MDZ_MBS.json',
 '100018_Trevisanus1567_Peri_chemeias_MDZ_MBS.json',
 '100019_Ulstadt1526_De_epidemia_ONB.json',
 '100020_Dorn1569_Artificii_chymistici_MDZ_MBS.json',
 '100021_Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB.json',
 '100022_Anon1550_De_alchemia_opuscula_MDZ_MBS.json',
 '100023_Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS.json',
 '100024_Fanianus1560_De_arte_metallicae_ONB.json',
 '100025_Pseudo-Lull1563_Codicillus_MDZ_MBS.json',
 '100026_Garlandius1560_Compendium_Alchemiae_VD16_SLUB.json',
 '100027_Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 '100028_Pedemontanus1563_De_secretis_MDZ_MBS.json',
 '100029_Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json',
 '100030_Rupescissa1561_De_consideratione_quintae_essentie_rerum_GB.json',
 '100031_Phaedro1562_Aquila_coelestis_MBZ_MBS.json',
 '100032_Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json',
 '100033_Pseudo-Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json',
 '100034_Penotus1594_Tractatus_varii_MDZ_MBS.json',
 '100035_Dorn1570_Lapis_metaphysicus_MDZ_MBS.json',
 '100036_Vadis1595_Dialogus_IA_Wellcome.json',
 '100037_DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
 '100038_Anon1571_Auriferae_artis_MBZ_Augsburg.json',
 '100039_Pseudo-Democritus1572_Ars_magna_MDZ_MBS.json',
 '100040_Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 '100041_Senior1560_De_chemia_senioris_MDZ_MBS.json',
 '100042_Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json',
 '100043_DuChesne1575_Sclopetarius_MDZ_Augsburg.json',
 '100044_Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json',
 '100045_Dorn1583_De_naturae_luce_physica_MDZ_MBS.json',
 '100046_Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json',
 '100047_Portaleone1584_De_auro_dialogi_tres_ONB.json',
 '100048_Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 '100049_Rossi1585_De_destillatione_MDZ_MBS.json',
 '100050_Anon1599_Quadriga_aurifera_IA_Madrid.json',
 '100051_Ruland1564_Medicina_practica_recens_MDZ_MDS.json',
 '100052_Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json',
 '100053_Mirandola1586_De_auro_libri_tres_MDZ_MBS.json',
 '100054_Moffett1584_De_iure_et_praestantia_MDZ_MBS.json',
 '100055_Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json',
 '100056_Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json',
 '100057_Hagecius1585_De_cerevisia_GB_ONB.json',
 '100058_Hagecius1596_Actio_medica_ER_UBB.json',
 '100059_Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json',
 '100060_Witestein1583_Disceptatio_philosophica_MDZ_MBS.json',
 '100061_Moffett1588_Nosomantica_Hippocrates_ONB.json',
 '100062_Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.json',
 '100063_Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.json',
 '100064_Trevisanus1583_De_chymico_miraculo_MDZ_MBS.json',
 '100065_Libavius1594_Neoparacelsica_MDZ_MBS.json',
 '100066_Suchten1575_De_secretis_antimonii_ONB.json',
 '100067_Wecker1582_De_secretis_ONB.json',
 '100068_Pseudo-Paracelsus1577_Aurora_thesaurusque_philosophorum_ONB.json',
 '100069_Severinus1571_Idea_medicinae_philosophicae_GB_Noscemus.json',
 '100070_Libavius1597_Alchemia_ER_Noscemus.json',
 '100071_Pseudo-Lull1566_Testamentum_MDZ_MBS.json',
 '100072_Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.json',
 '100073_Greverus1599_Secretum_MDZ_MBS.json',
 '100074_Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.json',
 '100075_Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.json',
 '100076_Du_Chesne1604_Ad_Veritatem_Hermeticae_Medicinae_MDZ_MBS.json',
 '100077_Cephalus1601_Apotelesmatum_philosophicum_HT.json',
 '100078_Harvet1605_Demonstratio_veritatis_VD17_FAU.json',
 '100079_Eglinus1608_Disquisitio_de_Helia_Artium_MDZ_MBS.json',
 '100080_Anon1611_Tratatus_de_secretissimo_MDZ_MBS.json',
 '100081_Sendivogius1614_Novum_lumen_chymicum_VD17_SLUB.json',
 '100082_Hermes_Trismegistus1610_Tractatus_vere_aureus_VD17_SLUB.json',
 '100083_Sendivogius1616_Tractatus_de_sulphure_MBS_MDZ.json',
 '100084_Croll1609_Basilica_chymica_MDZ_MBS.json',
 '100085_Libavius1606_Commentariorum_alchemiae_pars_1_MDZ_MBS.json',
 '100086_Penotus1608_Denario_medico_MDZ_MBS.json',
 '100087_Beguin1612_Tyrocinium_chymicum_GB_Noscemus.json',
 '100088_Dienheim1610_Medicina_universalis_ONB.json',
 '100089_BasiliusValentinus1613_Azoth_VD17_SLUB.json',
 '100090_Nolle1617_Theoria_philosophiae_Hermeticae_MDZ_MBS.json',
 '100091_Ruland1607_Progymnasmata_alchemiae_MDZ_MBS.json',
 '100092_Drebbel1621_Tractatus_duo_VD17_Halle.json',
 '100093_Sala1622_Chrysologia_MBZ_MBS.json',
 '100094_Anon1625_Musaeum_hermeticum_VD17_SLUB.json',
 '100095_Fabre1632_Alchymista_christianus_ONB.json',
 '100096_Agricola1631_Galerazeya_GB_BL.json',
 '100097_Van_Helmont1644_Opuscula_medica_MDZ_MBS.json',
 '100098_Burggravius1630_Biolychnium_VD17_SLUB.json',
 '100099_Francus1607_De_Arte_Chemica_VD17_Halle.json',
 '100100_Van_Helmont1648_Ortus_medicinae_MDZ_MBS.json']

In [18]:
row = emlap_metadata.loc[emlap_metadata["no."]==int("100001")].iloc[0]
row

working_title                                                                                 Augurello, Chrysopoeia
filenames                                                               100001_Augurello1515_Chrysopoeia_GB_Noscemus
no.                                                                                                           100001
is_done                                                                                                         True
is_noscemus                                                                                                     True
if_noscemus_id                                                                                              713324.0
AUTHORSHIP                                                                                                       NaN
is_one_author                                                                                                   True
#if more than 1 author skip section and choose compendium below                                                  NaN
is_author_known                                                                                                 True
author_name                                                                              Augurelli, Giovanni Aurelio
author_name_alternatives                                                                                  Augurellus
author_viaf                                                                                                 88062391
author_cerl                                                                                              cnp01876437
author_comments                                                                                                  NaN
is_compendium                                                                                                  False
if_compendium                                                                                                    NaN
TRANSLATION / EDITORSHIP                                                                                         NaN
is_translator                                                                                                  False
translator_name                                                                                                  NaN
translator_name_alternatives                                                                                     NaN
translator_comments                                                                                              NaN
is_editor                                                                                                      False
editor_name                                                                                                      NaN
editor_name_alternatives                                                                                         NaN
editor_comments                                                                                                  NaN
DATE OF PUBLICATION                                                                                              NaN
date_publication                                                                                                1515
date_certainty                                                                                                  True
date_not_after                                                                                                   NaN
date_not_before                                                                                                  NaN
date_comment                                                                                                     NaN
TITLE                                                                                                            NaN
title_short                                                                                              Chrysopoeia
title_full                                                         Ioannis Aurelii Augurelli P. Ariminensis Chrys...
title_viaf                                                                                               178020328.0
title_comments                                                                                                   NaN
PLACE OF PUBLICATION                                                                                             NaN
place_publication                                                                                             Venice
place_geonames                                                                                               3164603
place_comments                                                                                                   NaN
PUBLISHER                                                                                                        NaN
publisher_name                                                                                             Da Rovere
publisher_name_alternatives                                                                                      NaN
publisher_comments                                                                                               NaN
CONTENTS                                                                                                         NaN
genre                                                                                                  didactic poem
subject                                                                                                      alchemy
SOURCE OF FILE                                                                                                   NaN
link                                                                    https://wiki.uibk.ac.at/noscemus/Chrysopoeia
source_of_file                                                                                                    GB
origin_of_copy                                                                                              Noscemus
other_notes                                                                                                      NaN
tokens_N                                                                                                       23718
aurhor_wd                                                                                                        NaN
if_compendium_parsed                                                                                            None
Name: 0, dtype: object

In [19]:
files_overview = []
for filename in os.listdir(source_path):
    #filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
    id = int(filename[:6])
    row = emlap_metadata.loc[emlap_metadata["no."]==id].iloc[0]
    if "_params" not in filename:
        filepath = os.path.join(source_path, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            textblocks = json.load(f)
        pages_n = len(textblocks)
        chars_n = sum([sum([len(tb["text"]) for tb in p]) for p in textblocks])
        files_overview.append({"filename" : filename, "pages_n" : pages_n, "chars_n" : chars_n})
files_processed = pd.DataFrame(files_overview)
files_processed

                                             filename  pages_n  chars_n
0      100084_Croll1609_Basilica_chymica_MDZ_MBS.json      477   694793
1   100094_Anon1625_Musaeum_hermeticum_VD17_SLUB.json      508   694493
2        100058_Hagecius1596_Actio_medica_ER_UBB.json       89   104677
3   100013_Ulstad1525_Coelum_philosophorum_Medica_...      113   237793
4   100069_Severinus1571_Idea_medicinae_philosophi...      463   600046
..                                                ...      ...      ...
95  100056_Claveus1598_Apologia_crysopoeiae_MDZ_MB...      233   233328
96    100065_Libavius1594_Neoparacelsica_MDZ_MBS.json      821  1079977
97   100031_Phaedro1562_Aquila_coelestis_MBZ_MBS.json       55    15562
98  100098_Burggravius1630_Biolychnium_VD17_SLUB.json      167   186267
99  100042_Pseudo-Paracelsus1568_De_summis_naturae...      177   179729

[100 rows x 3 columns]

In [20]:
#emlap_catalogue = google_conf.setup(sheet_url="https://docs.google.com/spreadsheets/d/1bkHHTYc86K2IuEXqfYfkDNt5LovtvCU3gvqHIbVio88/edit?usp=sharing", service_account_path="../../../ServiceAccountsKey.json")

# google_conf.set_with_dataframe(emlap_catalogue.add_worksheet("files_processed", 1,1), files_processed, include_index=False)


Develop and test with one example test

In [21]:
filename = '100085_Libavius1606_Commentariorum_alchemiae_pars_1_MDZ_MBS.json'
filepath = os.path.join(source_path, filename)
with open(filepath, 'r', encoding='utf-8') as f:
    textblocks = json.load(f)

In [22]:
len(textblocks)

413

In [ ]:
textblocks[30][:10]

In [25]:
for p in textblocks[:15]:
    for t in p:
        if "[" in t["text"]:
            print(t)

{'coordinates': [384.0, 2262.9599609375, 2165.489013671875, 2267.760009765625], 'text': '[GR]χιμικώτερα[/GR] essent seligere, dissentientiaquè componere. Itaque & nouam\n', 'tag': 'text'}
{'coordinates': [139.1999969482422, 3188.159912109375, 1914.183349609375, 3192.9599609375], 'text': 'quoddam [GR]μιγμα[/GR] & commentum ab omni veritate alienum. Sed ostendendum est veram artem nec\n', 'tag': 'text'}
{'coordinates': [398.1600036621094, 511.6800231933594, 2167.622314453125, 516.4800415039062], 'text': 'longe abest à [GR]πανσπερμία[/GR] illa vetere, & atomis Democriti, & multiplici vicissim oriente & pereunte? Sed\n', 'tag': 'text'}
{'coordinates': [390.7200012207031, 2782.079833984375, 2149.680419921875, 2786.8798828125], 'text': 'quętis [GR]σκευασταί καὶ πυροτεηνίαν[/GR], ecce tibi eundem Bulcasim passim inseruientem. Fornaces enim seu Atha¬\n', 'tag': 'text'}

In [136]:
for p in textblocks:
    for t in p:
        if "[/S]" in t["text"]:
            print(t)

{'coordinates': [225.83999633789062, 905.7598266601562, 387.3038635253906, 910.5598754882812], 'text': 'Olei [S]y[/S]. j. ex\n', 'tag': 'margin'}
{'coordinates': [429.1199951171875, 1108.5599365234375, 2191.517578125, 1113.35986328125], 'text': 'crassos. Dosis eius solius [S]z[/S] ij. vsque ad [S]z[/S] iiij. cum aqua frigida. Similia habet Mesues lib simplicium, cap. 16.\n', 'tag': 'text'}
{'coordinates': [241.9199981689453, 2369.999755859375, 407.46197509765625, 2374.7998046875], 'text': 'trahe [S][/S], ex\n', 'tag': 'margin'}
{'coordinates': [234.72000122070312, 2417.999755859375, 407.2383728027344, 2422.7998046875], 'text': 'hoc\xa0[S][/S], & i¬\n', 'tag': 'margin'}
{'coordinates': [424.0799865722656, 312.7200622558594, 2143.775634765625, 317.5200500488281], 'text': 'Lunam, Venerem, Martem, Saturnum, louem; signare vero more astrologorum,\xa0[S]Mercurius[/S],\xa0[S]Sol[/S],\xa0[S]Luna[/S],\xa0[S]Venus[/S],\xa0[S]Mars[/S],\xa0[S]Saturnus[/S],\xa0[S]Jupiter[/S].\n', 'tag': 'text'}
{'coordinates': [1166.4000244140625, 472.3201599121094, 1385.740966796875, 477.1201477050781], 'text': '[S]Saturnus[/S]\xa0Saturnus\n', 'tag': 'text'}
{'coordinates': [1188.0, 530.3999633789062, 1485.612548828125, 535.2000122070312], 'text': '[S]Jupiter[/S]\xa0vel\xa0[S]Jupiter[/S].\xa0Iupiter\n', 'tag': 'text'}
{'coordinates': [1213.9200439453125, 576.2642211914062, 1454.467041015625, 581.1842041015625], 'text': '[S]Mercurius[/S]\xa0Mercurius vel\xa0[S]Mercurius[/S]\n', 'tag': 'text'}
{'coordinates': [1538.6400146484375, 475.9441223144531, 1812.8485107421875, 480.8641357421875], 'text': '[S]Mars[/S] vel\xa0[S]Mars[/S]\xa0Mars\n', 'tag': 'text'}
{'coordinates': [1506.0, 532.5601196289062, 1686.530029296875, 537.3601684570312], 'text': '[S]Venus[/S] Venus\n', 'tag': 'text'}
{'coordinates': [1503.8399658203125, 584.1599731445312, 1697.5361328125, 588.9600219726562], 'text': '[S]Luna[/S] Luna\xa0[S]Luna[/S]\n', 'tag': 'text'}
{'coordinates': [1514.6400146484375, 634.3201293945312, 1646.7060546875, 639.1201782226562], 'text': '[S]Sol[/S]\xa0Sol.\n', 'tag': 'text'}
{'coordinates': [1327.6800537109375, 1278.7200927734375, 1373.8641357421875, 1283.52001953125], 'text': '[S]crux[/S]\n', 'tag': 'text'}
{'coordinates': [1060.3199462890625, 1432.823974609375, 1571.1358642578125, 1437.7440185546875], 'text': '[S]Aries[/S]\xa0[S]Taurus[/S]\xa0[S]Gemini[/S]\xa0\xa0[S]Cancer[/S]\xa0[S]]Leo[/S]\xa0\xa0[S]Virgo[/S]\n', 'tag': 'text'}
{'coordinates': [1049.52001953125, 1494.4801025390625, 1563.99609375, 1499.280029296875], 'text': '[S]Libra[/S]\xa0[S]Scorpio[/S]\xa0[S]Sagittarius[/S]\xa0[S]Capricornus[/S]\xa0[S] Aquarius[/S]\xa0[S]Pisces[/S]\n', 'tag': 'text'}
{'coordinates': [428.3999938964844, 1661.0401611328125, 2124.18017578125, 1665.840087890625], 'text': 'monstrat in illa vnione hieroglyphica Indicos hos characteres. I. 2. 3. 4. (vel [S]piscis[/S]) 5. 6.\n', 'tag': 'text'}
{'coordinates': [846.0, 2991.384033203125, 1560.7996826171875, 2996.303955078125], 'text': '[S]Libra[/S]\xa0vel\xa0[S]Taurus[/S]\xa0vel\xa0[S]Venus[/S]\xa0vel\xa0[S]Mercurius[/S]\xa0vel [S][/S] [S][/S]\n', 'tag': 'text'}
{'coordinates': [517.2000122070312, 3050.159912109375, 2166.363037109375, 3054.9599609375], 'text': 'Quidam tamen etiam vsurpant signum capitis draconis [S]caput draconis[/S], cui apponunt aliquando figuram\n', 'tag': 'text'}
{'coordinates': [411.1199951171875, 3098.880126953125, 2168.111572265625, 3103.68017578125], 'text': 'mercurii\xa0[S]Mercurius[/S] [S]caput draconis[/S]. Nam posterior nota etiam sublimationis character est, quam phanatici sic pingen¬\n', 'tag': 'text'}
{'coordinates': [415.44000244140625, 3156.9599609375, 2169.962646484375, 3161.760009765625], 'text': 'tes [S][/S]\xa0accommodarunt cineribus, & aquae vitae. Porro ex illa monade etiam haec dependent [S][/S]\xa0dies\n', 'tag': 'text'}
{'coordinates': [419.760009765625, 3212.880126953125, 2157.210693359375, 3217.68017578125], 'text': '[S][/S]\xa0nox: [S][/S]\xa0miniùm ex plumbo. [S][/S]\xa0limatura ferri, [S][/S]\xa0limatura chalybis. [S][/S]\xa0Crocus martis (ali¬\n', 'tag': 'text'}
{'coordinates': [415.44000244140625, 3270.02392578125, 2164.44482421875, 3274.94384765625], 'text': 'qui etiam sic pingunt [S][/S]\xa0vel [S][/S]\xa0fors cum sulphure factum designantes [S][/S]\xa0aerugo; [S][/S]\xa0atramen¬\n', 'tag': 'text'}
{'coordinates': [408.9599914550781, 3328.10400390625, 2154.82080078125, 3333.02392578125], 'text': 'tùm (quae nota efformatur etiam aliter vt: [S][/S], [S][/S]) [S][/S]\xa0halonitrum: [S][/S]\xa0alumen: [S][/S]\xa0acetum.\n', 'tag': 'text'}
{'coordinates': [421.9200134277344, 3392.639892578125, 2158.311767578125, 3397.43994140625], 'text': '\xa0[S][/S] Sal (vel\xa0[S]Gemini[/S]\xa0[S][/S]) O antimonium (alias [S][/S] [S][/S] [S][/S])\xa0ammoniacus (vel [S][/S]) [S][/S] oleum\n', 'tag': 'text'}
{'coordinates': [404.6400146484375, 3456.47998046875, 2121.532958984375, 3461.280029296875], 'text': 'subtile correctum (aliqui silici combusto seu calcinato tribuunt.) Hinc [S][/S]\xa0oleum vitrioli. [S][/S] hy¬\n', 'tag': 'text'}
{'coordinates': [411.1199951171875, 3510.719970703125, 2166.40087890625, 3515.52001953125], 'text': 'drargyrus praecipitatus. [S][/S]\xa0cinabaris. [S][/S]\xa0flos aeris: [S][/S]\xa0cerussa. [S][/S]\xa0ignis. [S][/S]\xa0aqua. [S][/S]\xa0sulphur (vel\n', 'tag': 'text'}
{'coordinates': [1982.1600341796875, 3558.0, 2145.5341796875, 3562.800048828125], 'text': '[S][/S] [S][/S]\xa0vel\n', 'tag': 'footer'}
{'coordinates': [190.55999755859375, 284.3999938964844, 1983.221435546875, 289.1999816894531], 'text': '[S][/S] [S][/S] vel [S][/S]\xa0nam variè pingitur, vt & crucis signo) sed magna est varietas, & in plaerisque aliis domi¬\n', 'tag': 'header'}
{'coordinates': [181.1999969482422, 384.2398376464844, 1989.5478515625, 389.0398254394531], 'text': 'diuinare, & ex praesente narratione, scopoque colligere, quid sibi velint. Hac nota [S][/S]\xa0acetum stillati¬\n', 'tag': 'text'}
{'coordinates': [181.1999969482422, 498.0239562988281, 1988.868896484375, 502.9439697265625], 'text': 'bium ostendit. Sali petraeo tribuuntur & hae [S][/S] [S][/S] [S][/S]\xa0&c. viride aeris [S][/S]. Sed nolo molestus esse\n', 'tag': 'text'}
{'coordinates': [207.1199951171875, 604.7998657226562, 1987.423095703125, 609.5999145507812], 'text': '[S][/S] calx viua: [S][/S] [S][/S] orichalcum, [S][/S]\xa0sal alcali. [S][/S] Galmia [S][/S] aes rustum: [S][/S]\xa0Lazurium. [S][/S]\xa0minium\n', 'tag': 'text'}
{'coordinates': [188.16000366210938, 663.5999145507812, 1977.362548828125, 668.3999633789062], 'text': '[S][/S] lac recens. [S][/S]\xa0atramentum album. [S][/S]\xa0sal crystallinus ex plumbo: & sal alabroth. [S][/S] vitrum.\n', 'tag': 'text'}
{'coordinates': [202.32000732421875, 717.3599243164062, 1987.8023681640625, 722.1599731445312], 'text': '[S][/S] arsenicum [S][/S]\xa0Thutia sublimata. [S][/S]\xa0alumen catinum [S][/S]\xa0magnesia [S][/S] aque fortis [S][/S]\xa0auri¬\n', 'tag': 'text'}
{'coordinates': [621.3599853515625, 1139.06396484375, 1534.22021484375, 1143.9840087890625], 'text': '[S][/S] [S][/S]\xa0[S] Aquarius[/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S]\n', 'tag': 'text'}
{'coordinates': [651.3599853515625, 1186.343994140625, 1508.04833984375, 1191.2640380859375], 'text': '[S]Libra[/S]\xa0[S]Luna[/S]\xa0[S]Virgo[/S]\xa0[S]Mercurius[/S]\xa0[S]]Leo[/S]\xa0[S]Venus[/S]\xa0[S]Cancer[/S]\xa0[S]Sol[/S]\xa0[S]Gemini[/S][S]Mars[/S]\n', 'tag': 'text'}
{'coordinates': [623.52001953125, 1227.143798828125, 1497.792236328125, 1232.0638427734375], 'text': '[S]Taurus[/S]\xa0[S]Jupiter[/S]\xa0[S]Aries[/S]\xa0[S][/S]\xa0quae teutonum more sunt\n', 'tag': 'text'}
{'coordinates': [280.0799865722656, 1357.703857421875, 1831.24951171875, 1362.6239013671875], 'text': 'Scriptura ergo haec: [S][/S]\n', 'tag': 'title'}
{'coordinates': [395.2799987792969, 1552.823974609375, 1009.2324829101562, 1557.7440185546875], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [411.8399963378906, 1603.4400634765625, 828.1699829101562, 1608.239990234375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [527.0399780273438, 1754.183837890625, 1089.233154296875, 1759.1038818359375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [371.760009765625, 1800.4798583984375, 842.3472290039062, 1805.27978515625], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [381.1199951171875, 1848.98388671875, 802.3519897460938, 1853.9039306640625], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [329.5199890136719, 2276.423828125, 1887.2523193359375, 2281.34375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [268.32000732421875, 2659.94384765625, 1915.25439453125, 2664.86376953125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [430.55999755859375, 2974.10400390625, 1534.022705078125, 2979.02392578125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [230.63999938964844, 3333.6240234375, 2122.053955078125, 3338.5439453125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [1041.1199951171875, 407.0401306152344, 2153.123779296875, 411.8401184082031], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [384.9599914550781, 925.9199829101562, 2188.209228515625, 930.7200317382812], 'text': 'cum, indeque extractum florem designare, hanc efformare posset effigiem [S][/S], vt crocum magistralem\n', 'tag': 'text'}
{'coordinates': [382.55999755859375, 982.5601196289062, 2185.1982421875, 987.3601684570312], 'text': 'indicaret; vt florem, hanc: [S][/S], vel [S][/S]. Cerussa plumbi in magisterio ex Saturni charactere deberet ex¬\n', 'tag': 'text'}
{'coordinates': [389.2799987792969, 1040.6400146484375, 2181.181640625, 1045.43994140625], 'text': 'culpi, nempe [S][/S]\xa0vt puncta calcinationem insinuarent. Flos sic: [S][/S]. Dorneiserus male obseruauit\n', 'tag': 'text'}
{'coordinates': [384.9599914550781, 1096.5601806640625, 2186.368408203125, 1101.360107421875], 'text': 'fundamentum, cum eam pinxit [S][/S]. Si omnino Zeta litera ternarii specie Indica expressa cerussam\n', 'tag': 'text'}
{'coordinates': [389.2799987792969, 1359.3602294921875, 2185.188720703125, 1364.16015625], 'text': 'actere [S][/S]\xa0vel [S][/S], quasi inuersus, mutatusque sit Saturnus. Non recte ltaque accommodatur ad stibium.\n', 'tag': 'text'}
{'coordinates': [391.67999267578125, 1464.7200927734375, 2185.862548828125, 1469.52001953125], 'text': 'plumbi sic scribetur [S][/S]\xa0vt intelligamus ealcinatum Saturnum diffluxisse deliquio in aquam: sed aliter\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1522.8001708984375, 2186.149169921875, 1527.60009765625], 'text': 'oleum nempe in hunc modum [S][/S]. Ex liquore enim fit per inclinationem. Caetera qui sunt ingeniosi,\n', 'tag': 'text'}
{'coordinates': [384.9599914550781, 1627.944091796875, 2168.281982421875, 1632.8641357421875], 'text': 'signisicandae essentiae aut magisterio, vel horum initialem figurae adiiciunt: vt [S][/S]\xa0pro coagulare: [S][/S]\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1682.424072265625, 2178.778564453125, 1687.3441162109375], 'text': 'pro figere [S][/S]\xa0calx vitrioli [S][/S]\xa0destillare: [S][/S]\xa0sublimare. Quidam pingunt res vnde ducta meta¬\n', 'tag': 'text'}
{'coordinates': [398.1600036621094, 1749.384033203125, 2189.18798828125, 1754.3040771484375], 'text': 'phora est, vel conceptaculum vulgo vsitatum vt: [S][/S]\xa0caput mortuum: [S][/S]\xa0pro aqua vitae: aut coniiciunt\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1797.1202392578125, 2191.741455078125, 1801.920166015625], 'text': 'literas in schema, quod tamen felicius praestant Ebraei, Chaldaei, Indi etc. vt [S][/S] Spiritus vini, quasi\n', 'tag': 'text'}
{'coordinates': [136.32000732421875, 2856.47998046875, 1942.3367919921875, 2861.280029296875], 'text': 'albae, an. lib. ß: squamae ferri [S]y[/S] iij. argillae bonae lib. ij. saxi murarij rubri, calcis viuae an. lib. ß. fimi equini praeparati, vel\n', 'tag': 'text'}
{'coordinates': [379.20001220703125, 1292.1600341796875, 2186.82666015625, 1296.9599609375], 'text': 'lutum albo ouorum subactum: vel componito cretae, "pollinis molendinorum, vitri an. [S]y[/S] ij. farinae laterum [S]y[/S]. j. oui\n', 'tag': 'text'}
{'coordinates': [381.8399963378906, 2081.52001953125, 2177.006103515625, 2086.320068359375], 'text': 'an. [S]y[/S]. viij. collique facta in massam coeant. Huiusmodi sunt & haec: "Farina laterum pars vna: pollinis è vitro pars tertia:\n', 'tag': 'text'}
{'coordinates': [391.44000244140625, 3456.26416015625, 2189.834716796875, 3461.18408203125], 'text': 'ris lithargyri, & vitri an. [S]y[/S] iij. farinae triticeae lib. ß. ex oui albo fiat pasta", quae intra & extra plagulas inducatur, &\n', 'tag': 'text'}
{'coordinates': [111.5999984741211, 1621.9200439453125, 1913.5340576171875, 1626.719970703125], 'text': '& tamen officinis placet: Aliter: "picis nigrae cerae an. [S]y[/S]. j. Calcis viuae laeuoris lateritij. an. [S]y[/S]. ß. misce ad calorem."\n', 'tag': 'text'}
{'coordinates': [1110.239990234375, 1647.384033203125, 1467.775634765625, 1652.3040771484375], 'text': '(crux[/S]) (crux[/S])\n', 'tag': 'margin'}
{'coordinates': [827.0399780273438, 2520.239990234375, 1168.0421142578125, 2525.0400390625], 'text': '\xa0[S]crux[/S] [S]crux[/S] [S]crux[/S]\n', 'tag': 'text'}
{'coordinates': [100.08000183105469, 3451.43994140625, 1882.7705078125, 3456.239990234375], 'text': 'silem apertilemque pro arbitratu. N. Aquilonaris fenestra cubiculi herilis. [S]Ξ[/S]. [S]Ο[/S] & [S]Π[/S]. Cubi¬\n', 'tag': 'text'}
{'coordinates': [97.68000030517578, 3500.639892578125, 1883.546630859375, 3505.43994140625], 'text': 'cula familiae herilis. P. Xenium, quod si placet distingui diaeta & cubili potest. [S]Σ[/S]. Penu superius:\n', 'tag': 'text'}
{'coordinates': [95.5199966430664, 3548.639892578125, 1892.1455078125, 3553.43994140625], 'text': 'T. Effluxus aquarum laboratorii ferramentis fortibus muniendus. [S]Γ[/S]. Spiracula labotatoril & fora¬\n', 'tag': 'text'}
{'coordinates': [1080.47998046875, 270.7439270019531, 1517.4407958984375, 275.6639404296875], 'text': '[S]crux[/S] [S]crux[/S] [S]crux[/S]\n', 'tag': 'header'}
{'coordinates': [410.8800048828125, 2133.3837890625, 2163.35595703125, 2138.3037109375], 'text': 'oportet esse instructa, vt quantum & quando vsus exigit, admittatur aura. [S]Φ[/S]. Caminus laborato¬\n', 'tag': 'text'}
{'coordinates': [406.55999755859375, 2182.320068359375, 2160.384033203125, 2187.1201171875], 'text': 'rii. [S]X[/S]. Diaeta probatorii. [S]Ψ[/S]. Diaeta penetralis. [S]Ω[/S]. Contignationum culminis valuae. [S]r[/S]. Fumibu¬\n', 'tag': 'text'}
{'coordinates': [658.5599975585938, 2042.18408203125, 733.8024291992188, 2047.1041259765625], 'text': '(:[S]crux[/S]):) (:[S]crux[/S]):) (:[S]crux[/S]):)\n', 'tag': 'text'}
{'coordinates': [970.7999877929688, 1027.4638671875, 1041.4744873046875, 1032.3839111328125], 'text': '(:[S]crux[/S]):) (:[S]crux[/S]):) (:[S]crux[/S]):)\n', 'tag': 'text'}
{'coordinates': [1109.280029296875, 2160.26416015625, 1187.9091796875, 2165.18408203125], 'text': ')[S]crux[/S]( )[S]crux[/S](\n', 'tag': 'text'}
{'coordinates': [1038.719970703125, 634.1040649414062, 1108.21337890625, 639.0240478515625], 'text': ')[S]crux[/S]( )[S]crux[/S](\n', 'tag': 'text'}
{'coordinates': [1543.6800537109375, 2153.27978515625, 2184.681640625, 2158.079833984375], 'text': 'tur fornaces. [S]Saturnus[/S] Vstrina argenti est\n', 'tag': 'text'}
{'coordinates': [1543.6800537109375, 2201.27978515625, 2184.14111328125, 2206.079833984375], 'text': 'absque tegula:\xa0[S]Jupiter[/S]\xa0eiusdem vsus\n', 'tag': 'text'}
{'coordinates': [1539.1199951171875, 2301.599853515625, 2184.455078125, 2306.39990234375], 'text': 'formata.\xa0[S]Mars[/S]\xa0fusoria capsa popularis\n', 'tag': 'text'}
{'coordinates': [1541.280029296875, 2498.639892578125, 2185.93115234375, 2503.43994140625], 'text': 'desuper follibus.\xa0[S]Sol[/S]\xa0Ventosa est, seu\n', 'tag': 'text'}
{'coordinates': [2019.5999755859375, 3639.599853515625, 2146.934326171875, 3644.39990234375], 'text': '[S]Mercurius[/S] \xa0Ca¬\n', 'tag': 'footer'}
{'coordinates': [1291.43994140625, 298.3199157714844, 1895.412841796875, 303.1199035644531], 'text': '[S]Mercurius[/S]\xa0Caementatorius Panthei, quan¬\n', 'tag': 'text'}
{'coordinates': [1242.47998046875, 838.5598754882812, 1881.9483642578125, 843.3599243164062], 'text': 'remouenda aqua est.\xa0[S]Luna[/S]\xa0Vstrina A¬\n', 'tag': 'text'}
{'coordinates': [1526.8800048828125, 2421.599853515625, 2188.16015625, 2426.39990234375], 'text': 'figies. [S]Sol[/S] clausum habet focum, &\n', 'tag': 'text'}
{'coordinates': [1521.8399658203125, 2569.199951171875, 2179.95166015625, 2574.0], 'text': 'rali & metallica instructum. [S]luna[/S] exhi¬\n', 'tag': 'text'}
{'coordinates': [1285.199951171875, 400.0799255371094, 1926.544189453125, 404.8799133300781], 'text': 'coctorio signat;\xa0[S]Jupiter[/S].\xa0feriantem per¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2330.639892578125, 1888.8544921875, 2335.43994140625], 'text': 'be lapideo, sufficiat, [S]Capricornus[/S] orbis lapide¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2379.35986328125, 1886.61328125, 2384.159912109375], 'text': 'us:\xa0[S]Gemini[/S]\xa0pedamentum cum macerie\n', 'tag': 'text'}
{'coordinates': [1239.5999755859375, 2426.90380859375, 1891.1217041015625, 2431.82373046875], 'text': 'detussata ab antico effractum:\xa0[S]Aquarius[/S]\xa0pe¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2533.94384765625, 1893.4879150390625, 2538.86376953125], 'text': 'clausa cum pilis. [S]Sagittarius[/S]\xa0focus stractus\n', 'tag': 'text'}
{'coordinates': [1237.43994140625, 2582.8798828125, 1888.95703125, 2587.679931640625], 'text': 'super pedamento. In effigie [S]Gemini[/S], li¬\n', 'tag': 'text'}
{'coordinates': [100.80000305175781, 2828.639892578125, 1906.6788330078125, 2833.43994140625], 'text': 'muri interni & angustiora. E. interstitium triangulare inter alas. In pictura [S]Aquarius[/S]\xa0litera. F. signat pilas\n', 'tag': 'text'}
{'coordinates': [432.7200012207031, 2864.423828125, 2174.7978515625, 2869.34375], 'text': 'Tres fulminatorii species offeruntur\xa0[S]Mercurius[/S] vulgata in Ioachimicis, Sclaccevvaldensibus & aliorum lo¬\n', 'tag': 'text'}
{'coordinates': [382.0799865722656, 2913.14404296875, 2163.592529296875, 2918.06396484375], 'text': 'corum officinis cum testudine ferrea:\xa0[S]Leo[/S]\xa0Liberimontana, qualis est &\xa0[S]Libra[/S], sed diuersa orificiorum\n', 'tag': 'text'}
{'coordinates': [386.3999938964844, 2962.34375, 2169.555419921875, 2967.263671875], 'text': 'dispositione In signa [S]Mercurius[/S], character A. notat pedamenti ambitum ex saxo natiuo. B. spiracula: C. pi¬\n', 'tag': 'text'}
{'coordinates': [375.3599853515625, 3353.303955078125, 2159.75830078125, 3358.223876953125], 'text': 'quam & per orificium ergasticum immittantur. In schemate [S]Leo[/S] M. pedamentum furni: N. fornix\n', 'tag': 'text'}
{'coordinates': [371.0400085449219, 3548.423828125, 2153.776123046875, 3553.34375], 'text': 'intus pilas triangulas habent, & viarum diuortia seu biuium decussatum. In pictura\xa0[S]Libra[/S]\xa0X. plantam muratam\n', 'tag': 'text'}
{'coordinates': [378.0, 460.7998962402344, 1958.2998046875, 466.3198547363281], 'text': 'autem etiam folles ex praecepto Geberi. Focus est vt praecedenti pagina liquet.\n) : [S]crux[/S] : (\n', 'tag': 'text'}
{'coordinates': [536.6400146484375, 510.9598083496094, 2181.16015625, 515.7598266601562], 'text': '[S][/S] Morauorum fulminatorium.\xa0[S][/S]\xa0Calix fulminatorius cum lacuna & fenestris in pedamento ad\n', 'tag': 'text'}
{'coordinates': [383.0400085449219, 560.3999633789062, 2184.374755859375, 565.2000122070312], 'text': 'recipiendum lithargyrum, & auertendos halitus.\xa0[S][/S]\xa0Circulus super foco concamerato, ex cuius strato\n', 'tag': 'text'}
{'coordinates': [1197.5999755859375, 804.9597778320312, 2165.358154296875, 809.7598266601562], 'text': '[S]Saturnus[/S]\xa0Fulminatorium, seu cineritium Hungarorum con¬\n', 'tag': 'text'}

In [26]:
def add_tag_info_to_char_mapping(full_text, char_to_source):
    """
    Parse inline tags like [GR]...[/GR], [M]...[/M], [S]...[/S] in full_text
    and attach a "tags" field (list of active tags) to char_to_source[char_idx].
    """
    active_tags = []  # stack / list of currently open tags
    i = 0
    n = len(full_text)

    while i < n:
        ch = full_text[i]

        if ch == "[":
            # Try to find the closing bracket of this [TAG] or [/TAG]
            close = full_text.find("]", i + 1)
            if close == -1:
                # malformed tag, treat as normal char
                if i in char_to_source and active_tags:
                    tags_set = char_to_source[i].setdefault("tags", set())
                    tags_set.update(active_tags)
                i += 1
                continue

            content = full_text[i + 1:close]

            if content.startswith("/"):
                # closixng tag, e.g. [/GR]
                label = content[1:]
                # remove from active_tags (LIFO or first match)
                if active_tags and active_tags[-1] == label:
                    active_tags.pop()
                elif label in active_tags:
                    active_tags.remove(label)
                # We don't assign tags to the '['...']' characters themselves here
            else:
                # opening tag, e.g. [GR]
                label = content
                active_tags.append(label)

            # skip past the closing ']'
            i = close + 1
            continue

        else:
            # normal character: assign currently active tags (if any)
            if i in char_to_source and active_tags:
                tags_set = char_to_source[i].setdefault("tags", set())
                tags_set.update(active_tags)
            i += 1

    # normalize sets → lists (so they are JSON-serializable, nicer to inspect)
    for info in char_to_source.values():
        if "tags" in info and isinstance(info["tags"], set):
            info["tags"] = sorted(info["tags"])

    return char_to_source

In [137]:
import re
import unicodedata
from spacy.tokens import Token, Doc
from spacy.language import Language


# -------------------------------------------------------------------
# 0. Token / Doc extensions
# -------------------------------------------------------------------
for ext, default in [
    ("pages", None),
    ("textblocks", None),
    ("tags", None),
    ("block_type", None),
]:
    if not Token.has_extension(ext):
        Token.set_extension(ext, default=default)

if not Doc.has_extension("char_to_source"):
    Doc.set_extension("char_to_source", default=None)


# -------------------------------------------------------------------
# CLEANER: keep tags exact, clean only outside-tag regions
# -------------------------------------------------------------------
def text_cleaner_keep_tags(raw_text):
    """
    Clean Latin text but NEVER modify anything inside markup spans like:
        [GR]...[/GR], [S]...[/S], [M]...[/M]

    Behavior:
      - Split raw text into TAG / NON-TAG parts
      - Maintain a stack (to allow nested tags)
      - CLEAN only outside-tag parts
      - Inside-tag content is preserved exactly and NFC-normalized
    """

    parts = re.split(r"(\[[A-Za-z]+]|\[/[A-Za-z]+])", raw_text)
    cleaned_parts = []
    stack = []

    for part in parts:

        # Opening tag
        if re.fullmatch(r"\[[A-Za-z]+]", part):
            stack.append(part[1:-1])
            cleaned_parts.append(part)
            continue

        # Closing tag
        if re.fullmatch(r"\[/[A-Za-z]+]", part):
            name = part[2:-1]
            if stack and stack[-1] == name:
                stack.pop()
            cleaned_parts.append(part)
            continue

        # Inside a tag span → do not modify, only normalize
        if stack:
            cleaned_parts.append(unicodedata.normalize("NFC", part))
            continue

        # Outside tags → apply Latin cleaning
        x = part
        x = x.replace("¬\n", "").replace("\n", " ")
        x = x.replace("ß", "ss").replace("ij", "ii")
        x = re.sub(r"\s\s+", " ", x)
        x = re.sub(r'\b(\w)(\w*)\b', lambda m: m.group(1) + m.group(2).lower(), x)
        x = x.replace(". &", ", &")
        x = x.replace("v", "u").replace("V", "U")

        cleaned_parts.append(x)

    return "".join(cleaned_parts)


# -------------------------------------------------------------------
# 1. Build raw + clean-with-tags + mapping
# -------------------------------------------------------------------
def process_textblocks(textblocks):
    raw_full = ""
    clean_full = ""
    raw_to_clean = {}
    char_src = {}

    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):

            if tb["tag"] not in {"text", "title", "margin"}:
                continue

            raw_text = tb["text"]
            clean_text = text_cleaner_keep_tags(raw_text)

            r0 = len(raw_full)
            c0 = len(clean_full)

            r_i = c_i = 0
            while r_i < len(raw_text) and c_i < len(clean_text):

                rc = raw_text[r_i]
                cc = clean_text[c_i]

                raw_idx = r0 + r_i
                clean_idx = c0 + c_i

                if rc == cc:
                    raw_to_clean[raw_idx] = clean_idx
                    char_src[clean_idx] = {
                        "page_idx": page_idx,
                        "textblock_idx": tb_idx,
                        "textblock_type": tb["tag"],
                    }
                    r_i += 1
                    c_i += 1
                    continue

                # raw has markup [TAG]
                if raw_text.startswith("[", r_i):
                    end = raw_text.find("]", r_i)
                    if end == -1:
                        # malformed → treat as normal
                        raw_to_clean[raw_idx] = clean_idx
                        char_src[clean_idx] = {
                            "page_idx": page_idx,
                            "textblock_idx": tb_idx,
                            "textblock_type": tb["tag"],
                        }
                        r_i += 1
                        c_i += 1
                    else:
                        # skip tag entirely in raw
                        for skip in range(r_i, end + 1):
                            raw_to_clean[r0 + skip] = None
                        r_i = end + 1
                    continue

                # cleaned version differs (ASCII conversion etc.)
                raw_to_clean[raw_idx] = clean_idx
                char_src[clean_idx] = {
                    "page_idx": page_idx,
                    "textblock_idx": tb_idx,
                    "textblock_type": tb["tag"],
                }
                r_i += 1
                c_i += 1

            # remaining raw chars (rare)
            while r_i < len(raw_text):
                raw_to_clean[r0 + r_i] = None
                r_i += 1

            raw_full += raw_text
            clean_full += clean_text

    return raw_full, clean_full, raw_to_clean, char_src


# -------------------------------------------------------------------
# 2. Greek-aware tag extractor
# -------------------------------------------------------------------
GREEK_RE = re.compile(r"[\u0370-\u03FF\u1F00-\u1FFF]")

def extract_tags_from_raw(raw_text):
    """
    Extract tags with Greek awareness:

    RULES:
      - Explicit [GR] ... [/GR] → exact span
      - Lone [GR] without closing → auto-close when Greek stops
      - Greek without tags → implicit GR tag on those chars
    """

    raw_tags = {}
    markup_spans = []

    TAG = re.compile(r"\[(?P<tag>[A-Za-z]+)]|\[/(?P<etag>[A-Za-z]+)]")
    matches = list(TAG.finditer(raw_text))

    # record tag token spans
    for m in matches:
        markup_spans.append(m.span())

    # explicit [GR] ... [/GR]
    open_pos = None
    for m in matches:
        start, end = m.span()
        tag = m.group("tag")
        etag = m.group("etag")

        if tag == "GR":
            open_pos = end
        elif etag == "GR" and open_pos is not None:
            for i in range(open_pos, start):
                if GREEK_RE.search(raw_text[i]):
                    raw_tags.setdefault(i, set()).add("GR")
            open_pos = None

    # unclosed [GR] → close at end of Greek run
    if open_pos is not None:
        i = open_pos
        while i < len(raw_text) and GREEK_RE.search(raw_text[i]):
            raw_tags.setdefault(i, set()).add("GR")
            i += 1

    # implicit GR (Greek outside tags)
    for idx, ch in enumerate(raw_text):
        if GREEK_RE.search(ch):
            raw_tags.setdefault(idx, set()).add("GR")

    return raw_tags, markup_spans


# -------------------------------------------------------------------
# 3. raw → clean tag mapping
# -------------------------------------------------------------------
def map_raw_tags_to_clean(raw_tags, raw_to_clean):
    clean_tags = {}
    for raw_idx, tagset in raw_tags.items():
        clean_idx = raw_to_clean.get(raw_idx)
        if clean_idx is not None:
            clean_tags.setdefault(clean_idx, set()).update(tagset)
    return clean_tags


# -------------------------------------------------------------------
# 4. remove markup from cleaned Latin text
# -------------------------------------------------------------------
def remove_markup(clean_text):
    return re.sub(r"\[[A-Za-z]+\]|\[/[A-Za-z]+\]", "", clean_text)


# -------------------------------------------------------------------
# 5. High-level processor
# -------------------------------------------------------------------
def process_with_source_tracking(textblocks, nlp):

    raw_text, clean_with_tags, raw_to_clean, char_src = process_textblocks(textblocks)

    raw_tag_map, _ = extract_tags_from_raw(raw_text)

    clean_tag_map = map_raw_tags_to_clean(raw_tag_map, raw_to_clean)

    clean_text_final = remove_markup(clean_with_tags)

    # inject tag info into char_src
    for clean_idx, tagset in clean_tag_map.items():
        if clean_idx in char_src:
            char_src[clean_idx]["tags"] = sorted(tagset)

    doc = nlp.make_doc(clean_text_final)
    doc._.char_to_source = char_src

    for name, proc in nlp.pipeline:
        doc = proc(doc)

    return doc


# -------------------------------------------------------------------
# 6. Source tracker: assign metadata to tokens
# -------------------------------------------------------------------
@Language.component("source_tracker")
def source_tracker(doc):
    cts = doc._.char_to_source
    if cts is None:
        return doc

    for token in doc:
        pages, tb, blocktypes, tags = set(), set(), set(), set()

        for i in range(token.idx, token.idx + len(token.text)):
            info = cts.get(i)
            if not info:
                continue
            pages.add(info["page_idx"])
            tb.add(info["textblock_idx"])
            blocktypes.add(info["textblock_type"])
            if "tags" in info:
                tags.update(info["tags"])

        token._.pages = sorted(pages) if pages else None
        token._.textblocks = sorted(tb) if tb else None
        token._.block_type = next(iter(blocktypes)) if blocktypes else "text"
        token._.tags = sorted(tags) if tags else None

    return doc


# -------------------------------------------------------------------
# 7. blocktype-based sentence splitter
# -------------------------------------------------------------------
@Language.component("blocktype_sentencizer")
def blocktype_sentencizer(doc):
    prev_bt = None
    for token in doc:
        bt = token._.block_type
        if prev_bt is None or bt != prev_bt:
            token.is_sent_start = True
        prev_bt = bt
    return doc


# -------------------------------------------------------------------
# Insert components into pipeline
# -------------------------------------------------------------------
nlp = tomela.nlp  # your existing model

if "source_tracker" in nlp.pipe_names:
    nlp.remove_pipe("source_tracker")
nlp.add_pipe("source_tracker", before="senter")

if "blocktype_sentencizer" in nlp.pipe_names:
    nlp.remove_pipe("blocktype_sentencizer")
nlp.add_pipe("blocktype_sentencizer", after="source_tracker")

In [ ]:
doc = process_with_source_tracking(textblocks, tomela.nlp)

In [133]:
for t in doc:
    if t._.tags:
        print("TAG:", repr(t.text), t._.tags)

TAG: 'χιμικωτερα' ['GR']
TAG: 'essent' ['GR']
TAG: 'commentum' ['GR']
TAG: ',' ['GR']
TAG: '&' ['GR']
TAG: 'atomis' ['GR']
TAG: 'tibi' ['GR']
TAG: 'eundem' ['GR']
TAG: 'Bulcasim' ['GR']
TAG: 'passim' ['GR']
TAG: 'mores' ['GR']
TAG: 'thessalicos' ['GR']
TAG: 'libera' ['GR']
TAG: ',' ['GR']
TAG: 'si' ['GR']
TAG: 'potes' ['GR']
TAG: 'prosyllogismus' ['GR']
TAG: 'aeque' ['GR']
TAG: 'Discat' ['GR']
TAG: 'Censor' ['GR']
TAG: 'specialium' ['GR']
TAG: 'extractum' ['GR']
TAG: '.' ['GR']
TAG: 'In' ['GR']
TAG: 'hoc' ['GR']
TAG: 'est' ['GR']
TAG: 'ασυμβλητον' ['GR']
TAG: 'maxime' ['GR']
TAG: 'nutritur' ['GR']
TAG: 'Et' ['GR']
TAG: 'in' ['GR']
TAG: 'quisquis' ['GR']
TAG: 'hoc' ['GR']
TAG: 'statuit' ['GR']
TAG: ',' ['GR']
TAG: 'nec' ['GR']
TAG: 'ab' ['GR']
TAG: 'habitus' ['GR']
TAG: '.' ['GR']
TAG: 'Si' ['GR']
TAG: 'cognitio' ['GR']
TAG: 'καθ' ['GR']
TAG: "'" ['GR']
TAG: 'εκαστα' ['GR']
TAG: 'eodem' ['GR']
TAG: 'explorationes' ['GR']
TAG: 'inuenerunt' ['GR']
TAG: 'omne' ['GR']
TAG: 'compositum' ['GR']
TAG: 'emolumentum' ['GR']
TAG: 'scammonium' ['GR']
TAG: ',' ['GR']
TAG: 'Elleborum' ['GR']
TAG: 'quia' ['GR']
TAG: 'utrumque' ['GR']
TAG: 'Sin' ['GR']
TAG: 'autem' ['GR']
TAG: 'ciues' ['GR']
TAG: 'Parisiorum' ['S']
TAG: 'unum' ['sic']
TAG: 'poculum' ['sic']
TAG: 'uini' ['sic']
TAG: 'optimi' ['sic']
TAG: 'ad' ['sic']
TAG: 'recreandum' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'integrum' ['sic']
TAG: 'dolium' ['sic']
TAG: 'uappae' ['sic']
TAG: ',' ['sic']
TAG: 'aut' ['sic']
TAG: 'aquae' ['sic']
TAG: 'lutulentae' ['sic']
TAG: '?' ['sic']
TAG: 'Cum' ['sic']
TAG: 'celertiur' ['sic']
TAG: 'uites' ['sic']
TAG: 'sunt' ['sic']
TAG: 'reficiendae' ['sic']
TAG: ',' ['sic']
TAG: 'quis' ['sic']
TAG: 'non' ['sic']
TAG: 'guttam' ['sic']
TAG: 'olei' ['sic']
TAG: 'cynamomi' ['sic']
TAG: 'efficaciorem' ['sic']
TAG: '&' ['sic']
TAG: 'utiliorem' ['sic']
TAG: 'sentit' ['sic']
TAG: 'integra' ['sic']
TAG: 'libra' ['sic']
TAG: 'corticis' ['sic']
TAG: '?' ['sic']
TAG: 'Commendat' ['sic']
TAG: 'paruitas' ['sic']
TAG: 'efficax' ['sic']
TAG: 'medicinam' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'uituperat' ['sic']
TAG: ',' ['sic']
TAG: 'nisi' ['sic']
TAG: 'fonte' ['sic']
TAG: 'non' ['sic']
TAG: 'tantum' ['sic']
TAG: 'pusilla' ['sic']
TAG: 'est' ['sic']
TAG: ',' ['sic']
TAG: 'uerum' ['sic']
TAG: 'etiam' ['sic']
TAG: 'euanida' ['sic']
TAG: 'integro' ['sic']
TAG: 'praecellentiore' ['sic']
TAG: '.' ['sic']
TAG: 'Assumtio' ['sic']
TAG: 'uana' ['sic']
TAG: 'est' ['sic']
TAG: 'si' ['sic']
TAG: 'per' ['sic']
TAG: 'se' ['sic']
TAG: 'iudicetur' ['sic']
TAG: '.' ['sic']
TAG: 'Sin' ['sic']
TAG: 'autem' ['sic']
TAG: 'impostores' ['sic']
TAG: 'Paracelsicos' ['sic']
TAG: 'respiciamus' ['sic']
TAG: ',' ['sic']
TAG: 'qui' ['sic']
TAG: 'muscerdam' ['sic']
TAG: 'quoque' ['sic']
TAG: 'magno' ['sic']
TAG: 'uendunt' ['sic']
TAG: ',' ['sic']
TAG: 'ad' ['sic']
TAG: 'coruos' ['sic']
TAG: 'cum' ['sic']
TAG: 'eis' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'furcam' ['sic']
TAG: '.' ['sic']
TAG: 'Quae' ['sic']
TAG: 'per' ['sic']
TAG: 'se' ['sic']
TAG: 'sunt' ['sic']
TAG: 'artis' ['sic']
TAG: ',' ['sic']
TAG: 'si' ['sic']
TAG: 'praestant' ['sic']
TAG: 'id' ['sic']
TAG: 'quod' ['sic']
TAG: 'debent' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'sunt' ['sic']
TAG: 'cara' ['sic']
TAG: '.' ['sic']
TAG: 'Carior' ['sic']
TAG: 'enim' ['sic']
TAG: 'propria' ['sic']
TAG: 'cuiusque' ['sic']
TAG: 'salus' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'emolumentum' ['sic']
TAG: 'patriae' ['sic']
TAG: '.' ['sic']
TAG: 'Quod' ['sic']
TAG: 'si' ['sic']
TAG: 'comparationem' ['sic']
TAG: 'instituas' ['sic']
TAG: 'cum' ['sic']
TAG: 'integris' ['sic']
TAG: ',' ['sic']
TAG: 'inuenias' ['sic']
TAG: 'multa' ['sic']
TAG: 'integra' ['sic']
TAG: 'multis' ['sic']
TAG: 'chymicis' ['sic']
TAG: 'esse' ['sic']
TAG: 'praeciosiora' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'moschum' ['sic']
TAG: ',' ['sic']
TAG: 'Ambram' ['sic']
TAG: ',' ['sic']
TAG: 'Bezoar' ['sic']
TAG: 'uerum' ['sic']
TAG: ',' ['sic']
TAG: 'uniones' ['sic']
TAG: ',' ['sic']
TAG: 'Adamantes' ['sic']
TAG: '&c' ['sic']
TAG: '.' ['sic']
TAG: 'Omnino' ['sic']
TAG: 'hoc' ['sic']
TAG: 'argumentum' ['sic']
TAG: 'contra' ['sic']
TAG: 'Alchymiam' ['sic']
TAG: 'nihil' ['sic']
TAG: 'concludit' ['sic']
TAG: ',' ['sic']
TAG: 'ignorat' ['sic']
TAG: 'que' ['sic']
TAG: 'Elenchum' ['sic']
TAG: ',' ['sic']
TAG: 'cum' ['sic']
TAG: 'entio' ['sic']
TAG: '&' ['sic']
TAG: 'uenditio' ['sic']
TAG: 'non' ['sic']
TAG: 'sint' ['sic']
TAG: 'res' ['sic']
TAG: 'Chymicae' ['sic']
TAG: '.' ['sic']
TAG: 'sed' ['sic']
TAG: 'spectent' ['sic']
TAG: 'ad' ['sic']
TAG: 'mercatores' ['sic']
TAG: '&' ['sic']
TAG: 'contractus' ['sic']
TAG: 'ciuiles' ['sic']
TAG: ',' ['sic']
TAG: 'possint' ['sic']
TAG: 'que' ['sic']
TAG: 'pluribus' ['sic']
TAG: 'uariari' ['sic']
TAG: 'circumstantiis' ['sic']
TAG: ',' ['sic']
TAG: 'modo' ['sic']
TAG: 'que' ['sic']
TAG: 'pluris' ['sic']
TAG: 'ueneant' ['sic']
TAG: ',' ['sic']
TAG: 'modo' ['sic']
TAG: 'minoris' ['sic']
TAG: '.' ['sic']
TAG: 'Inscitiam' ['sic']
TAG: 'suam' ['sic']
TAG: '&' ['sic']
TAG: 'proteruiam' ['sic']
TAG: 'prodidit' ['sic']
TAG: 'Censor' ['sic']
TAG: 'cum' ['sic']
TAG: 'de' ['sic']
TAG: 'drachma' ['sic']
TAG: 'olei' ['sic']
TAG: '&' ['sic']
TAG: 'una' ['sic']
TAG: 'libra' ['sic']
TAG: 'materialium' ['sic']
TAG: 'garrit' ['sic']
TAG: '.' ['sic']
TAG: 'Aut' ['sic']
TAG: 'enim' ['sic']
TAG: 'ex' ['sic']
TAG: 'arte' ['sic']
TAG: 'processum' ['sic']
TAG: 'est' ['sic']
TAG: 'operando' ['sic']
TAG: 'aut' ['sic']
TAG: 'inerter' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'oscitanter' ['sic']
TAG: '.' ['sic']
TAG: 'Si' ['sic']
TAG: 'hoc' ['sic']
TAG: ',' ['sic']
TAG: 'nihil' ['sic']
TAG: 'culpae' ['sic']
TAG: 'ad' ['sic']
TAG: 'artem' ['sic']
TAG: 'pertinet' ['sic']
TAG: '.' ['sic']
TAG: 'Si' ['sic']
TAG: 'illud' ['sic']
TAG: ',' ['sic']
TAG: 'euanida' ['sic']
TAG: 'fuit' ['sic']
TAG: 'materia' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'respectu' ['sic']
TAG: 'uirtutis' ['sic']
TAG: 'medicae' ['sic']
TAG: ',' ['sic']
TAG: 'quae' ['sic']
TAG: 'debebat' ['sic']
TAG: 'inesse' ['sic']
TAG: ',' ['sic']
TAG: 'cadauer' ['sic']
TAG: 'potius' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'materia' ['sic']
TAG: ';' ['sic']
TAG: 'quam' ['sic']
TAG: 'totam' ['sic']
TAG: 'si' ['sic']
TAG: 'in' ['sic']
TAG: 'usum' ['sic']
TAG: 'uertisses' ['sic']
TAG: ',' ['sic']
TAG: 'quantum' ['sic']
TAG: 'queso' ['sic']
TAG: 'effecisses' ['sic']
TAG: '?' ['sic']
TAG: 'An' ['sic']
TAG: 'non' ['sic']
TAG: 'copia' ['sic']
TAG: 'corporis' ['sic']
TAG: 'uani' ['sic']
TAG: 'plus' ['sic']
TAG: 'detrimenti' ['sic']
TAG: 'attulisses' ['sic']
TAG: 'laboranti' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'commodi' ['sic']
TAG: '?' ['sic']
TAG: 'At' ['sic']
TAG: 'drachma' ['sic']
TAG: 'una' ['sic']
TAG: 'potuit' ['sic']
TAG: 'in' ['sic']
TAG: 'multas' ['sic']
TAG: 'doses' ['sic']
TAG: 'efficaces' ['sic']
TAG: 'dispensari' ['sic']
TAG: '.' ['sic']
TAG: 'Sed' ['sic']
TAG: 'ponatur' ['sic']
TAG: '&' ['sic']
TAG: 'materia' ['sic']
TAG: 'bona' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'operatio' ['sic']
TAG: 'studiosa' ['sic']
TAG: ',' ['sic']
TAG: 'perita' ['sic']
TAG: 'que' ['sic']
TAG: ':' ['sic']
TAG: 'mendacem' ['sic']
TAG: 'dico' ['sic']
TAG: 'esse' ['sic']
TAG: ',' ['sic']
TAG: 'quisquis' ['sic']
TAG: 'ita' ['sic']
TAG: 'de' ['sic']
TAG: 'omnibus' ['sic']
TAG: ',' ['sic']
TAG: 'aut' ['sic']
TAG: 'pluribus' ['sic']
TAG: 'pronunciat' ['sic']
TAG: '.' ['sic']
TAG: 'Cum' ['sic']
TAG: 'ex' ['sic']
TAG: 'succino' ['sic']
TAG: 'fit' ['sic']
TAG: 'oleum' ['sic']
TAG: ',' ['sic']
TAG: 'libra' ['sic']
TAG: 'una' ['sic']
TAG: 'interdum' ['sic']
TAG: 'plus' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'dimidiam' ['sic']
TAG: 'fundit' ['sic']
TAG: '.' ['sic']
TAG: 'Experite' ['sic']
TAG: '&' ['sic']
TAG: 'de' ['sic']
TAG: 'terebinthina' ['sic']
TAG: ',' ['sic']
TAG: 'similibus' ['sic']
TAG: 'que' ['sic']
TAG: '.' ['sic']
TAG: 'Fernelius' ['sic']
TAG: 'lib' ['sic']
TAG: '.' ['sic']
TAG: '4' ['sic']
TAG: '.' ['sic']
TAG: 'meth' ['sic']
TAG: '.' ['sic']
TAG: 'cap' ['sic']
TAG: '.' ['sic']
TAG: '10' ['sic']
TAG: 'ex' ['sic']
TAG: 'libra' ['sic']
TAG: 'media' ['sic']
TAG: 'pulueris' ['sic']
TAG: 'prolicit' ['sic']
TAG: 'unciam' ['sic']
TAG: 'olei' ['sic']
TAG: 'synceri' ['sic']
TAG: '.' ['sic']
TAG: 'In' ['sic']
TAG: 'aliquibus' ['sic']
TAG: 'autem' ['sic']
TAG: 'satis' ['sic']
TAG: 'paruam' ['sic']
TAG: 'quantitatem' ['sic']
TAG: 'etiam' ['sic']
TAG: 'studio' ['sic']
TAG: 'spectari' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'in' ['sic']
TAG: 'quintis' ['sic']
TAG: 'essentiis' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'tincturis' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'imus' ['sic']
TAG: 'inficias' ['sic']
TAG: '.' ['sic']
TAG: 'Sed' ['sic']
TAG: 'hoc' ['sic']
TAG: 'quia' ['sic']
TAG: 'uires' ['sic']
TAG: 'habet' ['sic']
TAG: 'summas' ['sic']
TAG: 'est' ['sic']
TAG: 'que' ['sic']
TAG: 'ad' ['sic']
TAG: 'usum' ['sic']
TAG: 'longe' ['sic']
TAG: 'precellentissimum' ['sic']
TAG: ',' ['sic']
TAG: 'artem' ['sic']
TAG: 'exornat' ['sic']
TAG: ';' ['sic']
TAG: 'non' ['sic']
TAG: 'dedecorat' ['sic']
TAG: '.' ['sic']
TAG: 'Cum' ['sic']
TAG: 'contra' ['sic']
TAG: 'Gramanum' ['sic']
TAG: 'scriberemus' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'argumentum' ['sic']
TAG: 'ex' ['sic']
TAG: 'parua' ['sic']
TAG: 'dosi' ['sic']
TAG: 'repelleremus' ['sic']
TAG: ',' ['sic']
TAG: 'dicendum' ['sic']
TAG: 'erat' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'esse' ['sic']
TAG: 'istud' ['sic']
TAG: 'perpetuum' ['sic']
TAG: 'atque' ['sic']
TAG: 'ideo' ['sic']
TAG: 'non' ['sic']
TAG: 'habere' ['sic']
TAG: 'uim' ['sic']
TAG: 'catholicam' ['sic']
TAG: ',' ['sic']
TAG: 'quandoquidem' ['sic']
TAG: 'euenire' ['sic']
TAG: 'potest' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'iusta' ['sic']
TAG: 'copia' ['sic']
TAG: 'sit' ['sic']
TAG: 'ad' ['sic']
TAG: 'usum' ['sic']
TAG: 'commodior' ['sic']
TAG: 'tutior' ['sic']
TAG: 'que' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'exilis' ['sic']
TAG: 'admodum' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'praebeat' ['sic']
TAG: 'imperitus' ['sic']
TAG: '&' ['sic']
TAG: 'stolidus' ['sic']
TAG: 'aliquis' ['sic']
TAG: 'exgrege' ['sic']
TAG: 'Paracelsi' ['sic']
TAG: '.' ['sic']
TAG: 'Si' ['sic']
TAG: 'hoc' ['sic']
TAG: 'modo' ['sic']
TAG: 'uoluit' ['sic']
TAG: 'adhibere' ['sic']
TAG: 'argumentum' ['sic']
TAG: 'Censor' ['sic']
TAG: ',' ['sic']
TAG: 'circumspectius' ['sic']
TAG: 'pronunciasset' ['sic']
TAG: 'rationem' ['sic']
TAG: 'que' ['sic']
TAG: 'habuisset' ['sic']
TAG: 'circumstantiarum' ['sic']
TAG: ',' ['sic']
TAG: 'nec' ['sic']
TAG: 'tam' ['sic']
TAG: 'rustice' ['sic']
TAG: '&' ['sic']
TAG: 'arroganter' ['sic']
TAG: 'chymica' ['sic']
TAG: 'damnasset' ['sic']
TAG: '.' ['sic']
TAG: '"Ii' ['sic']
TAG: '.' ['sic']
TAG: 'Periculosa' ['sic']
TAG: 'non' ['sic']
TAG: 'sunt' ['sic']
TAG: 'sine' ['sic']
TAG: 'noxa' ['sic']
TAG: '.' ['sic']
TAG: 'Chymica' ['sic']
TAG: 'sunt' ['sic']
TAG: 'periculosa' ['sic']
TAG: '.' ['sic']
TAG: 'Ergo' ['sic']
TAG: '.' ['sic']
TAG: 'Minor' ['sic']
TAG: 'probatur' ['sic']
TAG: ':' ['sic']
TAG: '1' ['sic']
TAG: '.' ['sic']
TAG: 'quia' ['sic']
TAG: 'Antimonium' ['sic']
TAG: '&' ['sic']
TAG: 'praecipitatus' ['sic']
TAG: 'sunt' ['sic']
TAG: 'periculosa' ['sic']
TAG: ',' ['sic']
TAG: 'uitam' ['sic']
TAG: 'que' ['sic']
TAG: 'demoliuntur' ['sic']
TAG: '.' ['sic']
TAG: '2' ['sic']
TAG: '.' ['sic']
TAG: 'quia' ['sic']
TAG: 'secus' ['sic']
TAG: 'habent' ['sic']
TAG: 'ac' ['sic']
TAG: 'uulgaria' ['sic']
TAG: ',' ['sic']
TAG: 'quae' ['sic']
TAG: 'si' ['sic']
TAG: 'non' ['sic']
TAG: 'prosunt' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'nocent' ['sic']
TAG: ';' ['sic']
TAG: '(illa' ['sic']
TAG: 'uero' ['sic']
TAG: 'etiam' ['sic']
TAG: 'interim' ['sic']
TAG: 'dum' ['sic']
TAG: 'prosunt' ['sic']
TAG: ',' ['sic']
TAG: 'nocent' ['sic']
TAG: ')' ['sic']
TAG: '3' ['sic']
TAG: '.' ['sic']
TAG: 'quia' ['sic']
TAG: 'in' ['sic']
TAG: 'partibus' ['sic']
TAG: 'nobilioribus' ['sic']
TAG: 'relinquunt' ['sic']
TAG: 'malam' ['sic']
TAG: 'dispositionem' ['sic']
TAG: ':' ['sic']
TAG: '4' ['sic']
TAG: '.' ['sic']
TAG: 'quia' ['sic']
TAG: 'deleteria' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'naturae' ['sic']
TAG: 'inimica' ['sic']
TAG: ';' ['sic']
TAG: 'cum' ['sic']
TAG: 'contra' ['sic']
TAG: 'Galenica' ['sic']
TAG: '&' ['sic']
TAG: 'Arabica' ['sic']
TAG: 'sint' ['sic']
TAG: 'amica' ['sic']
TAG: ':' ['sic']
TAG: '5' ['sic']
TAG: '.' ['sic']
TAG: 'Quia' ['sic']
TAG: 'dispensantur' ['sic']
TAG: 'granis' ['sic']
TAG: 'quae' ['sic']
TAG: 'non' ['sic']
TAG: 'licet' ['sic']
TAG: 'excedere' ['sic']
TAG: ',' ['sic']
TAG: 'quod' ['sic']
TAG: 'secus' ['sic']
TAG: 'habet' ['sic']
TAG: 'in' ['sic']
TAG: 'Galenicis' ['sic']
TAG: '.' ['sic']
TAG: '"' ['sic']
TAG: 'R.' ['sic']
TAG: 'ad' ['sic']
TAG: 'maiorem' ['sic']
TAG: '.' ['sic']
TAG: 'Homonymia' ['sic']
TAG: 'est' ['sic']
TAG: 'in' ['sic']
TAG: 'uoce' ['sic']
TAG: 'periculosa' ['sic']
TAG: '.' ['sic']
TAG: 'Uocamus' ['sic']
TAG: 'aliquando' ['sic']
TAG: 'ita' ['sic']
TAG: 'medicamen' ['sic']
TAG: 'ualidarum' ['sic']
TAG: 'uirium' ['sic']
TAG: ',' ['sic']
TAG: 'ita' ['sic']
TAG: 'ut' ['sic']
TAG: 'non' ['sic']
TAG: 'sit' ['sic']
TAG: 'committendum' ['sic']
TAG: 'quibuslibet' ['sic']
TAG: ',' ['sic']
TAG: 'atque' ['sic']
TAG: 'adeo' ['sic']
TAG: 'in' ['sic']
TAG: 'usu' ['sic']
TAG: 'malo' ['sic']
TAG: '&' ['sic']
TAG: 'imperito' ['sic']
TAG: 'sit' ['sic']
TAG: 'potius' ['sic']
TAG: 'tale' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'sua' ['sic']
TAG: 'natura' ['sic']
TAG: ';' ['sic']
TAG: 'ut' ['sic']
TAG: 'ignis' ['sic']
TAG: '&' ['sic']
TAG: 'gladius' ['sic']
TAG: 'in' ['sic']
TAG: 'manu' ['sic']
TAG: 'delitantis' ['sic']
TAG: 'non' ['sic']
TAG: 'uacant' ['sic']
TAG: 'periculo' ['sic']
TAG: ':' ['sic']
TAG: 'alioquin' ['sic']
TAG: 'sapientet' ['sic']
TAG: 'caute' ['sic']
TAG: 'que' ['sic']
TAG: 'tractata' ['sic']
TAG: 'minus' ['sic']
TAG: 'habentia' ['sic']
TAG: 'periculi' ['sic']
TAG: ',' ['sic']
TAG: 'imo' ['sic']
TAG: 'tuta' ['sic']
TAG: '&' ['sic']
TAG: 'innoxia' ['sic']
TAG: ',' ['sic']
TAG: 'potius' ['sic']
TAG: 'que' ['sic']
TAG: 'salutaria' ['sic']
TAG: 'existentia' ['sic']
TAG: '.' ['sic']
TAG: 'Si' ['sic']
TAG: 'ergo' ['sic']
TAG: 'periculosum' ['sic']
TAG: 'est' ['sic']
TAG: ',' ['sic']
TAG: 'quod' ['sic']
TAG: 'usu' ['sic']
TAG: 'imperito' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'imprudenter' ['sic']
TAG: 'adhibetur' ['sic']
TAG: ',' ['sic']
TAG: 'habens' ['sic']
TAG: 'per' ['sic']
TAG: 'se' ['sic']
TAG: 'magnam' ['sic']
TAG: 'uim' ['sic']
TAG: 'ad' ['sic']
TAG: 'agendum' ['sic']
TAG: ',' ['sic']
TAG: 'anceps' ['sic']
TAG: 'que' ['sic']
TAG: ',' ['sic']
TAG: 'tam' ['sic']
TAG: 'ad' ['sic']
TAG: 'bene' ['sic']
TAG: ',' ['sic']
TAG: 'quam' ['sic']
TAG: 'male' ['sic']
TAG: ',' ['sic']
TAG: 'momentum' ['sic']
TAG: ';' ['sic']
TAG: 'contingere' ['sic']
TAG: 'potest' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'non' ['sic']
TAG: 'sint' ['sic']
TAG: 'sine' ['sic']
TAG: 'noxa' ['sic']
TAG: '.' ['sic']
TAG: 'Sin' ['sic']
TAG: 'autem' ['sic']
TAG: 'adiacet' ['sic']
TAG: 'ei' ['sic']
TAG: 'usus' ['sic']
TAG: 'sapiens' ['sic']
TAG: ',' ['sic']
TAG: 'absque' ['sic']
TAG: 'omni' ['sic']
TAG: 'detrimento' ['sic']
TAG: 'est' ['sic']
TAG: '.' ['sic']
TAG: 'Eadem' ['sic']
TAG: 'discretione' ['sic']
TAG: 'explicanda' ['sic']
TAG: '&' ['sic']
TAG: 'minor' ['sic']
TAG: 'est' ['sic']
TAG: ',' ['sic']
TAG: 'quae' ['sic']
TAG: 'insuper' ['sic']
TAG: 'etiam' ['sic']
TAG: 'alio' ['sic']
TAG: 'Elencho' ['sic']
TAG: 'ex' ['sic']
TAG: 'particulari' ['sic']
TAG: 'laborat' ['sic']
TAG: '.' ['sic']
TAG: 'Neque' ['sic']
TAG: 'enim' ['sic']
TAG: 'omnia' ['sic']
TAG: 'chymica' ['sic']
TAG: 'sunt' ['sic']
TAG: 'huiusmodi' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'etiam' ['sic']
TAG: 'a' ['sic']
TAG: 'uulgaribus' ['sic']
TAG: 'medicastris' ['sic']
TAG: 'adhibita' ['sic']
TAG: 'simpliciter' ['sic']
TAG: 'afferant' ['sic']
TAG: 'noxam' ['sic']
TAG: ';' ['sic']
TAG: 'quanquam' ['sic']
TAG: '&' ['sic']
TAG: 'hic' ['sic']
TAG: 'abusus' ['sic']
TAG: 'tantus' ['sic']
TAG: 'possit' ['sic']
TAG: 'esse' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'aqua' ['sic']
TAG: 'rosacea' ['sic']
TAG: 'quoque' ['sic']
TAG: 'cedat' ['sic']
TAG: 'in' ['sic']
TAG: 'detrimentum' ['sic']
TAG: ':' ['sic']
TAG: 'sed' ['sic']
TAG: 'quod' ['sic']
TAG: 'commune' ['sic']
TAG: 'est' ['sic']
TAG: 'pani' ['sic']
TAG: ',' ['sic']
TAG: 'uino' ['sic']
TAG: ',' ['sic']
TAG: 'aquae' ['sic']
TAG: '&' ['sic']
TAG: 'omnibus' ['sic']
TAG: 'Galenicis' ['sic']
TAG: '.' ['sic']
TAG: 'Censor' ['sic']
TAG: 'indicabat' ['sic']
TAG: 'medicinas' ['sic']
TAG: 'debere' ['sic']
TAG: 'esse' ['sic']
TAG: 'tutissimi' ['sic']
TAG: 'usus' ['sic']
TAG: ',' ['sic']
TAG: 'ita' ['sic']
TAG: 'ut' ['sic']
TAG: 'doctis' ['sic']
TAG: 'indoctis' ['sic']
TAG: 'que' ['sic']
TAG: 'sint' ['sic']
TAG: 'sine' ['sic']
TAG: 'periculo' ['sic']
TAG: ':' ['sic']
TAG: 'quia' ['sic']
TAG: 'medicina' ['sic']
TAG: 'exerceretur' ['sic']
TAG: 'ab' ['sic']
TAG: 'utrisque' ['sic']
TAG: ':' ['sic']
TAG: 'sed' ['sic']
TAG: 'debuit' ['sic']
TAG: 'ante' ['sic']
TAG: 'hanc' ['sic']
TAG: 'censuram' ['sic']
TAG: 'bibere' ['sic']
TAG: 'elleborum' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'uidisset' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'ita' ['sic']
TAG: 'prostituendum' ['sic']
TAG: 'uulgo' ['sic']
TAG: 'esse' ['sic']
TAG: 'etiam' ['sic']
TAG: 'Hippocraticam' ['sic']
TAG: 'medicinam' ['sic']
TAG: ',' ['sic']
TAG: 'iuxta' ['sic']
TAG: 'iusiurandum' ['sic']
TAG: 'Hippocratis' ['sic']
TAG: '&' ['sic']
TAG: 'legem' ['sic']
TAG: ',' ['sic']
TAG: 'quae' ['sic']
TAG: 'iubet' ['sic']
TAG: 'res' ['sic']
TAG: 'sactas' ['sic']
TAG: 'sacris' ['sic']
TAG: 'hominibus' ['sic']
TAG: 'demonstrare' ['sic']
TAG: '.' ['sic']
TAG: 'Absterrendum' ['sic']
TAG: 'uulgus' ['sic']
TAG: 'est' ['sic']
TAG: 'difficultate' ['sic']
TAG: 'artis' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'periculo' ['sic']
TAG: 'medicamentorum' ['sic']
TAG: ',' ['sic']
TAG: 'non' ['sic']
TAG: 'alliciendum' ['sic']
TAG: 'facilitate' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'securitate' ['sic']
TAG: '.' ['sic']
TAG: 'Si' ['sic']
TAG: 'etiam' ['sic']
TAG: 'uina' ['sic']
TAG: 'non' ['sic']
TAG: 'apto' ['sic']
TAG: 'tempore' ['sic']
TAG: 'data' ['sic']
TAG: 'nocent' ['sic']
TAG: ',' ['sic']
TAG: 'magis' ['sic']
TAG: 'medicina' ['sic']
TAG: '.' ['sic']
TAG: 'Ars' ['sic']
TAG: 'non' ['sic']
TAG: 'est' ['sic']
TAG: 'cuius' ['sic']
TAG: 'tanta' ['sic']
TAG: 'est' ['sic']
TAG: 'facilitas' ['sic']
TAG: '&' ['sic']
TAG: 'securitas' ['sic']
TAG: '.' ['sic']
TAG: 'Sed' ['sic']
TAG: 'ad' ['sic']
TAG: 'prosyllogismos' ['sic']
TAG: '.' ['sic']
TAG: 'In' ['sic']
TAG: 'primo' ['sic']
TAG: 'accusatur' ['sic']
TAG: 'Antimonium' ['sic']
TAG: '&' ['sic']
TAG: 'praecipitatum' ['sic']
TAG: '.' ['sic']
TAG: 'Dicimus' ['sic']
TAG: 'ea' ['sic']
TAG: 'esse' ['sic']
TAG: 'periculosa' ['sic']
TAG: 'in' ['sic']
TAG: 'manu' ['sic']
TAG: 'stultorum' ['sic']
TAG: ',' ['sic']
TAG: '&' ['sic']
TAG: 'imprudentium' ['sic']
TAG: ':' ['sic']
TAG: 'in' ['sic']
TAG: 'artificum' ['sic']
TAG: 'circumspectione' ['sic']
TAG: 'minime' ['sic']
TAG: '.' ['sic']
TAG: 'Deinde' ['sic']
TAG: 'si' ['sic']
TAG: 'praeparationem' ['sic']
TAG: 'diuersam' ['sic']
TAG: 'spectes' ['sic']
TAG: 'aliqua' ['sic']
TAG: 'sunt' ['sic']
TAG: 'ualida' ['sic']
TAG: 'medicamenta' ['sic']
TAG: ':' ['sic']
TAG: 'aliqua' ['sic']
TAG: 'tam' ['sic']
TAG: 'blanda' ['sic']
TAG: ',' ['sic']
TAG: 'ut' ['sic']
TAG: 'ouis' ['sic']
TAG: ',' ['sic']
TAG: 'adeo' ['sic']
TAG: 'ut' ['sic']
TAG: 'etiam' ['sic']
TAG: 'pusionibus' ['sic']
TAG: 'dari' ['sic']
TAG: 'recte' ['sic']
TAG: 'queant' ['sic']
TAG: ',' ['sic']
TAG: 'imo' ['sic']
TAG: 'ne' ['sic']
TAG: 'purgent' ['sic']
TAG: 'quidem' ['sic']
TAG: ',' ['sic']
TAG: 'Galenice' ['sic']
TAG: 'per' ['sic']
TAG: 'aluum' ['sic']
TAG: ',' ['sic']
TAG: 'sed' ['sic']
TAG: 'alio' ['sic']
TAG: 'modo' ['sic']

In [120]:
doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)), {"page" : t._.pages, "texblock" : t._.textblocks, "tags": t._.tags, "blocktype" : t._.block_type}) for t in sent]) for sent in doc.sents]
sent_data_updated = []
for n_sent, sent_data in enumerate(doc_sentdata):
    sent_data_updated.append((filename[:6], n_sent, sent_data[0], sent_data[1]))

In [121]:
sent_data_updated[100:110]

[('100085',
  100,
  'Non alium liquorem uesica reddunt.',
  [('Non',
    'non',
    'PART',
    (0, 3),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('alium',
    'alius',
    'DET',
    (4, 9),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('liquorem',
    'liquor',
    'NOUN',
    (10, 18),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('uesica',
    'uesica',
    'NOUN',
    (19, 25),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('reddunt',
    'reddo',
    'VERB',
    (26, 33),
    {'page': [7], 'texblock': [23, 24], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (33, 34),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  101,
  'Non habent alia membra, quam nos, non sudores alios.',
  [('Non',
    'non',
    'PART',
    (0, 3),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('habent',
    'habeo',
    'VERB',
    (4, 10),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('alia',
    'alius',
    'DET',
    (11, 15),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('membra',
    'membrum',
    'NOUN',
    (16, 22),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (22, 23),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('quam',
    'qui',
    'PRON',
    (24, 28),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (29, 32),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (32, 33),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (34, 37),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('sudores',
    'sudor',
    'NOUN',
    (38, 45),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('alios',
    'alius',
    'DET',
    (46, 51),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (51, 52),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  102,
  'Quo rhabarbaro purgantur ipsi, eodem & nos.',
  [('Quo',
    'quo',
    'SCONJ',
    (0, 3),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('rhabarbaro',
    'rhabarbarum',
    'NOUN',
    (4, 14),
    {'page': [7], 'texblock': [24, 25], 'tags': None, 'blocktype': 'text'}),
   ('purgantur',
    'purgo',
    'VERB',
    (15, 24),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ipsi',
    'ipse',
    'DET',
    (25, 29),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (29, 30),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('eodem',
    'idem',
    'ADV',
    (31, 36),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (37, 38),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (39, 42),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (42, 43),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  103,
  'Quod ex ipsis segregatur per sennam idem ex nobis.',
  [('Quod',
    'qui',
    'PRON',
    (0, 4),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ex',
    'ex',
    'ADP',
    (5, 7),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ipsis',
    'ipse',
    'DET',
    (8, 13),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('segregatur',
    'segrego',
    'VERB',
    (14, 24),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('per',
    'per',
    'ADP',
    (25, 28),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('sennam',
    'senna',
    'NOUN',
    (29, 35),
    {'page': [7], 'texblock': [25, 26], 'tags': None, 'blocktype': 'text'}),
   ('idem',
    'idem',
    'DET',
    (36, 40),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('ex',
    'ex',
    'ADP',
    (41, 43),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('nobis',
    'nos',
    'PRON',
    (44, 49),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (49, 50),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  104,
  'Uulnerati fundunt sanguinem nostro congenerem, qui in pus mutatur eodem modo:',
  [('Uulnerati',
    'uulnerati',
    'VERB',
    (0, 9),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('fundunt',
    'fundo',
    'VERB',
    (10, 17),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('sanguinem',
    'sanguis',
    'NOUN',
    (18, 27),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('nostro',
    'noster',
    'DET',
    (28, 34),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('congenerem',
    'congenero',
    'NOUN',
    (35, 45),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (45, 46),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (47, 50),
    {'page': [7], 'texblock': [26, 27], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (51, 53),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('pus',
    'pus',
    'NOUN',
    (54, 57),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('mutatur',
    'muto',
    'VERB',
    (58, 65),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('eodem',
    'idem',
    'DET',
    (66, 71),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('modo',
    'modus',
    'NOUN',
    (72, 76),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   (':',
    ':',
    'PUNCT',
    (76, 77),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  105,
  'eadem sanantur Chirurgia.',
  [('eadem',
    'idem',
    'DET',
    (0, 5),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('sanantur',
    'sano',
    'VERB',
    (6, 14),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('Chirurgia',
    'Chirurgia',
    'PROPN',
    (15, 24),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (24, 25),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  106,
  'Et omnino qui nihil non commune secundum naturam nobiscum habent, nisi quod opinionum turba moueantur secus ac nos, indeque phantasmatibus decipiantur & linguam nouis sonis instruant, quid est secundum rei ueritatem, ut a nobis discedant primum, nisi opinio?',
  [('Et',
    'et',
    'CCONJ',
    (0, 2),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('omnino',
    'omnino',
    'ADV',
    (3, 9),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (10, 13),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('nihil',
    'nihil',
    'PRON',
    (14, 19),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (20, 23),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('commune',
    'communis',
    'ADJ',
    (24, 31),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('secundum',
    'secundum',
    'ADP',
    (32, 40),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('naturam',
    'natura',
    'NOUN',
    (41, 48),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('nobiscum',
    'nobiscus',
    'NOUN',
    (49, 57),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('habent',
    'habeo',
    'VERB',
    (58, 64),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (64, 65),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (66, 70),
    {'page': [7], 'texblock': [28, 29], 'tags': None, 'blocktype': 'text'}),
   ('quod',
    'quod',
    'SCONJ',
    (71, 75),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('opinionum',
    'opinio',
    'NOUN',
    (76, 85),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('turba',
    'turba',
    'NOUN',
    (86, 91),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('moueantur',
    'moueo',
    'VERB',
    (92, 101),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('secus',
    'secus',
    'ADV',
    (102, 107),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('ac',
    'ac',
    'CCONJ',
    (108, 110),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (111, 114),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (114, 115),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('inde',
    'inde',
    'ADV',
    (116, 120),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('que',
    'que',
    'CCONJ',
    (120, 123),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('phantasmatibus',
    'phantasma',
    'NOUN',
    (124, 138),
    {'page': [7], 'texblock': [29, 30], 'tags': None, 'blocktype': 'text'}),
   ('decipiantur',
    'decipio',
    'VERB',
    (139, 150),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (151, 152),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('linguam',
    'lingua',
    'NOUN',
    (153, 160),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('nouis',
    'nouus',
    'ADJ',
    (161, 166),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('sonis',
    'sonus',
    'NOUN',
    (167, 172),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('instruant',
    'instruo',
    'VERB',
    (173, 182),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (182, 183),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('quid',
    'quis',
    'PRON',
    (184, 188),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('est',
    'sum',
    'AUX',
    (189, 192),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('secundum',
    'secundum',
    'ADP',
    (193, 201),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('rei',
    'res',
    'NOUN',
    (202, 205),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('ueritatem',
    'ueritas',
    'NOUN',
    (206, 215),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (215, 216),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('ut',
    'ut',
    'SCONJ',
    (217, 219),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('a',
    'ab',
    'ADP',
    (220, 221),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('nobis',
    'nos',
    'PRON',
    (222, 227),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('discedant',
    'discedo',
    'VERB',
    (228, 237),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('primum',
    'primum',
    'ADV',
    (238, 244),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (244, 245),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (246, 250),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('opinio',
    'opinio',
    'NOUN',
    (251, 257),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('?',
    '?',
    'PUNCT',
    (257, 258),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  107,
  'Hos qui opinione ducuntur, & in caeteris nihil aliud faciunt aut patiuntur, an non risu, quam acerba insectatione potius dignos iudicem?',
  [('Hos',
    'hic',
    'DET',
    (0, 3),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (4, 7),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('opinione',
    'opinio',
    'NOUN',
    (8, 16),
    {'page': [7], 'texblock': [31, 32], 'tags': None, 'blocktype': 'text'}),
   ('ducuntur',
    'duco',
    'VERB',
    (17, 25),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (25, 26),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (27, 28),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (29, 31),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('caeteris',
    'caeterus',
    'ADJ',
    (32, 40),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('nihil',
    'nihil',
    'PRON',
    (41, 46),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('aliud',
    'alius',
    'DET',
    (47, 52),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('faciunt',
    'facio',
    'VERB',
    (53, 60),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('aut',
    'aut',
    'CCONJ',
    (61, 64),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('patiuntur',
    'patior',
    'VERB',
    (65, 74),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (74, 75),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('an',
    'an',
    'PART',
    (76, 78),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (79, 82),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('risu',
    'risus',
    'NOUN',
    (83, 87),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (87, 88),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('quam',
    'qui',
    'PRON',
    (89, 93),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('acerba',
    'acerbus',
    'ADJ',
    (94, 100),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('insectatione',
    'insectatio',
    'NOUN',
    (101, 113),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('potius',
    'potior',
    'ADV',
    (114, 120),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('dignos',
    'dignus',
    'ADJ',
    (121, 127),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('iudicem',
    'iudico',
    'NOUN',
    (128, 135),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('?',
    '?',
    'PUNCT',
    (135, 136),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  108,
  'Cum chymiatris autem parabolicis stultum est digladiari uelle.',
  [('Cum',
    'cum',
    'SCONJ',
    (0, 3),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('chymiatris',
    'chymiatr',
    'NOUN',
    (4, 14),
    {'page': [7], 'texblock': [33, 34], 'tags': None, 'blocktype': 'text'}),
   ('autem',
    'autem',
    'CCONJ',
    (15, 20),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('parabolicis',
    'parabolicus',
    'ADJ',
    (21, 32),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('stultum',
    'stultus',
    'ADJ',
    (33, 40),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('est',
    'sum',
    'AUX',
    (41, 44),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('digladiari',
    'digladio',
    'VERB',
    (45, 55),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('uelle',
    'uolo',
    'VERB',
    (56, 61),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (61, 62),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  109,
  'Nihil enim, proficitur, nisi quod cerebrum, rumpitur & tempus perit, Quin fiat hic idem, quod in disciplina Aristotelico ramaea.',
  [('Nihil',
    'nihil',
    'PRON',
    (0, 5),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('enim',
    'enim',
    'PART',
    (6, 10),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (10, 11),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('proficitur',
    'profico',
    'VERB',
    (12, 22),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (22, 23),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (24, 28),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('quod',
    'quod',
    'SCONJ',
    (29, 33),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('cerebrum',
    'cerebrum',
    'NOUN',
    (34, 42),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (42, 43),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('rumpitur',
    'rumpo',
    'VERB',
    (44, 52),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (53, 54),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('tempus',
    'tempus',
    'NOUN',
    (55, 61),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('perit',
    'pereo',
    'VERB',
    (62, 67),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (67, 68),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('Quin',
    'quin',
    'ADV',
    (69, 73),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('fiat',
    'fio',
    'VERB',
    (74, 78),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('hic',
    'hic',
    'DET',
    (79, 82),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   ('idem',
    'idem',
    'DET',
    (83, 87),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (87, 88),

In [122]:
sents_tags = []

for sent in sent_data_updated:
    for token in sent[3]:
        blocktype = token[4]["blocktype"]
        tag = token[4]["tags"]
        if "GR" in tag:
        #if blocktype == "margin":
            sents_tags.append(sent)
            break   # go to next sentence

TypeError: argument of type 'NoneType' is not iterable

In [113]:
len(sents_tags)

19732

In [114]:
sents_tags[:5]

[('100085',
  84,
  'Studuerum aliqua probabili specie donare, & recisis neglectisque plurimis uanis, quae χιμικωτερα essent seligere, dissentientiaque componere.',
  [('Studuerum',
    'studuerum',
    'ADJ',
    (0, 9),
    {'page': [6], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('aliqua',
    'aliquis',
    'PRON',
    (10, 16),
    {'page': [6], 'texblock': [25, 26], 'tags': None, 'blocktype': 'text'}),
   ('probabili',
    'probabilis',
    'ADJ',
    (17, 26),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('specie',
    'species',
    'NOUN',
    (27, 33),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('donare',
    'dono',
    'VERB',
    (34, 40),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (40, 41),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (42, 43),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('recisis',
    'recido',
    'VERB',
    (44, 51),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('neglectis',
    'neglego',
    'VERB',
    (52, 61),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('que',
    'que',
    'CCONJ',
    (61, 64),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('plurimis',
    'plurimus',
    'DET',
    (65, 73),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('uanis',
    'uanus',
    'NOUN',
    (74, 79),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (79, 80),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('quae',
    'qui',
    'PRON',
    (81, 85),
    {'page': [6], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('χιμικωτερα',
    '',
    'X',
    (86, 96),
    {'page': [6], 'texblock': [27], 'tags': ['GR'], 'blocktype': 'text'}),
   ('essent',
    'sum',
    'AUX',
    (97, 103),
    {'page': [6], 'texblock': [27], 'tags': ['GR'], 'blocktype': 'text'}),
   ('seligere',
    'seligo',
    'VERB',
    (104, 112),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (112, 113),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('dissentientia',
    'dissentio',
    'VERB',
    (114, 127),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('que',
    'que',
    'CCONJ',
    (127, 130),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('componere',
    'compono',
    'VERB',
    (131, 140),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (140, 141),
    {'page': [6], 'texblock': [27], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  205,
  '& non protul memoria nostra eo peruenerunt deprauationes, ut uideatur plane in alium uultum transmutata degenerasse in monstrosum quoddam μιγμα & commentum ab omni veritate alienum.',
  [('&',
    '&',
    'PUNCT',
    (0, 1),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (2, 5),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('protul',
    '',
    'VERB',
    (6, 12),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('memoria',
    'memoria',
    'NOUN',
    (13, 20),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('nostra',
    'noster',
    'DET',
    (21, 27),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('eo',
    'eo',
    'ADV',
    (28, 30),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('peruenerunt',
    'peruenio',
    'VERB',
    (31, 42),
    {'page': [11], 'texblock': [38], 'tags': None, 'blocktype': 'text'}),
   ('deprauationes',
    'deprauatio',
    'NOUN',
    (43, 56),
    {'page': [11], 'texblock': [38, 39], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (56, 57),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('ut',
    'ut',
    'SCONJ',
    (58, 60),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('uideatur',
    'uideo',
    'VERB',
    (61, 69),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('plane',
    'plane',
    'ADV',
    (70, 75),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (76, 78),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('alium',
    'alius',
    'DET',
    (79, 84),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('uultum',
    'uultus',
    'NOUN',
    (85, 91),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('transmutata',
    'transmuto',
    'VERB',
    (92, 103),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('degenerasse',
    'degenero',
    'VERB',
    (104, 115),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (116, 118),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('monstrosum',
    'monstrosum',
    'NOUN',
    (119, 129),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('quoddam',
    'quidam',
    'DET',
    (130, 137),
    {'page': [11], 'texblock': [39], 'tags': None, 'blocktype': 'text'}),
   ('μιγμα',
    'μιγμαarchia',
    'X',
    (138, 143),
    {'page': [11], 'texblock': [39, 40], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (144, 145),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'}),
   ('commentum',
    'commentum',
    'NOUN',
    (146, 155),
    {'page': [11], 'texblock': [40], 'tags': ['GR'], 'blocktype': 'text'}),
   ('ab',
    'ab',
    'ADP',
    (156, 158),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'}),
   ('omni',
    'omnis',
    'DET',
    (159, 163),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'}),
   ('veritate',
    'ueritas',
    'NOUN',
    (164, 172),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'}),
   ('alienum',
    'alienus',
    'ADJ',
    (173, 180),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (180, 181),
    {'page': [11], 'texblock': [40], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  340,
  'Ipse Riolanus cum omnia ex omnibus facit, per Elementa materiamque primam quae se transformet in omnia rerum miracula, quam longe abest a πανσπερμια illa vetere, & atomis Democriti, & multiplici vicissim oriente & pereunte?',
  [('Ipse',
    'ipse',
    'DET',
    (0, 4),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('Riolanus',
    'Riolanus',
    'PROPN',
    (5, 13),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('cum',
    'cum',
    'SCONJ',
    (14, 17),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('omnia',
    'omnis',
    'DET',
    (18, 23),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('ex',
    'ex',
    'ADP',
    (24, 26),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('omnibus',
    'omnis',
    'DET',
    (27, 34),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('facit',
    'facio',
    'VERB',
    (35, 40),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (40, 41),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('per',
    'per',
    'ADP',
    (42, 45),
    {'page': [14], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('Elementa',
    'elementum',
    'NOUN',
    (46, 54),
    {'page': [14], 'texblock': [18, 19], 'tags': None, 'blocktype': 'text'}),
   ('materiam',
    'materia',
    'NOUN',
    (55, 63),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('que',
    'que',
    'CCONJ',
    (63, 66),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('primam',
    'primus',
    'ADJ',
    (67, 73),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('quae',
    'qui',
    'PRON',
    (74, 78),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('se',
    'sui',
    'PRON',
    (79, 81),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('transformet',
    'transformo',
    'VERB',
    (82, 93),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (94, 96),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('omnia',
    'omnis',
    'DET',
    (97, 102),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('rerum',
    'res',
    'NOUN',
    (103, 108),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('miracula',
    'miraculum',
    'NOUN',
    (109, 117),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (117, 118),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('quam',
    'qui',
    'PRON',
    (119, 123),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('longe',
    'longe',
    'ADV',
    (124, 129),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('abest',
    'absum',
    'VERB',
    (130, 135),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('a',
    'ab',
    'ADP',
    (136, 137),
    {'page': [14], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('πανσπερμια',
    '',
    'X',
    (138, 148),
    {'page': [14], 'texblock': [19, 20], 'tags': None, 'blocktype': 'text'}),
   ('illa',
    'ille',
    'DET',
    (149, 153),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('vetere',
    'ueterus',
    'ADJ',
    (154, 160),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (160, 161),
    {'page': [14], 'texblock': [20], 'tags': ['GR'], 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (162, 163),
    {'page': [14], 'texblock': [20], 'tags': ['GR'], 'blocktype': 'text'}),
   ('atomis',
    'atomus',
    'NOUN',
    (164, 170),
    {'page': [14], 'texblock': [20], 'tags': ['GR'], 'blocktype': 'text'}),
   ('Democriti',
    'Democritus',
    'PROPN',
    (171, 180),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (180, 181),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (182, 183),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('multiplici',
    'multiplex',
    'ADJ',
    (184, 194),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('vicissim',
    'uicissim',
    'ADV',
    (195, 203),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('oriente',
    'oriens',
    'VERB',
    (204, 211),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (212, 213),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('pereunte',
    'pereo',
    'VERB',
    (214, 222),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'}),
   ('?',
    '?',
    'PUNCT',
    (222, 223),
    {'page': [14], 'texblock': [20], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  376,
  'Si quetis σκευασται και πυροτεηνιαν, ecce tibi eundem Bulcasim passim inseruientem.',
  [('Si',
    'si',
    'SCONJ',
    (0, 2),
    {'page': [14], 'texblock': [65], 'tags': None, 'blocktype': 'text'}),
   ('quetis',
    'quetus',
    'VERB',
    (3, 9),
    {'page': [14], 'texblock': [65], 'tags': None, 'blocktype': 'text'}),
   ('σκευασται',
    '',
    'X',
    (10, 19),
    {'page': [14], 'texblock': [65], 'tags': None, 'blocktype': 'text'}),
   ('και',
    '',
    'X',
    (20, 23),
    {'page': [14], 'texblock': [65], 'tags': None, 'blocktype': 'text'}),
   ('πυροτεηνιαν',
    'πhυροτεηνιαν',
    'X',
    (24, 35),
    {'page': [14], 'texblock': [65, 66], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (35, 36),
    {'page': [14], 'texblock': [66], 'tags': None, 'blocktype': 'text'}),
   ('ecce',
    'ecce',
    'INTJ',
    (37, 41),
    {'page': [14], 'texblock': [66], 'tags': None, 'blocktype': 'text'}),
   ('tibi',
    'tu',
    'PRON',
    (42, 46),
    {'page': [14], 'texblock': [66], 'tags': ['GR'], 'blocktype': 'text'}),
   ('eundem',
    'idem',
    'DET',
    (47, 53),
    {'page': [14], 'texblock': [66], 'tags': ['GR'], 'blocktype': 'text'}),
   ('Bulcasim',
    'Bulcasis',
    'PROPN',
    (54, 62),
    {'page': [14], 'texblock': [66], 'tags': ['GR'], 'blocktype': 'text'}),
   ('passim',
    'passim',
    'ADV',
    (63, 69),
    {'page': [14], 'texblock': [66], 'tags': ['GR'], 'blocktype': 'text'}),
   ('inseruientem',
    'inseruio',
    'VERB',
    (70, 82),
    {'page': [14], 'texblock': [66], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (82, 83),
    {'page': [14], 'texblock': [66], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  545,
  'κακοηθειαν illorum & inanem iactantiam & mores thessalicos, quibus se supra omnem antiquitatem & seculi nostri excellentiam collocant, non probo, etc.',
  [('κακοηθειαν',
    'κακοηθειανarchia',
    'X',
    (0, 10),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('illorum',
    'ille',
    'DET',
    (11, 18),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (19, 20),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('inanem',
    'inanis',
    'ADJ',
    (21, 27),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('iactantiam',
    'iactantia',
    'NOUN',
    (28, 38),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (39, 40),
    {'page': [17], 'texblock': [18], 'tags': None, 'blocktype': 'text'}),
   ('mores',
    'mos',
    'NOUN',
    (41, 46),
    {'page': [17], 'texblock': [18], 'tags': ['GR'], 'blocktype': 'text'}),
   ('thessalicos',
    'thessalicus',
    'ADJ',
    (47, 58),
    {'page': [17], 'texblock': [18, 19], 'tags': ['GR'], 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (58, 59),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('quibus',
    'qui',
    'PRON',
    (60, 66),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('se',
    'sui',
    'PRON',
    (67, 69),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('supra',
    'supra',
    'ADP',
    (70, 75),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('omnem',
    'omnis',
    'DET',
    (76, 81),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('antiquitatem',
    'antiquitas',
    'NOUN',
    (82, 94),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (95, 96),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('seculi',
    'seculum',
    'NOUN',
    (97, 103),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('nostri',
    'noster',
    'DET',
    (104, 110),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('excellentiam',
    'excellentia',
    'NOUN',
    (111, 123),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('collocant',
    'colloco',
    'VERB',
    (124, 133),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (133, 134),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (135, 138),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('probo',
    'probo',
    'VERB',
    (139, 144),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (144, 145),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('etc',
    'etcetera',
    'X',
    (146, 149),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (149, 150),
    {'page': [17], 'texblock': [19], 'tags': None, 'blocktype': 'text'})])]

In [ ]:
    target_path = "/srv/data/tome/tome-corpus/sents_data_id_jsons_v4-0/"
os.makedirs(target_path, exist_ok=True)

In [ ]:
# filename_id_dict.items()

In [ ]:
source_path = "../data/emlap_annotated_textblocks/"
len(os.listdir(source_path)) # 100 for textblocks, 100 for parameters used for their extraction

In [ ]:
os.listdir(source_path)

In [ ]:
for filename in os.listdir(source_path):
    if "_params" not in filename:
            id = filename[:6]
            try:
                if id + ".json" not in os.listdir(target_path):
                    # filename = filename.replace(".pdf", ".json")
                    filepath = os.path.join(source_path, filename)
                    with open(filepath, 'r', encoding='utf-8') as f:
                            textblocks_pages = json.load(f)
                    print("currently processing: ", filename)
                    doc = process_with_source_tracking(textblocks_pages, tomela.nlp)
                    doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)),  {"page" : t._.pages, "texblock" : t._.textblocks}) for t in sent]) for sent in doc.sents]
                    sent_data_updated = []
                    for n_sent, sent_data in enumerate(doc_sentdata):
                            sent_data_updated.append((id, n_sent, sent_data[0], sent_data[1]))
                    with open(target_path + str(id) + ".json", "w") as f:
                            json.dump(sent_data_updated, f)
            except:
                print("failed with file: ", id, filename)
                pass

In [ ]:
fns_jsons = os.listdir(target_path)
fns_jsons[:10]

In [ ]:
len(fns_jsons)

In [ ]:
sents_data = json.load(open(target_path + fns_jsons[20], "r"))
sents_data[100:103]

In [ ]:
import os, json, pickle
prev_path   = target_path  # where your old .pickle / .json live
target_path = "../data/sents_data_jsons_dicts/"
os.makedirs(target_path, exist_ok=True)

def token_tuple_to_dict(tok):
    """
    Accepts token tuples of length 4 or 5:
      4: (text, lemma, pos, (start, end))
      5: (text, lemma, pos, (start, end), ref_dict)
    Returns a JSON-serializable dict.
    """
    if len(tok) < 4:
        raise ValueError(f"Unexpected token shape: {tok}")

    token_text, lemma, pos, span = tok[0], tok[1], tok[2], tok[3]
    if not isinstance(span, (list, tuple)) or len(span) != 2:
        raise ValueError(f"Bad span in token: {tok}")

    char_start, char_end = int(span[0]), int(span[1])

    # Optional ref at index 4
    ref = tok[4] if len(tok) >= 5 else None

    # Make sure ref is JSON-friendly
    if isinstance(ref, dict):
        page = ref.get("page")
        # convert sets/tuples to lists to be JSON-serializable
        if isinstance(page, (set, tuple)):
            page = list(page)
        ref = {
            "page": page,
            "textblock": ref.get("textblock") or ref.get("texblock")  # tolerate earlier key name
        }
    elif ref is not None:
        # unexpected type → stringify to avoid JSON errors
        ref = str(ref)

    return {
        "token_text": token_text,
        "lemma": lemma,
        "pos": pos,
        "ref": ref,                  # << stays None if we don’t have it
        "char_start": char_start,
        "char_end": char_end,
    }

def sent_tuple_to_dict(entry):
    """
    entry is typically: (work_id, sent_id, sent_text, tokens_list)
    """
    if len(entry) != 4:
        raise ValueError(f"Unexpected sentence shape: {type(entry)} {entry}")

    work_id, sent_id, sent_text, tokens_list = entry
    tokens_dicts = [token_tuple_to_dict(tok) for tok in tokens_list]
    return {
        "work_id": work_id,
        "sent_id": int(sent_id),
        "sent_text": sent_text,
        "tokens_data": tokens_dicts,
    }

def load_any(path):
    """
    Load .pickle OR .json produced by your previous run.
    Must return a list of sentence entries (tuples/lists).
    """
    if path.endswith(".pickle"):
        with open(path, "rb") as f:
            return pickle.load(f)
    elif path.endswith(".json"):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    else:
        raise ValueError(f"Unsupported file type: {path}")

for fn in os.listdir(prev_path):
    if not (fn.endswith(".pickle") or fn.endswith(".json")):
        continue

    # Keep your 6-char doc id convention if you like
    doc_id = fn[:6]
    out_path = os.path.join(target_path, f"{doc_id}.json")
    if os.path.exists(out_path):
        continue

    try:
        prev_data = load_any(os.path.join(prev_path, fn))
        # If the previous version stored only (sent_text, tokens) per sentence,
        # reconstruct work_id/sent_id here as needed:
        # e.g., prev_data == [(sent_text, tokens), ...]
        if prev_data and len(prev_data[0]) == 2:
            # synthesize (work_id, sent_id, sent_text, tokens)
            prev_data = [(doc_id, i, s[0], s[1]) for i, s in enumerate(prev_data)]

        sents_dicts = [sent_tuple_to_dict(row) for row in prev_data]

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(sents_dicts, f, ensure_ascii=False, indent=2)

        print("wrote:", out_path)

    except Exception as e:
        print("failed:", fn, "-", e)

In [ ]:
lemmatized_sents_path = "/srv/data/tome/tome-corpus/lemmatized_sents_v4-0/"
try:
    os.mkdir(lemmatized_sents_path)
except:
    pass

In [ ]:
os.listdir(lemmatized_sents_path)

In [ ]:
for fn in fns_jsons:
    lemmatized_sents = []
    sents_data = json.load(open(target_path + fn, "rb"))
    print(fn)
    for (doc_id, sent_id, sent_text, sent_data) in sents_data:
        lemmasent = []
        for wordform, lemma, tag, position, t_ref in sent_data:
            if tag in ["NOUN", "PROPN", "ADJ", "VERB"]:
                lemmasent.append(lemma.lower())
        lemmatized_sents.append(" ".join(lemmasent) + "\n")
    with open(lemmatized_sents_path + fn.replace(".json", ".txt"), "w", encoding="utf-8") as f:
        f.writelines(lemmatized_sents)

In [ ]:
import shutil
shutil.copytree("/srv/data/tome/tome-corpus/lemmatized_sents_v4-0/", "../data/lemmatized_sents", dirs_exist_ok=True)
shutil.copytree("/srv/data/tome/tome-corpus/sents_data_id_jsons_v4-0/", "../data/sents_data", dirs_exist_ok=True)