About this notebook.

This notebook goes through all the texts and aplies on them a NLP pipeline consisting of (1) cleaning of the raw text, (2) sentence tokenization, (3) part-of-speech annotation, (4) lemmatization, and (5) named entity recognition.

The processed textual data are saved for future reuse.

In [1]:
import spacy
import os
import glob
from spacy.tokens import Doc
from spacy.language import Language
import pickle
from unidecode import unidecode
import sddk
import pandas as pd
import re
import sys
import importlib
import json
from spacy.tokens import Token
from spacy.language import Language
import google_conf
import pandas as pd
import json

In [2]:
import stanza
#stanza.download("grc")

/home/jupyter-vojta/notebooks/labyrinth/venv_torch_nlp/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
emlap_metadata = pd.read_csv("../data/emlap_metadata.csv", sep=";", index_col=0)
emlap_metadata.head(5)

,working_title,filenames,no.,is_done,is_noscemus,if_noscemus_id,AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,CONTENTS,genre,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,other_notes,tokens_N,aurhor_wd
0,"Augurello, Chrysopoeia",100001_Augurello1515_Chrysopoeia_GB_Noscemus,100001,True,True,713324.0,NaN,True,NaN,True,...,NaN,didactic poem,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,GB,Noscemus,NaN,23718,NaN
1,"Pseudo-Lull, Secretis",100002_Pseudo-Lull1518_De secretis_naturae_MDZ...,100002,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,"alchemy, medicine",NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,24673,NaN
2,"Pantheus, Ars Transmutatione",100003_Pantheus1518_Ars_Transmutationis_Metall...,100003,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,alchemy,NaN,https://www.google.co.uk/books/edition/Ars_Tra...,GB,BL,NaN,8646,NaN
3,"Anon, Vera alchemiae",100004_Anon1561_Verae_Alchemiae_MDZ_MBS,100004,True,False,NaN,NaN,True,NaN,True,...,NaN,"compendium, florilegium",alchemy,NaN,https://mdz-nbn-resolving.de/details:bsb10141168,MDZ,MBS,NaN,3521,NaN
4,"Pantheus, Voarchadumia",100005_Pantheus1530_Voarchadumia_ONB,100005,True,False,NaN,NaN,True,NaN,True,...,NaN,treatise,alchemy,NaN,https://data.onb.ac.at/rep/10588E49,ONB,ONB,NaN,20386,NaN

In [4]:
row = emlap_metadata.loc[emlap_metadata["no."]==100001].iloc[0]

In [5]:
row["working_title"]

'Augurello, Chrysopoeia'

In [6]:
import json
import ast
import re

def parse_messy_json(text):
    if not isinstance(text, str):
        return None

    # 1. Try strict JSON first
    try:
        return json.loads(text)
    except Exception:
        pass

    # 2. Fix common issues
    fixed = text.strip()

    # Replace single quotes with double quotes when appropriate
    fixed = fixed.replace("'", '"')

    # Remove trailing commas before ] or }
    fixed = re.sub(r",\s*([}\]])", r"\1", fixed)

    # Ensure keys are quoted (naively, but works for your case)
    fixed = re.sub(r"(?<=\{|\s)([A-Za-z_][A-Za-z0-9_]*)(?=\s*:)", r'"\1"', fixed)

    # 3. Try JSON again
    try:
        return json.loads(fixed)
    except Exception:
        pass

    # 4. Try Python literal (safer than eval)
    try:
        return ast.literal_eval(text)
    except Exception:
        pass

    # 5. Give up
    return None

In [7]:
emlap_metadata["if_compendium_parsed"] = emlap_metadata["if_compendium"].apply(parse_messy_json).tolist()

In [8]:
len(emlap_metadata)

100

In [9]:
#filename_id_dict = dict(zip(emlap_metadata["filename"], emlap_metadata["No."]))

For preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level one level up.

The module can be clonned from here: https://github.com/CCS-ZCU/latin-preprocessing and imported to python following the steps below:

In [10]:
import spacy_stanza

In [11]:
greek_nlp = spacy_stanza.load_pipeline("grc")

2025-11-26 14:10:21 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.6.0.json: 367kB [00:00, 20.7MB/s]
2025-11-26 14:10:22 INFO: Loading these models for language: grc (Ancient_Greek):
===============================
| Processor | Package         |
-------------------------------
| tokenize  | proiel          |
| pos       | proiel_nocharlm |
| lemma     | proiel_nocharlm |
| depparse  | proiel_nocharlm |
===============================

2025-11-26 14:10:22 INFO: Using device: cuda
2025-11-26 14:10:22 INFO: Loading: tokenize
2025-11-26 14:10:23 INFO: Loading: pos
2025-11-26 14:10:23 INFO: Loading: lemma
2025-11-26 14:10:23 INFO: Loading: depparse
2025-11-26 14:10:23 INFO: Done loading processors!

In [12]:
doc = greek_nlp('δοκῶ μοι περὶ ὧν πυνθάνεσθε οὐκ ἀμελέτητος εἶναι')

for token in doc:
   print(f'{token.text}, lemma: {token.lemma_}, pos: {token.pos_}, dep: {token.dep_}')

δοκῶ, lemma: δοκέω, pos: VERB, dep: root
μοι, lemma: ἐγώ, pos: PRON, dep: obl:arg
περὶ, lemma: περί, pos: ADP, dep: case
ὧν, lemma: ὅς, pos: PRON, dep: obj
πυνθάνεσθε, lemma: πυνθάνομαι, pos: VERB, dep: acl
οὐκ, lemma: οὐ, pos: ADV, dep: advmod
ἀμελέτητος, lemma: ἀμελέτης, pos: NOUN, dep: ccomp
εἶναι, lemma: εἰμί, pos: AUX, dep: cop

In [13]:
# for preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level as the current project.
current_working_directory = os.getcwd()
relative_path = '../../latin-preprocessing/' # change according to your location...
module_path = os.path.abspath(os.path.join(current_working_directory, relative_path))
if module_path not in sys.path:
    sys.path.insert(0, module_path)
# Now import the module
import tomela

Using CPU for spaCy.

In [14]:
importlib.reload(tomela)

Using CPU for spaCy.

In [15]:
tomela.nlp.pipeline

[('senter', <spacy.pipeline.senter.SentenceRecognizer at 0x78e5b0887bf0>),
 ('normer', <function la_core_web_lg.functions.normer(doc)>),
 ('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x78e5b0887cb0>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x78e5b0887fb0>),
 ('morphologizer',
  <spacy.pipeline.morphologizer.Morphologizer at 0x78e5b0887dd0>),
 ('trainable_lemmatizer',
  <spacy.pipeline.edit_tree_lemmatizer.EditTreeLemmatizer at 0x78e5b0887f50>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x78e591b8c580>),
 ('lookup_lemmatizer',
  <function la_core_web_lg.functions.make_lookup_lemmatizer_function(doc)>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x78e591b8fdf0>),
 ('remorpher', <function la_core_web_lg.functions.remorpher(doc)>)]

In [16]:
tomela.nlp.max_length = 4000000

In [17]:
doc = tomela.nlp("Veritas, vt vlla dicit, semper est universalis et a principiis fundamentalis oritur (lib. 3, cap. VI)")
for token in doc:
    print((token.text, token.lemma_, token.pos_))

('Veritas', 'ueritas', 'NOUN')
(',', ',', 'PUNCT')
('vt', 'vt', 'ADV')
('vlla', 'vllus', 'NOUN')
('dicit', 'dico', 'VERB')
(',', ',', 'PUNCT')
('semper', 'semper', 'ADV')
('est', 'sum', 'AUX')
('universalis', 'uniuersalis', 'ADJ')
('et', 'et', 'CCONJ')
('a', 'ab', 'ADP')
('principiis', 'principium', 'NOUN')
('fundamentalis', 'fundamentalis', 'ADJ')
('oritur', 'orior', 'VERB')
('(lib', '(lib', 'NOUN')
('.', '.', 'PUNCT')
('3', '3', 'NUM')
(',', ',', 'PUNCT')
('cap', 'capitulum', 'NOUN')
('.', '.', 'PUNCT')
('VI', 'uis', 'NUM')
(')', ')', 'PUNCT')

In [18]:
source_path = "/srv/data/tome/tome-corpus/EMLAP_2025-10-31/annotated_textblocks/"
len(os.listdir(source_path))

200

In [19]:
import shutil
shutil.copytree("/srv/data/tome/tome-corpus/EMLAP_2025-10-31/annotated_textblocks/", "../data/emlap_annotated_textblocks/", dirs_exist_ok=True)

'../data/emlap_annotated_textblocks/'

In [20]:
[f for f in sorted(os.listdir(source_path)) if "_params" not in f]

['100001_Augurello1515_Chrysopoeia_GB_Noscemus.json',
 '100002_Pseudo-Lull1518_De_secretis_naturae_MDZ_MBS.json',
 '100003_Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 '100004_Anon1561_Verae_Alchemiae_MDZ_MBS.json',
 '100005_Pantheus1530_Voarchadumia_ONB.json',
 '100006_Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json',
 '100007_Anon1550_Rosarium_philosophorum_ER_ZZ.json',
 '100008_Severinus1572_Epistola_MBZ_MBS.json',
 '100009_Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json',
 '100010_Bracesco1548_De_alchemia_dialogi_duo_IA_Madrid.json',
 '100011_Anon1541_De_alchemia_MDZ_MBS.json',
 '100012_Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json',
 '100013_Ulstad1525_Coelum_philosophorum_Medica_BIUSP.json',
 '100014_Toxites1567_Spongia_stibii_MDZ_MBS.json',
 '100015_Gessner1569_Thesaurus_Euonymi_Philiatri_liber_secundus_MDZ_MBS.json',
 '100016_Bonus1546_Pretiosa_Margarita_Novella_ONB.json',
 '100017_Bodenstein1559_Isagoge_MDZ_MBS.json',
 '100018_Trevisanus1567_Peri_chemeias_MDZ_MBS.json',
 '100019_Ulstadt1526_De_epidemia_ONB.json',
 '100020_Dorn1569_Artificii_chymistici_MDZ_MBS.json',
 '100021_Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB.json',
 '100022_Anon1550_De_alchemia_opuscula_MDZ_MBS.json',
 '100023_Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS.json',
 '100024_Fanianus1560_De_arte_metallicae_ONB.json',
 '100025_Pseudo-Lull1563_Codicillus_MDZ_MBS.json',
 '100026_Garlandius1560_Compendium_Alchemiae_VD16_SLUB.json',
 '100027_Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 '100028_Pedemontanus1563_De_secretis_MDZ_MBS.json',
 '100029_Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json',
 '100030_Rupescissa1561_De_consideratione_quintae_essentie_rerum_GB.json',
 '100031_Phaedro1562_Aquila_coelestis_MBZ_MBS.json',
 '100032_Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json',
 '100033_Pseudo-Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json',
 '100034_Penotus1594_Tractatus_varii_MDZ_MBS.json',
 '100035_Dorn1570_Lapis_metaphysicus_MDZ_MBS.json',
 '100036_Vadis1595_Dialogus_IA_Wellcome.json',
 '100037_DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
 '100038_Anon1571_Auriferae_artis_MBZ_Augsburg.json',
 '100039_Pseudo-Democritus1572_Ars_magna_MDZ_MBS.json',
 '100040_Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 '100041_Senior1560_De_chemia_senioris_MDZ_MBS.json',
 '100042_Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json',
 '100043_DuChesne1575_Sclopetarius_MDZ_Augsburg.json',
 '100044_Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json',
 '100045_Dorn1583_De_naturae_luce_physica_MDZ_MBS.json',
 '100046_Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json',
 '100047_Portaleone1584_De_auro_dialogi_tres_ONB.json',
 '100048_Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 '100049_Rossi1585_De_destillatione_MDZ_MBS.json',
 '100050_Anon1599_Quadriga_aurifera_IA_Madrid.json',
 '100051_Ruland1564_Medicina_practica_recens_MDZ_MDS.json',
 '100052_Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json',
 '100053_Mirandola1586_De_auro_libri_tres_MDZ_MBS.json',
 '100054_Moffett1584_De_iure_et_praestantia_MDZ_MBS.json',
 '100055_Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json',
 '100056_Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json',
 '100057_Hagecius1585_De_cerevisia_GB_ONB.json',
 '100058_Hagecius1596_Actio_medica_ER_UBB.json',
 '100059_Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json',
 '100060_Witestein1583_Disceptatio_philosophica_MDZ_MBS.json',
 '100061_Moffett1588_Nosomantica_Hippocrates_ONB.json',
 '100062_Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.json',
 '100063_Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.json',
 '100064_Trevisanus1583_De_chymico_miraculo_MDZ_MBS.json',
 '100065_Libavius1594_Neoparacelsica_MDZ_MBS.json',
 '100066_Suchten1575_De_secretis_antimonii_ONB.json',
 '100067_Wecker1582_De_secretis_ONB.json',
 '100068_Pseudo-Paracelsus1577_Aurora_thesaurusque_philosophorum_ONB.json',
 '100069_Severinus1571_Idea_medicinae_philosophicae_GB_Noscemus.json',
 '100070_Libavius1597_Alchemia_ER_Noscemus.json',
 '100071_Pseudo-Lull1566_Testamentum_MDZ_MBS.json',
 '100072_Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.json',
 '100073_Greverus1599_Secretum_MDZ_MBS.json',
 '100074_Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.json',
 '100075_Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.json',
 '100076_Du_Chesne1604_Ad_Veritatem_Hermeticae_Medicinae_MDZ_MBS.json',
 '100077_Cephalus1601_Apotelesmatum_philosophicum_HT.json',
 '100078_Harvet1605_Demonstratio_veritatis_VD17_FAU.json',
 '100079_Eglinus1608_Disquisitio_de_Helia_Artium_MDZ_MBS.json',
 '100080_Anon1611_Tratatus_de_secretissimo_MDZ_MBS.json',
 '100081_Sendivogius1614_Novum_lumen_chymicum_VD17_SLUB.json',
 '100082_Hermes_Trismegistus1610_Tractatus_vere_aureus_VD17_SLUB.json',
 '100083_Sendivogius1616_Tractatus_de_sulphure_MBS_MDZ.json',
 '100084_Croll1609_Basilica_chymica_MDZ_MBS.json',
 '100085_Libavius1606_Commentariorum_alchemiae_pars_1_MDZ_MBS.json',
 '100086_Penotus1608_Denario_medico_MDZ_MBS.json',
 '100087_Beguin1612_Tyrocinium_chymicum_GB_Noscemus.json',
 '100088_Dienheim1610_Medicina_universalis_ONB.json',
 '100089_BasiliusValentinus1613_Azoth_VD17_SLUB.json',
 '100090_Nolle1617_Theoria_philosophiae_Hermeticae_MDZ_MBS.json',
 '100091_Ruland1607_Progymnasmata_alchemiae_MDZ_MBS.json',
 '100092_Drebbel1621_Tractatus_duo_VD17_Halle.json',
 '100093_Sala1622_Chrysologia_MBZ_MBS.json',
 '100094_Anon1625_Musaeum_hermeticum_VD17_SLUB.json',
 '100095_Fabre1632_Alchymista_christianus_ONB.json',
 '100096_Agricola1631_Galerazeya_GB_BL.json',
 '100097_Van_Helmont1644_Opuscula_medica_MDZ_MBS.json',
 '100098_Burggravius1630_Biolychnium_VD17_SLUB.json',
 '100099_Francus1607_De_Arte_Chemica_VD17_Halle.json',
 '100100_Van_Helmont1648_Ortus_medicinae_MDZ_MBS.json']

In [21]:
row = emlap_metadata.loc[emlap_metadata["no."]==int("100001")].iloc[0]
row

working_title                                                                                 Augurello, Chrysopoeia
filenames                                                               100001_Augurello1515_Chrysopoeia_GB_Noscemus
no.                                                                                                           100001
is_done                                                                                                         True
is_noscemus                                                                                                     True
if_noscemus_id                                                                                              713324.0
AUTHORSHIP                                                                                                       NaN
is_one_author                                                                                                   True
#if more than 1 author skip section and choose compendium below                                                  NaN
is_author_known                                                                                                 True
author_name                                                                              Augurelli, Giovanni Aurelio
author_name_alternatives                                                                                  Augurellus
author_viaf                                                                                                 88062391
author_cerl                                                                                              cnp01876437
author_comments                                                                                                  NaN
is_compendium                                                                                                  False
if_compendium                                                                                                    NaN
TRANSLATION / EDITORSHIP                                                                                         NaN
is_translator                                                                                                  False
translator_name                                                                                                  NaN
translator_name_alternatives                                                                                     NaN
translator_comments                                                                                              NaN
is_editor                                                                                                      False
editor_name                                                                                                      NaN
editor_name_alternatives                                                                                         NaN
editor_comments                                                                                                  NaN
DATE OF PUBLICATION                                                                                              NaN
date_publication                                                                                                1515
date_certainty                                                                                                  True
date_not_after                                                                                                   NaN
date_not_before                                                                                                  NaN
date_comment                                                                                                     NaN
TITLE                                                                                                            NaN
title_short                                                                                              Chrysopoeia
title_full                                                         Ioannis Aurelii Augurelli P. Ariminensis Chrys...
title_viaf                                                                                               178020328.0
title_comments                                                                                                   NaN
PLACE OF PUBLICATION                                                                                             NaN
place_publication                                                                                             Venice
place_geonames                                                                                               3164603
place_comments                                                                                                   NaN
PUBLISHER                                                                                                        NaN
publisher_name                                                                                             Da Rovere
publisher_name_alternatives                                                                                      NaN
publisher_comments                                                                                               NaN
CONTENTS                                                                                                         NaN
genre                                                                                                  didactic poem
subject                                                                                                      alchemy
SOURCE OF FILE                                                                                                   NaN
link                                                                    https://wiki.uibk.ac.at/noscemus/Chrysopoeia
source_of_file                                                                                                    GB
origin_of_copy                                                                                              Noscemus
other_notes                                                                                                      NaN
tokens_N                                                                                                       23718
aurhor_wd                                                                                                        NaN
if_compendium_parsed                                                                                            None
Name: 0, dtype: object

In [22]:
files_overview = []
for filename in os.listdir(source_path):
    #filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
    id = int(filename[:6])
    row = emlap_metadata.loc[emlap_metadata["no."]==id].iloc[0]
    if "_params" not in filename:
        filepath = os.path.join(source_path, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            textblocks = json.load(f)
        pages_n = len(textblocks)
        chars_n = sum([sum([len(tb["text"]) for tb in p]) for p in textblocks])
        files_overview.append({"filename" : filename, "pages_n" : pages_n, "chars_n" : chars_n})
files_processed = pd.DataFrame(files_overview)
files_processed

                                             filename  pages_n  chars_n
0      100084_Croll1609_Basilica_chymica_MDZ_MBS.json      477   694793
1   100094_Anon1625_Musaeum_hermeticum_VD17_SLUB.json      508   694493
2        100058_Hagecius1596_Actio_medica_ER_UBB.json       89   104677
3   100013_Ulstad1525_Coelum_philosophorum_Medica_...      113   237793
4   100069_Severinus1571_Idea_medicinae_philosophi...      463   600046
..                                                ...      ...      ...
95  100056_Claveus1598_Apologia_crysopoeiae_MDZ_MB...      233   233328
96    100065_Libavius1594_Neoparacelsica_MDZ_MBS.json      821  1079977
97   100031_Phaedro1562_Aquila_coelestis_MBZ_MBS.json       55    15562
98  100098_Burggravius1630_Biolychnium_VD17_SLUB.json      167   186267
99  100042_Pseudo-Paracelsus1568_De_summis_naturae...      177   179729

[100 rows x 3 columns]

In [23]:
#emlap_catalogue = google_conf.setup(sheet_url="https://docs.google.com/spreadsheets/d/1bkHHTYc86K2IuEXqfYfkDNt5LovtvCU3gvqHIbVio88/edit?usp=sharing", service_account_path="../../../ServiceAccountsKey.json")

# google_conf.set_with_dataframe(emlap_catalogue.add_worksheet("files_processed", 1,1), files_processed, include_index=False)


Develop and test with one example test

In [64]:
filename = '100085_Libavius1606_Commentariorum_alchemiae_pars_1_MDZ_MBS.json'
filepath = os.path.join(source_path, filename)
with open(filepath, 'r', encoding='utf-8') as f:
    textblocks = json.load(f)

In [65]:
textblocks_unheadered = []
for p in textblocks:
    p_unheadered = []
    header_met = False
    for textblock in p:
        if textblock["tag"] == "header":
            if header_met:
                textblock["tag"] = "text"
            else:
                header_met = True
        p_unheadered.append(textblock)
    textblocks_unheadered.append(p_unheadered)

textblocks = textblocks_unheadered#%%
len(textblocks)

413

In [66]:
textblocks[30][:10]

[{'coordinates': [211.67999267578125,
   1086.2401123046875,
   361.0691833496094,
   1091.0400390625],
  'text': '6. Aeneid.\n',
  'tag': 'margin'},
 {'coordinates': [405.6000061035156,
   200.16000366210938,
   1988.2835693359375,
   217.34410095214844],
  'text': '20\nExamen sententiae Parisiensis scholae\n',
  'tag': 'header'},
 {'coordinates': [573.3599853515625,
   284.6640930175781,
   2086.989501953125,
   289.5841064453125],
  'text': '"Si in mundo sublunari nulla est substantia ab elementaribus quatuor distincta, nulla est quinta essen¬\n',
  'tag': 'text'},
 {'coordinates': [672.47998046875,
   334.7998962402344,
   1029.914794921875,
   339.5998840332031],
  'text': 'tia, quae extrahi possit.\n',
  'tag': 'text'},
 {'coordinates': [573.3599853515625,
   384.9600524902344,
   1760.6229248046875,
   389.7600402832031],
  'text': 'Prius est. Posterius ergo: & per consequens, ignis & opera perditur extrahendo,"\n',
  'tag': 'text'},
 {'coordinates': [504.9599914550781,
   433.6800231933594,
   2177.0302734375,
   438.4800109863281],
  'text': 'Minor negatur, cumque hic eam non probet Censor, vt vana relinquitur. Interim vt studiosis\n',
  'tag': 'text'},
 {'coordinates': [408.0,
   484.5599060058594,
   2182.865478515625,
   489.3598937988281],
  'text': 'contrarium constet, primum opponimus Censori imperitissimo rerum naturalium, tantum Logicis\n',
  'tag': 'text'},
 {'coordinates': [408.0,
   534.0000610351562,
   2179.46728515625,
   538.8001098632812],
  'text': '& Metaphysicis argutiis innutrito ludicium Philosophorum grauissimorum, qui ex actione & passio¬\n',
  'tag': 'text'},
 {'coordinates': [405.6000061035156,
   584.8799438476562,
   2182.76025390625,
   589.6799926757812],
  'text': 'ne inferiorum & superiorum colligunt materiarum seu substantiarum consensum quendam genericum,\n',
  'tag': 'text'},
 {'coordinates': [410.1600036621094,
   632.1599731445312,
   2186.11572265625,
   636.9600219726562],
  'text': 'hoc est, materialem & subiecto tenus. Cum enim omnis virtus inferiorum, teste Aristotele, à superio¬\n',
  'tag': 'text'}]

In [67]:
margin_pages = []
for p in textblocks[:50]:
    for textblock in p:
        if textblock["tag"] == "margin":
            margin_pages.append(p)
            break

In [68]:
len(margin_pages)

35

In [69]:
margin_pages[0]

[{'coordinates': [235.44000244140625,
   684.7200317382812,
   409.4384460449219,
   689.5200805664062],
  'text': 'In specie tot\n',
  'tag': 'margin'},
 {'coordinates': [235.44000244140625,
   725.0398559570312,
   410.12158203125,
   729.8399047851562],
  'text': 'medicorum\n',
  'tag': 'margin'},
 {'coordinates': [235.44000244140625,
   765.8640747070312,
   409.9117736816406,
   770.7840576171875],
  'text': 'hodie sectae,\n',
  'tag': 'margin'},
 {'coordinates': [240.24000549316406,
   806.3999633789062,
   399.8396301269531,
   811.2000122070312],
  'text': 'vt videan¬\n',
  'tag': 'margin'},
 {'coordinates': [237.83999633789062,
   846.2639770507812,
   409.64459228515625,
   851.1839599609375],
  'text': 'tur innume¬\n',
  'tag': 'margin'},
 {'coordinates': [237.83999633789062,
   885.8640747070312,
   410.22802734375,
   890.7840576171875],
  'text': 'rabila, gene¬\n',
  'tag': 'margin'},
 {'coordinates': [237.83999633789062,
   929.0398559570312,
   394.5736389160156,
   933.8399047851562],
  'text': 're ad tres\n',
  'tag': 'margin'},
 {'coordinates': [240.24000549316406,
   969.8399047851562,
   409.71844482421875,
   974.6399536132812],
  'text': 'classes reduci\n',
  'tag': 'margin'},
 {'coordinates': [235.44000244140625,
   1013.5200805664062,
   369.552001953125,
   1018.3201293945312],
  'text': 'possunt.\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   1045.4400634765625,
   409.9608154296875,
   1050.239990234375],
  'text': 'Galenici in¬\n',
  'tag': 'margin'},
 {'coordinates': [240.24000549316406,
   1094.4000244140625,
   343.356201171875,
   1099.199951171875],
  'text': 'genui.\n',
  'tag': 'margin'},
 {'coordinates': [245.27999877929688,
   1392.02392578125,
   410.1197204589844,
   1396.9439697265625],
  'text': 'Chymiatri\n',
  'tag': 'margin'},
 {'coordinates': [247.67999267578125,
   1429.6800537109375,
   410.7650451660156,
   1434.47998046875],
  'text': 'vulgares seu\n',
  'tag': 'margin'},
 {'coordinates': [237.83999633789062,
   1477.9200439453125,
   390.0096435546875,
   1482.719970703125],
  'text': 'simplices.\n',
  'tag': 'margin'},
 {'coordinates': [250.0800018310547,
   2001.5999755859375,
   409.78240966796875,
   2006.39990234375],
  'text': 'Chymiatri\n',
  'tag': 'margin'},
 {'coordinates': [245.27999877929688,
   2045.2801513671875,
   404.2020263671875,
   2050.080078125],
  'text': 'hermetici.\n',
  'tag': 'margin'},
 {'coordinates': [250.0800018310547,
   2377.199951171875,
   408.7648010253906,
   2382.0],
  'text': 'Chymiatri.\n',
  'tag': 'margin'},
 {'coordinates': [247.67999267578125,
   2419.43994140625,
   395.3243713378906,
   2424.239990234375],
  'text': 'sophistici,\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   2458.079833984375,
   409.3320617675781,
   2462.8798828125],
  'text': 'non parum\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   2499.119873046875,
   411.25274658203125,
   2503.919921875],
  'text': 'paracelsici,\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   2539.4638671875,
   409.72705078125,
   2544.3837890625],
  'text': 'licet hoc no¬\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   2579.519775390625,
   409.93597412109375,
   2584.31982421875],
  'text': 'men auer¬\n',
  'tag': 'margin'},
 {'coordinates': [245.27999877929688,
   2620.800048828125,
   354.4461669921875,
   2625.60009765625],
  'text': 'sentur.\n',
  'tag': 'margin'},
 {'coordinates': [250.0800018310547,
   2661.599853515625,
   411.2279968261719,
   2666.39990234375],
  'text': 'Talis fuit\n',
  'tag': 'margin'},
 {'coordinates': [250.0800018310547,
   2703.6240234375,
   409.8185119628906,
   2708.5439453125],
  'text': 'Assyluanus.\n',
  'tag': 'margin'},
 {'coordinates': [245.27999877929688,
   2857.199951171875,
   410.5152282714844,
   2862.0],
  'text': 'Paracelsici.\n',
  'tag': 'margin'},
 {'coordinates': [240.24000549316406,
   3234.719970703125,
   405.763427734375,
   3239.52001953125],
  'text': 'Hemipara¬\n',
  'tag': 'margin'},
 {'coordinates': [242.8800048828125,
   3275.760009765625,
   348.81805419921875,
   3280.56005859375],
  'text': 'celsici.\n',
  'tag': 'margin'},
 {'coordinates': [752.6400146484375,
   171.59994506835938,
   1860.423095703125,
   176.3999481201172],
  'text': 'EPISTOLA DEDICATORIA.\n',
  'tag': 'header'},
 {'coordinates': [420.0,
   255.35995483398438,
   2208.9599609375,
   260.1599426269531],
  'text': 'test ex sequentibus intelligi. Triplex hodiè est medicinae docendae, facien¬\n',
  'tag': 'text'},
 {'coordinates': [424.79998779296875,
   334.7998962402344,
   2193.759765625,
   339.5998840332031],
  'text': 'daeque & ratio & familia. Primam appellant sectam dogmaticorum &\n',
  'tag': 'text'},
 {'coordinates': [420.0,
   408.9839172363281,
   2192.752685546875,
   413.9039306640625],
  'text': 'rationalium, cuius professores ab Hippocrate & Galeno Hippocratici &\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   490.5599060058594,
   2202.1669921875,
   495.3598937988281],
  'text': 'Galenici nuncupantur, quia potissmum, istorum, instituta sequuntur.\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   570.0000610351562,
   2196.081298828125,
   574.8001098632812],
  'text': 'Quidam adijciunt & Arabum doctrinam, quanquam non omnem, &\n',
  'tag': 'text'},
 {'coordinates': [432.0,
   641.5440063476562,
   2211.814208984375,
   646.4639892578125],
  'text': 'sic in diuersas factiones etiam alias hoc genus diuiditur, ex quibus quaedam\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   720.4800415039062,
   2209.98095703125,
   725.2800903320312],
  'text': 'etiam Galeni placitis non omnino acquiescunt. Sed hoc palam est. Iuxta\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   796.0798950195312,
   2222.36669921875,
   800.8799438476562],
  'text': 'praesentem considerationem, Galenici sunt duplices: Quidam seruiles, qui\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   875.0640258789062,
   2205.964599609375,
   879.9840087890625],
  'text': 'nihil ne latum quidem vnguem à dogmatibus Galeni sibi discedendum\n',
  'tag': 'text'},
 {'coordinates': [439.44000244140625,
   951.8399047851562,
   2202.39013671875,
   956.6399536132812],
  'text': 'putant. Quidam nullius adicti iurare in verba magistri, liberalem,\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   1031.06396484375,
   2210.219970703125,
   1035.9840087890625],
  'text': 'amplectuntur disciplinam, & ingenuè in medicina versantur, ausi vel\n',
  'tag': 'text'},
 {'coordinates': [424.79998779296875,
   1106.6400146484375,
   2206.9443359375,
   1111.43994140625],
  'text': 'ipsum Galenum reprehendere & Hippocratem sicubi à vero discedunt.\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   1181.2801513671875,
   2210.017822265625,
   1186.080078125],
  'text': 'Manent tamen intra veterum praeceptorum scholae Galenicae septa, ean¬\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   1258.5599365234375,
   2212.02001953125,
   1263.35986328125],
  'text': 'demque medendi tenent consuetudinem. Quidam nomen & famam\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1333.2000732421875,
   2217.2958984375,
   1338.0],
  'text': 'Logempiriae aucupantur, cum priores dogmatici vel rationales solum¬\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   1417.4400634765625,
   2208.65234375,
   1422.239990234375],
  'text': 'modo audire velint. Secundum medicorum genus est CHVMIATRO¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 1490.6640625, 2198.62841796875, 1495.5841064453125],
  'text': 'RUM, qui veterum methodo adiecerunt pharmaceuticen chymicam, &\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1565.2801513671875,
   2205.05126953125,
   1570.080078125],
  'text': 'non tantum vulgariter praeparatis vtuntur medicamentis verum et¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 1642.583984375, 2213.14990234375, 1647.5040283203125],
  'text': 'iam ex Alchymia petitis. In hac classe excellunt prisci illi Arabes & Sa¬\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1717.9200439453125,
   2213.10595703125,
   1722.719970703125],
  'text': 'raceni, Auicenna, Mesue, Rhases, Bulcasis, & alij, quos secuti sunt re¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1798.7999267578125,
   2210.601806640625,
   1803.599853515625],
  'text': 'centium plurimi, Albertus, Arnoldus, Lullius, Vlstadius, & omnino\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1873.703857421875,
   2211.7900390625,
   1878.6239013671875],
  'text': 'innumerabiles: Ex quibus aliqui simpliciter & vulgari consuetoque Ga¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1950.0,
   2209.206787109375,
   1954.7999267578125],
  'text': 'lenicis sermone disserunt de medicinae regulis, in chymicis saltem chy¬\n',
  'tag': 'text'},
 {'coordinates': [437.0400085449219,
   2027.52001953125,
   2218.730712890625,
   2032.3199462890625],
  'text': 'mica proferentes: Nonnulli ad dogmata prisca accommodant discipli¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2104.079833984375,
   2208.762451171875,
   2108.8798828125],
  'text': 'nam chymicam, & quod Galenici vulgares suae scholae verbis enunci¬\n',
  'tag': 'text'},
 {'coordinates': [432.0,
   2183.760009765625,
   2214.954833984375,
   2188.56005859375],
  'text': 'ant, id hi chymicè vel macrocosmicè expediunt, vtrobique tamen eodem\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2261.06396484375,
   2207.695068359375,
   2265.98388671875],
  'text': 'circa catholica praecepta necessariamque scientiam, & praxin sensu.\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   2337.840087890625,
   2214.621826171875,
   2342.64013671875],
  'text': 'Hi parabolici & Hermetici dici consueuerunt, aut genuine chymiatri.\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2415.119873046875,
   2220.51904296875,
   2419.919921875],
  'text': 'Sed sunt & alij sophistici, qui, cùm aliqua consentiant cum veterum\n',
  'tag': 'text'},
 {'coordinates': [437.0400085449219,
   2493.840087890625,
   2209.309326171875,
   2498.64013671875],
  'text': 'Hippocratica schola, multa immiscent praua, & sophisticis opinionibus,\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2567.5439453125, 2204.443603515625, 2572.4638671875],
  'text': 'chymicorum more enuntiatis, multas excitant turbas, nec patiuntur cae¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2645.999755859375,
   2223.29638671875,
   2650.7998046875],
  'text': 'teros prae se quid sapere, siue verba spectes siue sententias, siue facta, quae\n',
  'tag': 'text'},
 {'coordinates': [444.239990234375,
   2723.999755859375,
   2208.225341796875,
   2728.7998046875],
  'text': 'praedicant ingentia. Hostes hi sunt Galenicorum, potissimum eorum,\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2799.119873046875, 1967.80810546875, 2803.919921875],
  'text': 'qui rigidius & pertinacius adhaerent magistri Galeni dictatis.\n',
  'tag': 'text'},
 {'coordinates': [563.280029296875,
   2878.079833984375,
   2214.97705078125,
   2882.8798828125],
  'text': 'Tertia factio est PARACELSISTARVM ab autore Paracelso, quon¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2953.919921875, 2212.4072265625, 2958.719970703125],
  'text': 'dam Galenicae & Arabum disciplinae addicto, chymicoque non indocto\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   3030.719970703125,
   2208.04736328125,
   3035.52001953125],
  'text': 'nec imperito, sed qui propriantandem sectam condidit coaceruatis ex omni¬\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3107.280029296875,
   2206.38671875,
   3112.080078125],
  'text': 'paradoxorum absurdorumque & deliramentorum angulo portentis, quae\n',
  'tag': 'text'},
 {'coordinates': [424.79998779296875,
   3183.864013671875,
   2214.892822265625,
   3188.783935546875],
  'text': 'fucato quodam colore inducta studuit verisimilia reddere. Statim hoc\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   3259.679931640625,
   2208.2880859375,
   3264.47998046875],
  'text': 'genus in duos diuulsum est greges. Nam cum nouitas quidem arrideret\n',
  'tag': 'text'},
 {'coordinates': [473.2799987792969,
   3337.919921875,
   2205.98486328125,
   3342.719970703125],
  'text': '& in insolitas quasdam spes, consiliaque plurium excitaret pelliceretque\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3416.8798828125,
   2204.18701171875,
   3421.679931640625],
  'text': 'animos; tamen magian impiam, & affinia deliramenta pauci sunt\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3492.0,
   660.1680908203125,
   3496.800048828125],
  'text': 'amplexi.\n',
  'tag': 'text'},
 {'coordinates': [1990.56005859375,
   3578.159912109375,
   2198.117919921875,
   3582.9599609375],
  'text': 'Nullus\n',
  'tag': 'footer'}]

In [70]:
margin_pages[1]

[{'coordinates': [526.0800170898438,
   172.10403442382812,
   1639.3897705078125,
   177.02403259277344],
  'text': 'EPISTOLA DEDICATORIA.\n',
  'tag': 'header'},
 {'coordinates': [337.9200134277344,
   262.1040344238281,
   1993.8466796875,
   267.0240478515625],
  'text': 'Nullus quidem Paracelsita quicquam sibi commune cum schola\n',
  'tag': 'text'},
 {'coordinates': [194.63999938964844,
   338.9038391113281,
   1991.999755859375,
   343.8238525390625],
  'text': 'Galenica esse prae se videtur ferre: aliqui tamen Hippocrati sunt aequio¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   417.8399353027344,
   1995.948486328125,
   422.6399230957031],
  'text': 'res: Hic reijcit Chrysopoeian, ille magian, adiurationes, execrationes ec.\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   495.3838195800781,
   1972.9329833984375,
   500.3038330078125],
  'text': 'Puri puti Paracelsici omnia atque etiam sputa sui Monarchae exosculan¬\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   574.0798950195312,
   1998.3780517578125,
   578.8799438476562],
  'text': 'tur, quod in omnibus putent aliquid diuini latitare & mysteria mera¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   643.4400024414062,
   441.10601806640625,
   648.2400512695312],
  'text': 'crepant.\n',
  'tag': 'text'},
 {'coordinates': [304.55999755859375,
   727.9439086914062,
   1988.58447265625,
   732.8638916015625],
  'text': 'Aristotelem, Platonem, Galenum & caeteros philosophiae vulgatae\n',
  'tag': 'text'},
 {'coordinates': [179.0399932861328,
   804.9597778320312,
   1985.39404296875,
   809.7598266601562],
  'text': 'antistites verbis & gestibus quanquam interim multa suffurentur, ex¬\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   878.3999633789062,
   445.9079895019531,
   883.2000122070312],
  'text': 'plodunt.\n',
  'tag': 'text'},
 {'coordinates': [335.760009765625,
   959.5440063476562,
   1989.110595703125,
   964.4639892578125],
  'text': 'Profitentur autem Philosophiam aliam, quam Paracelsus ap¬\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   1034.6400146484375,
   1991.2000732421875,
   1039.43994140625],
  'text': 'pellauit sagacem, quae complectitur magian, non illam naturalem\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1114.7999267578125,
   1989.8240966796875,
   1119.599853515625],
  'text': 'ex philosophia legitima, sed quàm autor paracelsus ita describit, vt pri¬\n',
  'tag': 'text'},
 {'coordinates': [174.72000122070312,
   1192.0799560546875,
   1982.0372314453125,
   1196.8798828125],
  'text': 'mo statim vultu damnatam agnoscas: Item Nigromantiam, Necro¬\n',
  'tag': 'text'},
 {'coordinates': [179.0399932861328,
   1270.0799560546875,
   1983.9996337890625,
   1274.8798828125],
  'text': 'mantiam, Astrologiam vanam, signatum, artes incertas, Geomantiam,\n',
  'tag': 'text'},
 {'coordinates': [188.16000366210938,
   1345.94384765625,
   1973.4652099609375,
   1350.8638916015625],
  'text': 'Pyromantiam etc. Praeterea medicinam adeptam mathematicam ade¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1422.9598388671875,
   1989.2001953125,
   1427.759765625],
  'text': 'ptam & alias, in quibus tum sordes & purgamenta quisquiliaeque magiae\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1500.02392578125,
   1984.3125,
   1504.9439697265625],
  'text': 'Zoroastris, Platonicorum, & similium gentilitiarum superstitionum,\n',
  'tag': 'text'},
 {'coordinates': [179.0399932861328,
   1576.7999267578125,
   1973.6326904296875,
   1581.599853515625],
  'text': 'tum sagarum, magorumque sathanicorum. In hac Philosophia est ars\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1652.6400146484375,
   1972.089111328125,
   1657.43994140625],
  'text': 'Diabolos seu spiritus euocandi, consulendique per Berillos, vnde Berillisti¬\n',
  'tag': 'text'},
 {'coordinates': [174.72000122070312,
   1729.703857421875,
   1978.190673828125,
   1734.6239013671875],
  'text': 'ca, & specula, vnde visio specularis, Thesauros fodiendi, quae Thesauri¬\n',
  'tag': 'text'},
 {'coordinates': [183.60000610351562,
   1806.7198486328125,
   1965.4879150390625,
   1811.519775390625],
  'text': 'nella, pestem per menstruatos pannos, procurandi, & venenandi, mor¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1885.4400634765625,
   1974.8330078125,
   1890.239990234375],
  'text': 'bos inferendi, fascinandi per imaginationes, excantandi, per homuncu¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   1964.8800048828125,
   1981.0599365234375,
   1969.679931640625],
  'text': 'los cruciandi, occulta per spirituum commercia expiscandi, per annulos.\n',
  'tag': 'text'},
 {'coordinates': [192.47999572753906,
   2041.679931640625,
   1990.1934814453125,
   2046.4798583984375],
  'text': 'statuas, Gemmahuias, characteres, verba concepta & alia, monstrosa\n',
  'tag': 'text'},
 {'coordinates': [174.72000122070312,
   2117.519775390625,
   1991.2901611328125,
   2122.31982421875],
  'text': 'nec nisi damnatis magis vsitata. In hac traditur ratio eliciendorum\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   2195.039794921875,
   1994.34716796875,
   2199.83984375],
  'text': 'fulminum & perdendarum messium. In hac mulierculae illae domoniacae\n',
  'tag': 'text'},
 {'coordinates': [179.0399932861328,
   2272.10400390625,
   1993.4456787109375,
   2277.02392578125],
  'text': 'comburuntur, sed magi execrandissimi absoluuntur. In hac quicquid\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   2351.039794921875,
   1986.0479736328125,
   2355.83984375],
  'text': 'Apuleius de aureo suo asinò ex homine per incantamenta transformato,\n',
  'tag': 'text'},
 {'coordinates': [205.9199981689453,
   2425.679931640625,
   1991.40478515625,
   2430.47998046875],
  'text': '& Circe de porcis Vlyssis habet, quicquid in occulta philosophia Cornelius\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   2502.02392578125,
   1978.3028564453125,
   2506.94384765625],
  'text': 'Agrippa, quicquid magus ille famosissimus Tritemius, quicquid Pisto¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   2580.959716796875,
   1969.8843994140625,
   2585.759765625],
  'text': 'rius apostata & alij de republica diabolorum &c. id omne in vnum coa¬\n',
  'tag': 'text'},
 {'coordinates': [185.75999450683594,
   2653.919677734375,
   1980.56396484375,
   2658.7197265625],
  'text': 'ctum est, & tanquam licitum verumque defenditur. Huius se monar¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   2733.3837890625,
   1994.55029296875,
   2738.3037109375],
  'text': 'cham & principem proclamat Paracelsus, quem adulatores pessimi vo¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   2813.760009765625,
   1985.14404296875,
   2818.56005859375],
  'text': 'cant magnum (imo magum) philosophum paradoxum, mysteriorum\n',
  'tag': 'text'},
 {'coordinates': [183.60000610351562,
   2887.439697265625,
   1991.7359619140625,
   2892.23974609375],
  'text': 'patrem, medicum esc. Ille licet aliquando Galenicus & Hippocraticus\n',
  'tag': 'text'},
 {'coordinates': [190.32000732421875,
   2963.759765625,
   1991.7723388671875,
   2968.559814453125],
  'text': 'velit videri, tamen se sequi iubet omnes, Galenum, Hippocratem, Aui¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   3044.90380859375,
   1988.5064697265625,
   3049.82373046875],
  'text': 'cennam, Lullium, Arnoldum, priscos, recentes, quia sua sit monarchia,\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   3117.35986328125,
   1986.42236328125,
   3122.159912109375],
  'text': 'gloriatur se literas à Galeno ex inferno accepisse, & disputasse cum Aui¬\n',
  'tag': 'text'},
 {'coordinates': [179.0399932861328,
   3193.94384765625,
   1994.19091796875,
   3198.86376953125],
  'text': 'cenna in tartari vestibulo, & alia quae nosti vel ipsis fabulis esse fabulo¬\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   3278.39990234375,
   1112.333984375,
   3283.199951171875],
  'text': 'siora, & impudentiora impudentia.\n',
  'tag': 'text'},
 {'coordinates': [313.44000244140625,
   3350.159912109375,
   1990.743896484375,
   3354.9599609375],
  'text': 'Hic cum ad explicationes rerum naturalium peruentum est, vel\n',
  'tag': 'text'},
 {'coordinates': [174.72000122070312,
   3427.439697265625,
   1997.419677734375,
   3432.23974609375],
  'text': 'ipso Adria est inconstantior & mutabilior vertumno. Cum bacchicus\n',
  'tag': 'text'},
 {'coordinates': [181.44000244140625,
   3501.143798828125,
   1996.6009521484375,
   3506.063720703125],
  'text': 'furor eum rapuit ad coelestia, iam omnia per planetas, stellas, constel¬\n',
  'tag': 'text'},
 {'coordinates': [1470.719970703125,
   3572.159912109375,
   1971.9534912109375,
   3586.31982421875],
  'text': 'latio¬\nAa 3\n',
  'tag': 'footer'},
 {'coordinates': [1972.3199462890625,
   484.5599060058594,
   2175.93798828125,
   489.3598937988281],
  'text': 'Heloparacel¬\n',
  'tag': 'margin'},
 {'coordinates': [1967.760009765625,
   526.8240356445312,
   2042.2366943359375,
   531.7440185546875],
  'text': 'sici.\n',
  'tag': 'margin'}]

In [71]:
for p in textblocks[:50]:
    for t in p:
        if "[" in t["text"]:
            print(t)

{'coordinates': [384.0, 2262.9599609375, 2165.489013671875, 2267.760009765625], 'text': '[GR]χιμικώτερα[/GR] essent seligere, dissentientiaquè componere. Itaque & nouam\n', 'tag': 'text'}
{'coordinates': [139.1999969482422, 3188.159912109375, 1914.183349609375, 3192.9599609375], 'text': 'quoddam [GR]μιγμα[/GR] & commentum ab omni veritate alienum. Sed ostendendum est veram artem nec\n', 'tag': 'text'}
{'coordinates': [398.1600036621094, 511.6800231933594, 2167.622314453125, 516.4800415039062], 'text': 'longe abest à [GR]πανσπερμία[/GR] illa vetere, & atomis Democriti, & multiplici vicissim oriente & pereunte? Sed\n', 'tag': 'text'}
{'coordinates': [390.7200012207031, 2782.079833984375, 2149.680419921875, 2786.8798828125], 'text': 'quętis [GR]σκευασταί καὶ πυροτεηνίαν[/GR], ecce tibi eundem Bulcasim passim inseruientem. Fornaces enim seu Atha¬\n', 'tag': 'text'}
{'coordinates': [198.24000549316406, 1149.1199951171875, 1980.812744140625, 1153.919921875], 'text': 'potest. "Nec ego (inquit in dedicatoria Therapeuseos Galeni) laudabilia medicamenta vitupero: [GR]κακοήθειαν[/GR]\n', 'tag': 'text'}
{'coordinates': [487.44000244140625, 2431.920166015625, 2163.921142578125, 2436.72021484375], 'text': 'Destructio chymica fundamentum in natural [ Cùm aestate & autumno aliisque temporibus plurima\n', 'tag': 'text'}
{'coordinates': [167.0399932861328, 1815.3602294921875, 1964.35009765625, 1820.16015625], 'text': 'est magistratum in nos excitare, vt habeas, quo in sinum tuum gaudeas? [GR]δπιχαιρεκακοι[/GR] no sumus. Tu te\n', 'tag': 'text'}
{'coordinates': [162.24000549316406, 2356.320068359375, 1389.7701416015625, 2361.1201171875], 'text': 'Verùm fit in illis prouerbium, [GR]ὀψέγε φρύγες[/GR]. Et, Malo accepto stultus sapit.\n', 'tag': 'text'}
{'coordinates': [403.44000244140625, 2066.639892578125, 2183.89208984375, 2071.43994140625], 'text': 'methodo per generalia & specialia axiomata sunt dichotomiae [GR]ἀντδιῃρημέναι[/GR], quae vt species habent\n', 'tag': 'text'}
{'coordinates': [186.72000122070312, 2901.599853515625, 1964.145263671875, 2906.39990234375], 'text': 'cinam [GR]κατ’ ἐξοὴν[/GR]. Censor ita de ea disputat, vt videatur intelligere quoduis extractum. In hoc si perma¬\n', 'tag': 'text'}
{'coordinates': [338.6400146484375, 3475.43994140625, 1496.03271484375, 3480.239990234375], 'text': '"[GR]Ασύμβλητον[/GR] elementis immisceri non potest nec cum eis coire ad corpus misti:\n', 'tag': 'text'}
{'coordinates': [345.6000061035156, 3528.744140625, 881.5740356445312, 3533.6640625], 'text': 'Coelum est [GR]ασύμβλητον[/GR] Elementis:"\n', 'tag': 'text'}
{'coordinates': [193.1999969482422, 1529.5439453125, 1980.6802978515625, 1534.4639892578125], 'text': 'sionem [GR]ἀπλῶς[/GR], siue meliorem. Ratio est primum, quod hodie medicamentis & praeceptis aucta me¬\n', 'tag': 'text'}
{'coordinates': [193.1999969482422, 1726.343994140625, 1989.5897216796875, 1731.2640380859375], 'text': 'rere Chymicis. Non potest carere ars medica suo membro, quin sit imperfecta & manca. [Destillatio\n', 'tag': 'text'}
{'coordinates': [200.63999938964844, 3104.39990234375, 1991.309814453125, 3109.199951171875], 'text': 'Hippocrate Hippocratica, nec simul potuit cepisse & perfici. Num vero etiam si respicimus [GR]τὸ εὖ ζῇν¬\n', 'tag': 'text'}
{'coordinates': [200.63999938964844, 3155.280029296875, 1993.7149658203125, 3160.080078125], 'text': 'καὶ ἰᾶσθαι καλᾶς[/GR] possumus carere alchymia, & nominatim destillatoria? Ingratè Dei munera aestimat,\n', 'tag': 'text'}
{'coordinates': [374.1600036621094, 1326.9600830078125, 2144.95458984375, 1331.760009765625], 'text': 'duobus membris principalibus Medicum. Perfectio seu [GR]ιντελέχεια[/GR] est actus quidam cum fine perfecto\n', 'tag': 'text'}
{'coordinates': [174.47999572753906, 2693.760009765625, 1968.1871337890625, 2698.56005859375], 'text': 'boum & sic de aliis omnibus. Discrimen est inter [GR]το ζην[/GR] simpliciter [GR]ευ ζην[/GR]. Minor de antiquitate est fal¬\n', 'tag': 'text'}
{'coordinates': [169.67999267578125, 2743.919921875, 1971.6490478515625, 2748.719970703125], 'text': "sa. Chymica enim & ante Galenum fuerunt & cum ipso, & post ipsum, si non [GR]καθ'\xa0έκαστα[/GR], at [GR]κατα γένη[/GR]. Et\n", 'tag': 'text'}
{'coordinates': [471.3599853515625, 2172.9599609375, 2144.6064453125, 2177.760009765625], 'text': 'Est & imperitia operationum Chymicarum asserere, Chymicorum essentias fieri calidiores [No¬\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 2615.999755859375, 2159.318359375, 2620.7998046875], 'text': 'plecticum, quam Theriaca Parisiensis. Iam itaque maior haec erit: [ Tabernae montanus plus virium\n', 'tag': 'text'}
{'coordinates': [158.8800048828125, 1707.3602294921875, 1950.0943603515625, 1712.16015625], 'text': 'Et hoc si [GR]καθ\' ολου[/GR] iudicandum est, seu simpliciter. "Aula regia quaedam magis iuuatur Chymicis. Haec ergo ante¬\n', 'tag': 'text'}
{'coordinates': [374.8800048828125, 3559.464111328125, 2159.017578125, 3564.384033203125], 'text': 'ceant: Item Chymica relinquunt malam [GR]διάθεσιν[/GR] in partibus nobilibus: perpauci vsi sunt antimonio aut praecipitato,\n', 'tag': 'text'}
{'coordinates': [151.67999267578125, 1188.98388671875, 1941.96337890625, 1193.9039306640625], 'text': 'intemperiei calidae: Chymiam non habere, quia in destillatis maneat [GR]ἐμπύρευμα[/GR]; dum quicquid vi calo¬\n', 'tag': 'text'}
{'coordinates': [274.0799865722656, 2617.199951171875, 1963.833251953125, 2622.0], 'text': 'Respondetur ad maiorem, quod fallat Elencho [GR]τοῦ πῇ καὶ ἁπλῶς[/GR], imo & magna ex parte sit falsa.\n', 'tag': 'text'}
{'coordinates': [225.83999633789062, 905.7598266601562, 387.3038635253906, 910.5598754882812], 'text': 'Olei [S]y[/S]. j. ex\n', 'tag': 'margin'}
{'coordinates': [228.24000549316406, 1523.7598876953125, 402.3943786621094, 1528.559814453125], 'text': 'rum [sic] contra\n', 'tag': 'margin'}

In [72]:
for p in textblocks:
    for t in p:
        if "[/S]" in t["text"]:
            print(t)

{'coordinates': [225.83999633789062, 905.7598266601562, 387.3038635253906, 910.5598754882812], 'text': 'Olei [S]y[/S]. j. ex\n', 'tag': 'margin'}
{'coordinates': [429.1199951171875, 1108.5599365234375, 2191.517578125, 1113.35986328125], 'text': 'crassos. Dosis eius solius [S]z[/S] ij. vsque ad [S]z[/S] iiij. cum aqua frigida. Similia habet Mesues lib simplicium, cap. 16.\n', 'tag': 'text'}
{'coordinates': [241.9199981689453, 2369.999755859375, 407.46197509765625, 2374.7998046875], 'text': 'trahe [S][/S], ex\n', 'tag': 'margin'}
{'coordinates': [234.72000122070312, 2417.999755859375, 407.2383728027344, 2422.7998046875], 'text': 'hoc\xa0[S][/S], & i¬\n', 'tag': 'margin'}
{'coordinates': [424.0799865722656, 312.7200622558594, 2143.775634765625, 317.5200500488281], 'text': 'Lunam, Venerem, Martem, Saturnum, louem; signare vero more astrologorum,\xa0[S]Mercurius[/S],\xa0[S]Sol[/S],\xa0[S]Luna[/S],\xa0[S]Venus[/S],\xa0[S]Mars[/S],\xa0[S]Saturnus[/S],\xa0[S]Jupiter[/S].\n', 'tag': 'text'}
{'coordinates': [1166.4000244140625, 472.3201599121094, 1385.740966796875, 477.1201477050781], 'text': '[S]Saturnus[/S]\xa0Saturnus\n', 'tag': 'text'}
{'coordinates': [1188.0, 530.3999633789062, 1485.612548828125, 535.2000122070312], 'text': '[S]Jupiter[/S]\xa0vel\xa0[S]Jupiter[/S].\xa0Iupiter\n', 'tag': 'text'}
{'coordinates': [1213.9200439453125, 576.2642211914062, 1454.467041015625, 581.1842041015625], 'text': '[S]Mercurius[/S]\xa0Mercurius vel\xa0[S]Mercurius[/S]\n', 'tag': 'text'}
{'coordinates': [1538.6400146484375, 475.9441223144531, 1812.8485107421875, 480.8641357421875], 'text': '[S]Mars[/S] vel\xa0[S]Mars[/S]\xa0Mars\n', 'tag': 'text'}
{'coordinates': [1506.0, 532.5601196289062, 1686.530029296875, 537.3601684570312], 'text': '[S]Venus[/S] Venus\n', 'tag': 'text'}
{'coordinates': [1503.8399658203125, 584.1599731445312, 1697.5361328125, 588.9600219726562], 'text': '[S]Luna[/S] Luna\xa0[S]Luna[/S]\n', 'tag': 'text'}
{'coordinates': [1514.6400146484375, 634.3201293945312, 1646.7060546875, 639.1201782226562], 'text': '[S]Sol[/S]\xa0Sol.\n', 'tag': 'text'}
{'coordinates': [1327.6800537109375, 1278.7200927734375, 1373.8641357421875, 1283.52001953125], 'text': '[S]crux[/S]\n', 'tag': 'text'}
{'coordinates': [1060.3199462890625, 1432.823974609375, 1571.1358642578125, 1437.7440185546875], 'text': '[S]Aries[/S]\xa0[S]Taurus[/S]\xa0[S]Gemini[/S]\xa0\xa0[S]Cancer[/S]\xa0[S]]Leo[/S]\xa0\xa0[S]Virgo[/S]\n', 'tag': 'text'}
{'coordinates': [1049.52001953125, 1494.4801025390625, 1563.99609375, 1499.280029296875], 'text': '[S]Libra[/S]\xa0[S]Scorpio[/S]\xa0[S]Sagittarius[/S]\xa0[S]Capricornus[/S]\xa0[S] Aquarius[/S]\xa0[S]Pisces[/S]\n', 'tag': 'text'}
{'coordinates': [428.3999938964844, 1661.0401611328125, 2124.18017578125, 1665.840087890625], 'text': 'monstrat in illa vnione hieroglyphica Indicos hos characteres. I. 2. 3. 4. (vel [S]piscis[/S]) 5. 6.\n', 'tag': 'text'}
{'coordinates': [846.0, 2991.384033203125, 1560.7996826171875, 2996.303955078125], 'text': '[S]Libra[/S]\xa0vel\xa0[S]Taurus[/S]\xa0vel\xa0[S]Venus[/S]\xa0vel\xa0[S]Mercurius[/S]\xa0vel [S][/S] [S][/S]\n', 'tag': 'text'}
{'coordinates': [517.2000122070312, 3050.159912109375, 2166.363037109375, 3054.9599609375], 'text': 'Quidam tamen etiam vsurpant signum capitis draconis [S]caput draconis[/S], cui apponunt aliquando figuram\n', 'tag': 'text'}
{'coordinates': [411.1199951171875, 3098.880126953125, 2168.111572265625, 3103.68017578125], 'text': 'mercurii\xa0[S]Mercurius[/S] [S]caput draconis[/S]. Nam posterior nota etiam sublimationis character est, quam phanatici sic pingen¬\n', 'tag': 'text'}
{'coordinates': [415.44000244140625, 3156.9599609375, 2169.962646484375, 3161.760009765625], 'text': 'tes [S][/S]\xa0accommodarunt cineribus, & aquae vitae. Porro ex illa monade etiam haec dependent [S][/S]\xa0dies\n', 'tag': 'text'}
{'coordinates': [419.760009765625, 3212.880126953125, 2157.210693359375, 3217.68017578125], 'text': '[S][/S]\xa0nox: [S][/S]\xa0miniùm ex plumbo. [S][/S]\xa0limatura ferri, [S][/S]\xa0limatura chalybis. [S][/S]\xa0Crocus martis (ali¬\n', 'tag': 'text'}
{'coordinates': [415.44000244140625, 3270.02392578125, 2164.44482421875, 3274.94384765625], 'text': 'qui etiam sic pingunt [S][/S]\xa0vel [S][/S]\xa0fors cum sulphure factum designantes [S][/S]\xa0aerugo; [S][/S]\xa0atramen¬\n', 'tag': 'text'}
{'coordinates': [408.9599914550781, 3328.10400390625, 2154.82080078125, 3333.02392578125], 'text': 'tùm (quae nota efformatur etiam aliter vt: [S][/S], [S][/S]) [S][/S]\xa0halonitrum: [S][/S]\xa0alumen: [S][/S]\xa0acetum.\n', 'tag': 'text'}
{'coordinates': [421.9200134277344, 3392.639892578125, 2158.311767578125, 3397.43994140625], 'text': '\xa0[S][/S] Sal (vel\xa0[S]Gemini[/S]\xa0[S][/S]) O antimonium (alias [S][/S] [S][/S] [S][/S])\xa0ammoniacus (vel [S][/S]) [S][/S] oleum\n', 'tag': 'text'}
{'coordinates': [404.6400146484375, 3456.47998046875, 2121.532958984375, 3461.280029296875], 'text': 'subtile correctum (aliqui silici combusto seu calcinato tribuunt.) Hinc [S][/S]\xa0oleum vitrioli. [S][/S] hy¬\n', 'tag': 'text'}
{'coordinates': [411.1199951171875, 3510.719970703125, 2166.40087890625, 3515.52001953125], 'text': 'drargyrus praecipitatus. [S][/S]\xa0cinabaris. [S][/S]\xa0flos aeris: [S][/S]\xa0cerussa. [S][/S]\xa0ignis. [S][/S]\xa0aqua. [S][/S]\xa0sulphur (vel\n', 'tag': 'text'}
{'coordinates': [1982.1600341796875, 3558.0, 2145.5341796875, 3562.800048828125], 'text': '[S][/S] [S][/S]\xa0vel\n', 'tag': 'footer'}
{'coordinates': [190.55999755859375, 284.3999938964844, 1983.221435546875, 289.1999816894531], 'text': '[S][/S] [S][/S] vel [S][/S]\xa0nam variè pingitur, vt & crucis signo) sed magna est varietas, & in plaerisque aliis domi¬\n', 'tag': 'text'}
{'coordinates': [181.1999969482422, 384.2398376464844, 1989.5478515625, 389.0398254394531], 'text': 'diuinare, & ex praesente narratione, scopoque colligere, quid sibi velint. Hac nota [S][/S]\xa0acetum stillati¬\n', 'tag': 'text'}
{'coordinates': [181.1999969482422, 498.0239562988281, 1988.868896484375, 502.9439697265625], 'text': 'bium ostendit. Sali petraeo tribuuntur & hae [S][/S] [S][/S] [S][/S]\xa0&c. viride aeris [S][/S]. Sed nolo molestus esse\n', 'tag': 'text'}
{'coordinates': [207.1199951171875, 604.7998657226562, 1987.423095703125, 609.5999145507812], 'text': '[S][/S] calx viua: [S][/S] [S][/S] orichalcum, [S][/S]\xa0sal alcali. [S][/S] Galmia [S][/S] aes rustum: [S][/S]\xa0Lazurium. [S][/S]\xa0minium\n', 'tag': 'text'}
{'coordinates': [188.16000366210938, 663.5999145507812, 1977.362548828125, 668.3999633789062], 'text': '[S][/S] lac recens. [S][/S]\xa0atramentum album. [S][/S]\xa0sal crystallinus ex plumbo: & sal alabroth. [S][/S] vitrum.\n', 'tag': 'text'}
{'coordinates': [202.32000732421875, 717.3599243164062, 1987.8023681640625, 722.1599731445312], 'text': '[S][/S] arsenicum [S][/S]\xa0Thutia sublimata. [S][/S]\xa0alumen catinum [S][/S]\xa0magnesia [S][/S] aque fortis [S][/S]\xa0auri¬\n', 'tag': 'text'}
{'coordinates': [621.3599853515625, 1139.06396484375, 1534.22021484375, 1143.9840087890625], 'text': '[S][/S] [S][/S]\xa0[S] Aquarius[/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S] [S][/S]\n', 'tag': 'text'}
{'coordinates': [651.3599853515625, 1186.343994140625, 1508.04833984375, 1191.2640380859375], 'text': '[S]Libra[/S]\xa0[S]Luna[/S]\xa0[S]Virgo[/S]\xa0[S]Mercurius[/S]\xa0[S]]Leo[/S]\xa0[S]Venus[/S]\xa0[S]Cancer[/S]\xa0[S]Sol[/S]\xa0[S]Gemini[/S][S]Mars[/S]\n', 'tag': 'text'}
{'coordinates': [623.52001953125, 1227.143798828125, 1497.792236328125, 1232.0638427734375], 'text': '[S]Taurus[/S]\xa0[S]Jupiter[/S]\xa0[S]Aries[/S]\xa0[S][/S]\xa0quae teutonum more sunt\n', 'tag': 'text'}
{'coordinates': [280.0799865722656, 1357.703857421875, 1831.24951171875, 1362.6239013671875], 'text': 'Scriptura ergo haec: [S][/S]\n', 'tag': 'title'}
{'coordinates': [395.2799987792969, 1552.823974609375, 1009.2324829101562, 1557.7440185546875], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [411.8399963378906, 1603.4400634765625, 828.1699829101562, 1608.239990234375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [527.0399780273438, 1754.183837890625, 1089.233154296875, 1759.1038818359375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [371.760009765625, 1800.4798583984375, 842.3472290039062, 1805.27978515625], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [381.1199951171875, 1848.98388671875, 802.3519897460938, 1853.9039306640625], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [329.5199890136719, 2276.423828125, 1887.2523193359375, 2281.34375], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [268.32000732421875, 2659.94384765625, 1915.25439453125, 2664.86376953125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [430.55999755859375, 2974.10400390625, 1534.022705078125, 2979.02392578125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [230.63999938964844, 3333.6240234375, 2122.053955078125, 3338.5439453125], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [1041.1199951171875, 407.0401306152344, 2153.123779296875, 411.8401184082031], 'text': '[S][/S]\n', 'tag': 'title'}
{'coordinates': [384.9599914550781, 925.9199829101562, 2188.209228515625, 930.7200317382812], 'text': 'cum, indeque extractum florem designare, hanc efformare posset effigiem [S][/S], vt crocum magistralem\n', 'tag': 'text'}
{'coordinates': [382.55999755859375, 982.5601196289062, 2185.1982421875, 987.3601684570312], 'text': 'indicaret; vt florem, hanc: [S][/S], vel [S][/S]. Cerussa plumbi in magisterio ex Saturni charactere deberet ex¬\n', 'tag': 'text'}
{'coordinates': [389.2799987792969, 1040.6400146484375, 2181.181640625, 1045.43994140625], 'text': 'culpi, nempe [S][/S]\xa0vt puncta calcinationem insinuarent. Flos sic: [S][/S]. Dorneiserus male obseruauit\n', 'tag': 'text'}
{'coordinates': [384.9599914550781, 1096.5601806640625, 2186.368408203125, 1101.360107421875], 'text': 'fundamentum, cum eam pinxit [S][/S]. Si omnino Zeta litera ternarii specie Indica expressa cerussam\n', 'tag': 'text'}
{'coordinates': [389.2799987792969, 1359.3602294921875, 2185.188720703125, 1364.16015625], 'text': 'actere [S][/S]\xa0vel [S][/S], quasi inuersus, mutatusque sit Saturnus. Non recte ltaque accommodatur ad stibium.\n', 'tag': 'text'}
{'coordinates': [391.67999267578125, 1464.7200927734375, 2185.862548828125, 1469.52001953125], 'text': 'plumbi sic scribetur [S][/S]\xa0vt intelligamus ealcinatum Saturnum diffluxisse deliquio in aquam: sed aliter\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1522.8001708984375, 2186.149169921875, 1527.60009765625], 'text': 'oleum nempe in hunc modum [S][/S]. Ex liquore enim fit per inclinationem. Caetera qui sunt ingeniosi,\n', 'tag': 'text'}
{'coordinates': [384.9599914550781, 1627.944091796875, 2168.281982421875, 1632.8641357421875], 'text': 'signisicandae essentiae aut magisterio, vel horum initialem figurae adiiciunt: vt [S][/S]\xa0pro coagulare: [S][/S]\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1682.424072265625, 2178.778564453125, 1687.3441162109375], 'text': 'pro figere [S][/S]\xa0calx vitrioli [S][/S]\xa0destillare: [S][/S]\xa0sublimare. Quidam pingunt res vnde ducta meta¬\n', 'tag': 'text'}
{'coordinates': [398.1600036621094, 1749.384033203125, 2189.18798828125, 1754.3040771484375], 'text': 'phora est, vel conceptaculum vulgo vsitatum vt: [S][/S]\xa0caput mortuum: [S][/S]\xa0pro aqua vitae: aut coniiciunt\n', 'tag': 'text'}
{'coordinates': [393.8399963378906, 1797.1202392578125, 2191.741455078125, 1801.920166015625], 'text': 'literas in schema, quod tamen felicius praestant Ebraei, Chaldaei, Indi etc. vt [S][/S] Spiritus vini, quasi\n', 'tag': 'text'}
{'coordinates': [136.32000732421875, 2856.47998046875, 1942.3367919921875, 2861.280029296875], 'text': 'albae, an. lib. ß: squamae ferri [S]y[/S] iij. argillae bonae lib. ij. saxi murarij rubri, calcis viuae an. lib. ß. fimi equini praeparati, vel\n', 'tag': 'text'}
{'coordinates': [379.20001220703125, 1292.1600341796875, 2186.82666015625, 1296.9599609375], 'text': 'lutum albo ouorum subactum: vel componito cretae, "pollinis molendinorum, vitri an. [S]y[/S] ij. farinae laterum [S]y[/S]. j. oui\n', 'tag': 'text'}
{'coordinates': [381.8399963378906, 2081.52001953125, 2177.006103515625, 2086.320068359375], 'text': 'an. [S]y[/S]. viij. collique facta in massam coeant. Huiusmodi sunt & haec: "Farina laterum pars vna: pollinis è vitro pars tertia:\n', 'tag': 'text'}
{'coordinates': [391.44000244140625, 3456.26416015625, 2189.834716796875, 3461.18408203125], 'text': 'ris lithargyri, & vitri an. [S]y[/S] iij. farinae triticeae lib. ß. ex oui albo fiat pasta", quae intra & extra plagulas inducatur, &\n', 'tag': 'text'}
{'coordinates': [111.5999984741211, 1621.9200439453125, 1913.5340576171875, 1626.719970703125], 'text': '& tamen officinis placet: Aliter: "picis nigrae cerae an. [S]y[/S]. j. Calcis viuae laeuoris lateritij. an. [S]y[/S]. ß. misce ad calorem."\n', 'tag': 'text'}
{'coordinates': [1110.239990234375, 1647.384033203125, 1467.775634765625, 1652.3040771484375], 'text': '(crux[/S]) (crux[/S])\n', 'tag': 'margin'}
{'coordinates': [827.0399780273438, 2520.239990234375, 1168.0421142578125, 2525.0400390625], 'text': '\xa0[S]crux[/S] [S]crux[/S] [S]crux[/S]\n', 'tag': 'text'}
{'coordinates': [100.08000183105469, 3451.43994140625, 1882.7705078125, 3456.239990234375], 'text': 'silem apertilemque pro arbitratu. N. Aquilonaris fenestra cubiculi herilis. [S]Ξ[/S]. [S]Ο[/S] & [S]Π[/S]. Cubi¬\n', 'tag': 'text'}
{'coordinates': [97.68000030517578, 3500.639892578125, 1883.546630859375, 3505.43994140625], 'text': 'cula familiae herilis. P. Xenium, quod si placet distingui diaeta & cubili potest. [S]Σ[/S]. Penu superius:\n', 'tag': 'text'}
{'coordinates': [95.5199966430664, 3548.639892578125, 1892.1455078125, 3553.43994140625], 'text': 'T. Effluxus aquarum laboratorii ferramentis fortibus muniendus. [S]Γ[/S]. Spiracula labotatoril & fora¬\n', 'tag': 'text'}
{'coordinates': [1080.47998046875, 270.7439270019531, 1517.4407958984375, 275.6639404296875], 'text': '[S]crux[/S] [S]crux[/S] [S]crux[/S]\n', 'tag': 'text'}
{'coordinates': [410.8800048828125, 2133.3837890625, 2163.35595703125, 2138.3037109375], 'text': 'oportet esse instructa, vt quantum & quando vsus exigit, admittatur aura. [S]Φ[/S]. Caminus laborato¬\n', 'tag': 'text'}
{'coordinates': [406.55999755859375, 2182.320068359375, 2160.384033203125, 2187.1201171875], 'text': 'rii. [S]X[/S]. Diaeta probatorii. [S]Ψ[/S]. Diaeta penetralis. [S]Ω[/S]. Contignationum culminis valuae. [S]r[/S]. Fumibu¬\n', 'tag': 'text'}
{'coordinates': [658.5599975585938, 2042.18408203125, 733.8024291992188, 2047.1041259765625], 'text': '(:[S]crux[/S]):) (:[S]crux[/S]):) (:[S]crux[/S]):)\n', 'tag': 'text'}
{'coordinates': [970.7999877929688, 1027.4638671875, 1041.4744873046875, 1032.3839111328125], 'text': '(:[S]crux[/S]):) (:[S]crux[/S]):) (:[S]crux[/S]):)\n', 'tag': 'text'}
{'coordinates': [1109.280029296875, 2160.26416015625, 1187.9091796875, 2165.18408203125], 'text': ')[S]crux[/S]( )[S]crux[/S](\n', 'tag': 'text'}
{'coordinates': [1038.719970703125, 634.1040649414062, 1108.21337890625, 639.0240478515625], 'text': ')[S]crux[/S]( )[S]crux[/S](\n', 'tag': 'text'}
{'coordinates': [1543.6800537109375, 2153.27978515625, 2184.681640625, 2158.079833984375], 'text': 'tur fornaces. [S]Saturnus[/S] Vstrina argenti est\n', 'tag': 'text'}
{'coordinates': [1543.6800537109375, 2201.27978515625, 2184.14111328125, 2206.079833984375], 'text': 'absque tegula:\xa0[S]Jupiter[/S]\xa0eiusdem vsus\n', 'tag': 'text'}
{'coordinates': [1539.1199951171875, 2301.599853515625, 2184.455078125, 2306.39990234375], 'text': 'formata.\xa0[S]Mars[/S]\xa0fusoria capsa popularis\n', 'tag': 'text'}
{'coordinates': [1541.280029296875, 2498.639892578125, 2185.93115234375, 2503.43994140625], 'text': 'desuper follibus.\xa0[S]Sol[/S]\xa0Ventosa est, seu\n', 'tag': 'text'}
{'coordinates': [2019.5999755859375, 3639.599853515625, 2146.934326171875, 3644.39990234375], 'text': '[S]Mercurius[/S] \xa0Ca¬\n', 'tag': 'footer'}
{'coordinates': [1291.43994140625, 298.3199157714844, 1895.412841796875, 303.1199035644531], 'text': '[S]Mercurius[/S]\xa0Caementatorius Panthei, quan¬\n', 'tag': 'text'}
{'coordinates': [1242.47998046875, 838.5598754882812, 1881.9483642578125, 843.3599243164062], 'text': 'remouenda aqua est.\xa0[S]Luna[/S]\xa0Vstrina A¬\n', 'tag': 'text'}
{'coordinates': [1526.8800048828125, 2421.599853515625, 2188.16015625, 2426.39990234375], 'text': 'figies. [S]Sol[/S] clausum habet focum, &\n', 'tag': 'text'}
{'coordinates': [1521.8399658203125, 2569.199951171875, 2179.95166015625, 2574.0], 'text': 'rali & metallica instructum. [S]luna[/S] exhi¬\n', 'tag': 'text'}
{'coordinates': [1285.199951171875, 400.0799255371094, 1926.544189453125, 404.8799133300781], 'text': 'coctorio signat;\xa0[S]Jupiter[/S].\xa0feriantem per¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2330.639892578125, 1888.8544921875, 2335.43994140625], 'text': 'be lapideo, sufficiat, [S]Capricornus[/S] orbis lapide¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2379.35986328125, 1886.61328125, 2384.159912109375], 'text': 'us:\xa0[S]Gemini[/S]\xa0pedamentum cum macerie\n', 'tag': 'text'}
{'coordinates': [1239.5999755859375, 2426.90380859375, 1891.1217041015625, 2431.82373046875], 'text': 'detussata ab antico effractum:\xa0[S]Aquarius[/S]\xa0pe¬\n', 'tag': 'text'}
{'coordinates': [1242.0, 2533.94384765625, 1893.4879150390625, 2538.86376953125], 'text': 'clausa cum pilis. [S]Sagittarius[/S]\xa0focus stractus\n', 'tag': 'text'}
{'coordinates': [1237.43994140625, 2582.8798828125, 1888.95703125, 2587.679931640625], 'text': 'super pedamento. In effigie [S]Gemini[/S], li¬\n', 'tag': 'text'}
{'coordinates': [100.80000305175781, 2828.639892578125, 1906.6788330078125, 2833.43994140625], 'text': 'muri interni & angustiora. E. interstitium triangulare inter alas. In pictura [S]Aquarius[/S]\xa0litera. F. signat pilas\n', 'tag': 'text'}
{'coordinates': [432.7200012207031, 2864.423828125, 2174.7978515625, 2869.34375], 'text': 'Tres fulminatorii species offeruntur\xa0[S]Mercurius[/S] vulgata in Ioachimicis, Sclaccevvaldensibus & aliorum lo¬\n', 'tag': 'text'}
{'coordinates': [382.0799865722656, 2913.14404296875, 2163.592529296875, 2918.06396484375], 'text': 'corum officinis cum testudine ferrea:\xa0[S]Leo[/S]\xa0Liberimontana, qualis est &\xa0[S]Libra[/S], sed diuersa orificiorum\n', 'tag': 'text'}
{'coordinates': [386.3999938964844, 2962.34375, 2169.555419921875, 2967.263671875], 'text': 'dispositione In signa [S]Mercurius[/S], character A. notat pedamenti ambitum ex saxo natiuo. B. spiracula: C. pi¬\n', 'tag': 'text'}
{'coordinates': [375.3599853515625, 3353.303955078125, 2159.75830078125, 3358.223876953125], 'text': 'quam & per orificium ergasticum immittantur. In schemate [S]Leo[/S] M. pedamentum furni: N. fornix\n', 'tag': 'text'}
{'coordinates': [371.0400085449219, 3548.423828125, 2153.776123046875, 3553.34375], 'text': 'intus pilas triangulas habent, & viarum diuortia seu biuium decussatum. In pictura\xa0[S]Libra[/S]\xa0X. plantam muratam\n', 'tag': 'text'}
{'coordinates': [378.0, 460.7998962402344, 1958.2998046875, 466.3198547363281], 'text': 'autem etiam folles ex praecepto Geberi. Focus est vt praecedenti pagina liquet.\n) : [S]crux[/S] : (\n', 'tag': 'text'}
{'coordinates': [536.6400146484375, 510.9598083496094, 2181.16015625, 515.7598266601562], 'text': '[S][/S] Morauorum fulminatorium.\xa0[S][/S]\xa0Calix fulminatorius cum lacuna & fenestris in pedamento ad\n', 'tag': 'text'}
{'coordinates': [383.0400085449219, 560.3999633789062, 2184.374755859375, 565.2000122070312], 'text': 'recipiendum lithargyrum, & auertendos halitus.\xa0[S][/S]\xa0Circulus super foco concamerato, ex cuius strato\n', 'tag': 'text'}
{'coordinates': [1197.5999755859375, 804.9597778320312, 2165.358154296875, 809.7598266601562], 'text': '[S]Saturnus[/S]\xa0Fulminatorium, seu cineritium Hungarorum con¬\n', 'tag': 'text'}

In [73]:
def add_tag_info_to_char_mapping(full_text, char_to_source):
    """
    Parse inline tags like [GR]...[/GR], [M]...[/M], [S]...[/S] in full_text
    and attach a "tags" field (list of active tags) to char_to_source[char_idx].
    """
    active_tags = []  # stack / list of currently open tags
    i = 0
    n = len(full_text)

    while i < n:
        ch = full_text[i]

        if ch == "[":
            # Try to find the closing bracket of this [TAG] or [/TAG]
            close = full_text.find("]", i + 1)
            if close == -1:
                # malformed tag, treat as normal char
                if i in char_to_source and active_tags:
                    tags_set = char_to_source[i].setdefault("tags", set())
                    tags_set.update(active_tags)
                i += 1
                continue

            content = full_text[i + 1:close]

            if content.startswith("/"):
                # closixng tag, e.g. [/GR]
                label = content[1:]
                # remove from active_tags (LIFO or first match)
                if active_tags and active_tags[-1] == label:
                    active_tags.pop()
                elif label in active_tags:
                    active_tags.remove(label)
                # We don't assign tags to the '['...']' characters themselves here
            else:
                # opening tag, e.g. [GR]
                label = content
                active_tags.append(label)

            # skip past the closing ']'
            i = close + 1
            continue

        else:
            # normal character: assign currently active tags (if any)
            if i in char_to_source and active_tags:
                tags_set = char_to_source[i].setdefault("tags", set())
                tags_set.update(active_tags)
            i += 1

    # normalize sets → lists (so they are JSON-serializable, nicer to inspect)
    for info in char_to_source.values():
        if "tags" in info and isinstance(info["tags"], set):
            info["tags"] = sorted(info["tags"])

    return char_to_source

In [74]:
    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):
            if tb["tag"] not in {"text", "title", "margin"}:
                continue



    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):
            if tb["tag"] == "margin":
                continue

In [75]:
import re
import unicodedata
from spacy.tokens import Token, Doc
from spacy.language import Language

# -------------------------------------------------------------------
# 0. Token / Doc extensions
# -------------------------------------------------------------------
for ext, default in [
    ("pages", None),
    ("textblocks", None),
    ("tags", None),
    ("block_type", None),
]:
    if not Token.has_extension(ext):
        Token.set_extension(ext, default=default)

if not Doc.has_extension("char_to_source"):
    Doc.set_extension("char_to_source", default=None)


# -------------------------------------------------------------------
# CLEANER: keep tag *content*, strip tag markers, clean only outside spans
# -------------------------------------------------------------------
TAG_PATTERN = re.compile(r"(\[[A-Za-z]+]|\[/[A-Za-z]+])")


def text_cleaner_keep_tags(raw_text: str) -> str:
    """
    Clean Latin text but NEVER modify text inside markup spans like:
        [GR]...[/GR], [S]...[/S], [M]...[/M]

    Behaviour:
      - Split raw text into TAG / NON-TAG parts.
      - Maintain a stack of open tags (supports nested, though unlikely).
      - REMOVE tag markers [TAG] and [/TAG] from the output.
      - Inside-tag content is preserved exactly (NFC-normalized).
      - Outside-tag content is cleaned with the Latin OCR pipeline.
    """
    # normalize non-breaking spaces to normal spaces
    raw_text = raw_text.replace("\xa0", " ")

    parts = re.split(TAG_PATTERN, raw_text)
    cleaned_parts = []
    stack = []  # open tag names

    for part in parts:
        # Opening tag: [GR], [S], [M], ...
        if re.fullmatch(r"\[[A-Za-z]+]", part):
            stack.append(part[1:-1])
            # DO NOT append the tag itself to output
            continue

        # Closing tag: [/GR], [/S], ...
        if re.fullmatch(r"\[/[A-Za-z]+]", part):
            name = part[2:-1]
            if stack and stack[-1] == name:
                stack.pop()
            # DO NOT append the tag marker either
            continue

        # Inside any tag span → preserve content, just normalize
        if stack:
            cleaned_parts.append(unicodedata.normalize("NFC", part))
            continue

        # Outside tags → Latin cleaning
        x = part
        x = x.replace("¬\n", "").replace("\n", " ")
        x = x.replace("ß", "ss").replace("ij", "ii")
        x = re.sub(r"\s\s+", " ", x)

        # Fix OCR margin stars: "*Nota" → "Nota"
        x = re.sub(r"^\*+(\w)", r"\1", x)

        # First letter as-is, rest lowercase
        x = re.sub(r'\b(\w)(\w*)\b', lambda m: m.group(1) + m.group(2).lower(), x)

        x = x.replace(". &", ", &")
        x = x.replace("v", "u").replace("V", "U")

        cleaned_parts.append(x)

    return "".join(cleaned_parts)


# -------------------------------------------------------------------
# 1. Build raw + clean text and mapping  (generic for any tag set)
# -------------------------------------------------------------------
def _process_textblocks_for_tags(textblocks, allowed_tags):
    """
    Same logic as your original process_textblocks, but restricted to
    a set of block tags (e.g. {"text", "title"} or {"margin"}).

    Returns:
      raw_full, clean_full, raw_to_clean, char_src
    """

    raw_full = ""
    clean_full = ""
    raw_to_clean = {}
    char_src = {}

    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):
            if tb["tag"] not in allowed_tags:
                continue

            raw_text = tb["text"]
            clean_text = text_cleaner_keep_tags(raw_text)

            r0 = len(raw_full)
            c0 = len(clean_full)

            r_i = 0
            c_i = 0
            len_raw = len(raw_text)
            len_clean = len(clean_text)

            while r_i < len_raw and c_i < len_clean:
                rc = raw_text[r_i]
                cc = clean_text[c_i]

                raw_idx = r0 + r_i
                clean_idx = c0 + c_i

                if rc == cc:
                    # Normal 1:1 character
                    raw_to_clean[raw_idx] = clean_idx
                    char_src[clean_idx] = {
                        "page_idx": page_idx,
                        "textblock_idx": tb_idx,
                        "textblock_type": tb["tag"],
                    }
                    r_i += 1
                    c_i += 1
                    continue

                # Raw is at a tag marker? Skip it entirely in raw.
                if raw_text.startswith("[", r_i):
                    end = raw_text.find("]", r_i)
                    if end == -1:
                        # Malformed tag: treat '[' as a normal char
                        raw_to_clean[raw_idx] = clean_idx
                        char_src[clean_idx] = {
                            "page_idx": page_idx,
                            "textblock_idx": tb_idx,
                            "textblock_type": tb["tag"],
                        }
                        r_i += 1
                        c_i += 1
                    else:
                        for skip in range(r_i, end + 1):
                            raw_to_clean[r0 + skip] = None
                        r_i = end + 1
                    continue

                # Otherwise: cleaner changed the char (case, diacritics, space, …)
                raw_to_clean[raw_idx] = clean_idx
                char_src[clean_idx] = {
                    "page_idx": page_idx,
                    "textblock_idx": tb_idx,
                    "textblock_type": tb["tag"],
                }
                r_i += 1
                c_i += 1

            # Any trailing raw chars (should be rare) → no clean mapping
            while r_i < len_raw:
                raw_to_clean[r0 + r_i] = None
                r_i += 1

            raw_full += raw_text
            clean_full += clean_text

    return raw_full, clean_full, raw_to_clean, char_src


# -------------------------------------------------------------------
# 2. Greek-aware + S-aware tag extractor
# -------------------------------------------------------------------
GREEK_RE = re.compile(r"[\u0370-\u03FF\u1F00-\u1FFF]")


def extract_tags_from_raw(raw_text: str):
    """
    Build char-level tag assignments on RAW indices.

    GR:
      - Any character in Greek Unicode ranges → tag "GR".

    S:
      - [S] ... [/S] → all characters between them get tag "S".
      - [S][/S] (empty) → ignored.
      - Lone [S] with no [/S] → tag immediately following token:
            characters from end-of-[S] up to next whitespace or '['.
    """

    raw_tags = {}  # raw_idx -> set(labels)
    markup_spans = []

    tag_pattern = re.compile(r"\[(?P<tag>[A-Za-z]+)]|\[/(?P<etag>[A-Za-z]+)]")
    matches = list(tag_pattern.finditer(raw_text))

    # record markup spans (for debugging / future use)
    for m in matches:
        markup_spans.append(m.span())

    # --- GR: any Greek character in raw_text ---
    for idx, ch in enumerate(raw_text):
        if GREEK_RE.match(ch):
            raw_tags.setdefault(idx, set()).add("GR")

    # --- S: explicit [S] ... [/S] and lone [S] ---

    # Track opening [S] tokens
    open_S = []  # list of match objects for [S]

    for m in matches:
        start, end = m.span()
        tag = m.group("tag")
        etag = m.group("etag")

        if tag == "S":
            # Opening [S]
            open_S.append(m)

        elif etag == "S":
            # Closing [/S] – match with the last unmatched [S]
            for j in range(len(open_S) - 1, -1, -1):
                open_m = open_S[j]
                if open_m is None:
                    continue
                open_end = open_m.end()
                close_start = start
                # assign S to chars between [S] and [/S]
                for raw_idx in range(open_end, close_start):
                    raw_tags.setdefault(raw_idx, set()).add("S")
                open_S[j] = None  # mark as matched
                break

    # Handle lone [S] (without a closing [/S])
    for open_m in open_S:
        if open_m is None:
            continue
        i = open_m.end()  # position just after ']'
        # Tag immediately following "token": chars until whitespace or new tag
        n = len(raw_text)
        while i < n and not raw_text[i].isspace():
            if raw_text[i] == "[":
                break  # new tag, stop
            raw_tags.setdefault(i, set()).add("S")
            i += 1

    return raw_tags, markup_spans


# -------------------------------------------------------------------
# 3. raw → clean tag mapping
# -------------------------------------------------------------------
def map_raw_tags_to_clean(raw_tags, raw_to_clean):
    clean_tags = {}  # clean_idx -> set(labels)
    for raw_idx, tagset in raw_tags.items():
        clean_idx = raw_to_clean.get(raw_idx)
        if clean_idx is not None:
            clean_tags.setdefault(clean_idx, set()).update(tagset)
    return clean_tags


# -------------------------------------------------------------------
# 4. High-level processor (MAIN + MARGINS)
# -------------------------------------------------------------------
def process_with_source_tracking(textblocks, nlp):
    """
    Returns two docs with identical structure but different content sources:

      doc_main    – based on block tags {"text", "title"}
      doc_margins – based on block tag {"margin"}

    Greek/S tags and char_to_source mappings are computed independently
    for each branch, so all indices remain consistent.
    """

    # ----- MAIN TEXT (text + title) -----
    raw_main, clean_main, raw2clean_main, src_main = _process_textblocks_for_tags(
        textblocks, allowed_tags={"text", "title"}
    )

    raw_tags_main, _ = extract_tags_from_raw(raw_main)
    clean_tags_main = map_raw_tags_to_clean(raw_tags_main, raw2clean_main)

    for clean_idx, tagset in clean_tags_main.items():
        if clean_idx in src_main:
            existing = set(src_main[clean_idx].get("tags", []))
            src_main[clean_idx]["tags"] = sorted(existing | set(tagset))

    doc_main = nlp.make_doc(clean_main)
    doc_main._.char_to_source = src_main

    for name, proc in nlp.pipeline:
        doc_main = proc(doc_main)

    # ----- MARGINS ONLY -----
    raw_marg, clean_marg, raw2clean_marg, src_marg = _process_textblocks_for_tags(
        textblocks, allowed_tags={"margin"}
    )

    raw_tags_marg, _ = extract_tags_from_raw(raw_marg)
    clean_tags_marg = map_raw_tags_to_clean(raw_tags_marg, raw2clean_marg)

    for clean_idx, tagset in clean_tags_marg.items():
        if clean_idx in src_marg:
            existing = set(src_marg[clean_idx].get("tags", []))
            src_marg[clean_idx]["tags"] = sorted(existing | set(tagset))

    doc_marg = nlp.make_doc(clean_marg)
    doc_marg._.char_to_source = src_marg

    for name, proc in nlp.pipeline:
        doc_marg = proc(doc_marg)

    return doc_main, doc_marg


# -------------------------------------------------------------------
# 5. Source tracker: assign page / textblock / tags / block_type to tokens
# -------------------------------------------------------------------
@Language.component("source_tracker")
def source_tracker(doc):
    cts = doc._.char_to_source
    if cts is None:
        return doc

    for token in doc:
        pages = set()
        textblocks = set()
        block_types = set()
        tags = set()

        for i in range(token.idx, token.idx + len(token.text)):
            info = cts.get(i)
            if not info:
                continue
            pages.add(info["page_idx"])
            textblocks.add(info["textblock_idx"])
            bt = info.get("textblock_type")
            if bt:
                block_types.add(bt)
            if "tags" in info:
                tags.update(info["tags"])

        token._.pages = sorted(pages) if pages else None
        token._.textblocks = sorted(textblocks) if textblocks else None
        token._.block_type = next(iter(block_types)) if block_types else "text"
        token._.tags = sorted(tags) if tags else None

    return doc


# -------------------------------------------------------------------
# 6. Block-type-based sentence splitter
# -------------------------------------------------------------------
@Language.component("blocktype_sentencizer")
def blocktype_sentencizer(doc):
    prev_bt = None
    for token in doc:
        bt = token._.block_type
        if prev_bt is None or bt != prev_bt:
            token.is_sent_start = True
        prev_bt = bt
    return doc


# -------------------------------------------------------------------
# 7. Greek enrichment (unchanged logic, applied to both docs)
# -------------------------------------------------------------------
for ext in ["gr_lemma", "gr_pos", "gr_morph", "gr_dep", "gr_norm"]:
    if not Token.has_extension(ext):
        Token.set_extension(ext, default=None)


@Language.component("greek_enricher")
def greek_enricher(doc):
    """
    Post-hoc Greek morphological enrichment:

      - Find contiguous GR-tagged spans in the doc.
      - For each span, run greek_nlp(span.text).
      - Align tokens by order (zip).
      - Copy Greek lemma / POS / morph / dep / norm into:
          - custom attrs: ._.gr_*
          - and override Latin .lemma_ and .pos_ for GR tokens.
    """

    greek_spans = []
    current = []

    # 1) Group contiguous GR tokens
    for tok in doc:
        if tok._.tags and "GR" in tok._.tags:
            current.append(tok)
        else:
            if current:
                greek_spans.append(current)
                current = []
    if current:
        greek_spans.append(current)

    if not greek_spans:
        return doc

    # 2) Process each GR span with greek_nlp
    for span_tokens in greek_spans:
        span_start = span_tokens[0].i
        span_end   = span_tokens[-1].i + 1
        span = doc[span_start:span_end]

        gdoc = greek_nlp(span.text)
        g_tokens = list(gdoc)

        # 3) Align by order; guard against length mismatches
        for latin_tok, g_tok in zip(span, g_tokens):
            if not (latin_tok._.tags and "GR" in latin_tok._.tags):
                continue

            latin_tok._.gr_lemma = g_tok.lemma_
            latin_tok._.gr_pos   = g_tok.pos_
            latin_tok._.gr_morph = g_tok.morph.to_dict()
            latin_tok._.gr_dep   = g_tok.dep_
            latin_tok._.gr_norm  = g_tok.norm_

            # override the Latin analysis
            latin_tok.lemma_ = g_tok.lemma_
            latin_tok.pos_   = g_tok.pos_

    return doc


# -------------------------------------------------------------------
# 8. Register components into your existing pipeline
# -------------------------------------------------------------------
if "source_tracker" in tomela.nlp.pipe_names:
    tomela.nlp.remove_pipe("source_tracker")
tomela.nlp.add_pipe("source_tracker", before="senter")

if "blocktype_sentencizer" in tomela.nlp.pipe_names:
    tomela.nlp.remove_pipe("blocktype_sentencizer")
tomela.nlp.add_pipe("blocktype_sentencizer", after="source_tracker")

if "greek_enricher" in tomela.nlp.pipe_names:
    tomela.nlp.remove_pipe("greek_enricher")
tomela.nlp.add_pipe("greek_enricher", last=True)

In [76]:
doc, doc_margins = process_with_source_tracking(textblocks[:20], tomela.nlp)

In [77]:
for t in doc:
    if t._.tags and "GR" in t._.tags:
        print(
            "TAG:",
            repr(t.text),
            "lemma=", t.lemma_,
            "pos=", t.pos_,
            "gr_lemma=", t._.gr_lemma,
            "gr_pos=", t._.gr_pos,
            "tags=", t._.tags,
        )

TAG: 'χιμικωτερα' lemma= χιμικός pos= ADJ gr_lemma= χιμικός gr_pos= ADJ tags= ['GR']
TAG: 'μιγμα' lemma= μιγμα pos= INTJ gr_lemma= μιγμα gr_pos= INTJ tags= ['GR']
TAG: 'πανσπερμια' lemma= πανσπερμια pos= INTJ gr_lemma= πανσπερμια gr_pos= INTJ tags= ['GR']
TAG: 'σκευασται' lemma= σκευαά pos= NOUN gr_lemma= σκευαά gr_pos= NOUN tags= ['GR']
TAG: 'και' lemma= και pos= NOUN gr_lemma= και gr_pos= NOUN tags= ['GR']
TAG: 'πυροτεηνιαν' lemma= πυροτεηνιανή pos= NOUN gr_lemma= πυροτεηνιανή gr_pos= NOUN tags= ['GR']
TAG: 'κακοηθειαν' lemma= κακοήθειος pos= ADJ gr_lemma= κακοήθειος gr_pos= ADJ tags= ['GR']

In [78]:
for sent in doc_margins.sents:
    print(sent.text)

In specie tot medicorum hodie sectae, ut uideantur innumerabila, genere ad tres classes reduci possunt.
Galenici ingenui.
Chymiatri uulgares seu simplices.
Chymiatri hermetici.
Chymiatri.
sophistici, non parum paracelsici, licet hoc nomen auersentur.
Talis fuit Assyluanus.
Paracelsici.
Hemiparacelsici.
Heloparacelsici.
Acto. 7. 22.
i.
metaph.
iux. 19.
Pag. 65.
apol.
pro Hipp.
Iulius Firmicus.
Albucasis Mesues ex regum Damascifamilia plaerumque uixisse.
narratur circa annum 155.
& 1158.
AliGodefrido Coatanem faciunt an.
1099.
Alchymia, aetate Mesue celebris cum suis artificibus.
Uidec. 8. 4.
Tamarindis.
c. 10.
de rosis c. 12 simp.
de absinth.
ubi Marini annotatio Chymicis honorifica.c. 14.
de fumaria.
c. 1 lib. 1.
de med.
laboriose soluentibus Item c. 3. 7. 9.
Ii. 13. 14. 22.
etc.
Albert.
Magnus.
Thom.
de Aquin.
Arnold.
de Uilla noua, Reimundus Lullius.
Auicennos Ita Ualescus de Taranta, qui scripsit an.
Ch. 1418.
fuisset prior Auicenna, etc Auicenna, Auerrhoes, Abenzoar, an. 1149.
tempore Conradi, Imp.
alias dicuntur floruisse.
Theoph.
Paracelsus.
Paracelsus in ueterum medicinam, Chymiam, Physicam, etc.
Duriter animaduertit.
Paracelsicus Galenicum se professus.
Alchymia an ars uel scientia.
Distillatores.
sione unitatis, qut detractione mutantur.
Nota errant illi, qui chymiam dicunt artem medicinam faciendi, hoc est, elixyr illud suum, transmutatione tamen metallica damnata.
Ex parte enim in sufficientem dant definitionem:
ex parte tropo peccant:
aliqua etiam falsum statuunt de medicina chymicorum antiquorum.
Chymica remedia an a Diabolo inuenta.
Pac. 9.
apolpro Hipp.

In [79]:
def doc_to_sent_dicts(doc, work_id):
    """
    Convert a spaCy Doc into the final v2 JSON sentence structure.
    Includes Greek overrides, lemma fallback, and full metadata.
    """

    sent_dicts = []

    for sent_id, sent in enumerate(doc.sents):

        sent_tokens = []
        sent_start = sent.start_char

        for t in sent:

            # --- Greek override ---
            if t._.tags and "GR" in t._.tags:
                lemma = t._.gr_lemma or t.lemma_
                pos   = t._.gr_pos   or t.pos_
            else:
                lemma = t.lemma_
                pos   = t.pos_

            # lemma fallback
            if not lemma:
                lemma = t.text

            # dict representation
            tok_dict = {
                "token_text": t.text,
                "lemma": lemma,
                "pos": pos,
                "ref": {
                    "page": t._.pages,
                    "textblock": t._.textblocks,
                    "tags": t._.tags,
                    "blocktype": t._.block_type,
                },
                "char_start": t.idx - sent_start,
                "char_end": (t.idx - sent_start) + len(t),
            }

            sent_tokens.append(tok_dict)

        # whole sentence
        sent_dict = {
            "work_id": work_id,
            "sent_id": sent_id,
            "sent_text": sent.text,
            "tokens_data": sent_tokens,
        }

        sent_dicts.append(sent_dict)

    return sent_dicts

In [82]:
work_id = filename[:6]
sent_dicts = doc_to_sent_dicts(doc, work_id)
sent_dicts_margins = doc_to_sent_dicts(doc_margins, work_id)

In [49]:
sent_dicts_margins[:5]

[{'work_id': '100085',
  'sent_id': 0,
  'sent_text': 'In specie tot medicorum hodie sectae, ut uideantur innumerabila, genere ad tres classes reduci possunt.',
  'tokens_data': [{'token_text': 'In',
    'lemma': 'in',
    'pos': 'ADP',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 2},
   {'token_text': 'specie',
    'lemma': 'species',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 3,
    'char_end': 9},
   {'token_text': 'tot',
    'lemma': 'tot',
    'pos': 'DET',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 13},
   {'token_text': 'medicorum',
    'lemma': 'medicus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [1],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 14,
    'char_end': 23},
   {'token_text': 'hodie',
    'lemma': 'hodie',
    'pos': 'ADV',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 24,
    'char_end': 29},
   {'token_text': 'sectae',
    'lemma': 'secta',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 30,
    'char_end': 36},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 36,
    'char_end': 37},
   {'token_text': 'ut',
    'lemma': 'ut',
    'pos': 'SCONJ',
    'ref': {'page': [4],
     'textblock': [3],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 38,
    'char_end': 40},
   {'token_text': 'uideantur',
    'lemma': 'uideo',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [3, 4],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 41,
    'char_end': 50},
   {'token_text': 'innumerabila',
    'lemma': 'innumerabilum',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [4, 5],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 51,
    'char_end': 63},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [5],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 63,
    'char_end': 64},
   {'token_text': 'genere',
    'lemma': 'genus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [5, 6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 65,
    'char_end': 71},
   {'token_text': 'ad',
    'lemma': 'ad',
    'pos': 'ADP',
    'ref': {'page': [4],
     'textblock': [6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 72,
    'char_end': 74},
   {'token_text': 'tres',
    'lemma': 'tres',
    'pos': 'NUM',
    'ref': {'page': [4],
     'textblock': [6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 75,
    'char_end': 79},
   {'token_text': 'classes',
    'lemma': 'classis',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [7],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 80,
    'char_end': 87},
   {'token_text': 'reduci',
    'lemma': 'reduco',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [7],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 88,
    'char_end': 94},
   {'token_text': 'possunt',
    'lemma': 'possum',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [8],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 95,
    'char_end': 102},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [8],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 102,
    'char_end': 103}]},
 {'work_id': '100085',
  'sent_id': 1,
  'sent_text': 'Galenici ingenui.',
  'tokens_data': [{'token_text': 'Galenici',
    'lemma': 'galenicus',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [9],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 8},
   {'token_text': 'ingenui',
    'lemma': 'ingigno',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [9, 10],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 9,
    'char_end': 16},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [10],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 16,
    'char_end': 17}]},
 {'work_id': '100085',
  'sent_id': 2,
  'sent_text': 'Chymiatri uulgares seu simplices.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'PROPN',
    'ref': {'page': [4],
     'textblock': [11],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9},
   {'token_text': 'uulgares',
    'lemma': 'uulgaris',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [12],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 18},
   {'token_text': 'seu',
    'lemma': 'seu',
    'pos': 'CCONJ',
    'ref': {'page': [4],
     'textblock': [12],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 19,
    'char_end': 22},
   {'token_text': 'simplices',
    'lemma': 'simplex',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [13],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 23,
    'char_end': 32},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [13],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 32,
    'char_end': 33}]},
 {'work_id': '100085',
  'sent_id': 3,
  'sent_text': 'Chymiatri hermetici.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [14],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9},
   {'token_text': 'hermetici',
    'lemma': 'hermeticus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [15],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 19},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [15],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 19,
    'char_end': 20}]},
 {'work_id': '100085',
  'sent_id': 4,
  'sent_text': 'Chymiatri.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [16],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [16],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 9,
    'char_end': 10}]}]

In [54]:
def get_token_coordinates(token, textblocks):
    """
    Returns the coordinates (x0, y0, x1, y1) of the ORIGINAL OCR textblock
    that produced the token.

    token.ref MUST contain:
        - "page": [int]
        - "textblock": [int]
    """

    ref = token["ref"]
    if ref is None:
        return None

    page_list = ref.get("page")
    tb_list = ref.get("textblock")

    if not page_list or not tb_list:
        return None

    page_idx = page_list[0]
    tb_idx = tb_list[0]

    try:
        tb = textblocks[page_idx][tb_idx]
        return tb["coordinates"]
    except Exception as e:
        print("Coordinate lookup failed:", e)
        return None

def attach_coordinates_to_sent_dicts(sent_dicts, textblocks):
    for sent in sent_dicts:
        for tok in sent["tokens_data"]:
            tok["coordinates"] = get_token_coordinates(tok, textblocks)
    return sent_dicts

In [55]:
sent_dicts_with_coords = attach_coordinates_to_sent_dicts(sent_dicts, textblocks)
sent_dicts_margins_with_coords = attach_coordinates_to_sent_dicts(sent_dicts_margins, textblocks)

In [ ]:
textblocks_unheadered = []
for p in textblocks:
    p_unheadered = []
    header_met = False
    for textblock in p:
        if textblock["tag"] == "header":
            if header_met:
                textblock["tag"] = "text"
            else:
                header_met = True
        p_unheadered.append(textblock)
    textblocks_unheadered.append(p_unheadered)
textblocks = textblocks_unheadered

In [63]:
[textblock for textblock in textblocks[4] if textblock["tag"] in ["header", "title", "text"]]

[{'coordinates': [752.6400146484375,
   171.59994506835938,
   1860.423095703125,
   176.3999481201172],
  'text': 'EPISTOLA DEDICATORIA.\n',
  'tag': 'header'},
 {'coordinates': [420.0,
   255.35995483398438,
   2208.9599609375,
   260.1599426269531],
  'text': 'test ex sequentibus intelligi. Triplex hodiè est medicinae docendae, facien¬\n',
  'tag': 'header'},
 {'coordinates': [424.79998779296875,
   334.7998962402344,
   2193.759765625,
   339.5998840332031],
  'text': 'daeque & ratio & familia. Primam appellant sectam dogmaticorum &\n',
  'tag': 'text'},
 {'coordinates': [420.0,
   408.9839172363281,
   2192.752685546875,
   413.9039306640625],
  'text': 'rationalium, cuius professores ab Hippocrate & Galeno Hippocratici &\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   490.5599060058594,
   2202.1669921875,
   495.3598937988281],
  'text': 'Galenici nuncupantur, quia potissmum, istorum, instituta sequuntur.\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   570.0000610351562,
   2196.081298828125,
   574.8001098632812],
  'text': 'Quidam adijciunt & Arabum doctrinam, quanquam non omnem, &\n',
  'tag': 'text'},
 {'coordinates': [432.0,
   641.5440063476562,
   2211.814208984375,
   646.4639892578125],
  'text': 'sic in diuersas factiones etiam alias hoc genus diuiditur, ex quibus quaedam\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   720.4800415039062,
   2209.98095703125,
   725.2800903320312],
  'text': 'etiam Galeni placitis non omnino acquiescunt. Sed hoc palam est. Iuxta\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   796.0798950195312,
   2222.36669921875,
   800.8799438476562],
  'text': 'praesentem considerationem, Galenici sunt duplices: Quidam seruiles, qui\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   875.0640258789062,
   2205.964599609375,
   879.9840087890625],
  'text': 'nihil ne latum quidem vnguem à dogmatibus Galeni sibi discedendum\n',
  'tag': 'text'},
 {'coordinates': [439.44000244140625,
   951.8399047851562,
   2202.39013671875,
   956.6399536132812],
  'text': 'putant. Quidam nullius adicti iurare in verba magistri, liberalem,\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   1031.06396484375,
   2210.219970703125,
   1035.9840087890625],
  'text': 'amplectuntur disciplinam, & ingenuè in medicina versantur, ausi vel\n',
  'tag': 'text'},
 {'coordinates': [424.79998779296875,
   1106.6400146484375,
   2206.9443359375,
   1111.43994140625],
  'text': 'ipsum Galenum reprehendere & Hippocratem sicubi à vero discedunt.\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   1181.2801513671875,
   2210.017822265625,
   1186.080078125],
  'text': 'Manent tamen intra veterum praeceptorum scholae Galenicae septa, ean¬\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   1258.5599365234375,
   2212.02001953125,
   1263.35986328125],
  'text': 'demque medendi tenent consuetudinem. Quidam nomen & famam\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1333.2000732421875,
   2217.2958984375,
   1338.0],
  'text': 'Logempiriae aucupantur, cum priores dogmatici vel rationales solum¬\n',
  'tag': 'text'},
 {'coordinates': [408.4800109863281,
   1417.4400634765625,
   2208.65234375,
   1422.239990234375],
  'text': 'modo audire velint. Secundum medicorum genus est CHVMIATRO¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 1490.6640625, 2198.62841796875, 1495.5841064453125],
  'text': 'RUM, qui veterum methodo adiecerunt pharmaceuticen chymicam, &\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1565.2801513671875,
   2205.05126953125,
   1570.080078125],
  'text': 'non tantum vulgariter praeparatis vtuntur medicamentis verum et¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 1642.583984375, 2213.14990234375, 1647.5040283203125],
  'text': 'iam ex Alchymia petitis. In hac classe excellunt prisci illi Arabes & Sa¬\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1717.9200439453125,
   2213.10595703125,
   1722.719970703125],
  'text': 'raceni, Auicenna, Mesue, Rhases, Bulcasis, & alij, quos secuti sunt re¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1798.7999267578125,
   2210.601806640625,
   1803.599853515625],
  'text': 'centium plurimi, Albertus, Arnoldus, Lullius, Vlstadius, & omnino\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   1873.703857421875,
   2211.7900390625,
   1878.6239013671875],
  'text': 'innumerabiles: Ex quibus aliqui simpliciter & vulgari consuetoque Ga¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   1950.0,
   2209.206787109375,
   1954.7999267578125],
  'text': 'lenicis sermone disserunt de medicinae regulis, in chymicis saltem chy¬\n',
  'tag': 'text'},
 {'coordinates': [437.0400085449219,
   2027.52001953125,
   2218.730712890625,
   2032.3199462890625],
  'text': 'mica proferentes: Nonnulli ad dogmata prisca accommodant discipli¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2104.079833984375,
   2208.762451171875,
   2108.8798828125],
  'text': 'nam chymicam, & quod Galenici vulgares suae scholae verbis enunci¬\n',
  'tag': 'text'},
 {'coordinates': [432.0,
   2183.760009765625,
   2214.954833984375,
   2188.56005859375],
  'text': 'ant, id hi chymicè vel macrocosmicè expediunt, vtrobique tamen eodem\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2261.06396484375,
   2207.695068359375,
   2265.98388671875],
  'text': 'circa catholica praecepta necessariamque scientiam, & praxin sensu.\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   2337.840087890625,
   2214.621826171875,
   2342.64013671875],
  'text': 'Hi parabolici & Hermetici dici consueuerunt, aut genuine chymiatri.\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2415.119873046875,
   2220.51904296875,
   2419.919921875],
  'text': 'Sed sunt & alij sophistici, qui, cùm aliqua consentiant cum veterum\n',
  'tag': 'text'},
 {'coordinates': [437.0400085449219,
   2493.840087890625,
   2209.309326171875,
   2498.64013671875],
  'text': 'Hippocratica schola, multa immiscent praua, & sophisticis opinionibus,\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2567.5439453125, 2204.443603515625, 2572.4638671875],
  'text': 'chymicorum more enuntiatis, multas excitant turbas, nec patiuntur cae¬\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   2645.999755859375,
   2223.29638671875,
   2650.7998046875],
  'text': 'teros prae se quid sapere, siue verba spectes siue sententias, siue facta, quae\n',
  'tag': 'text'},
 {'coordinates': [444.239990234375,
   2723.999755859375,
   2208.225341796875,
   2728.7998046875],
  'text': 'praedicant ingentia. Hostes hi sunt Galenicorum, potissimum eorum,\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2799.119873046875, 1967.80810546875, 2803.919921875],
  'text': 'qui rigidius & pertinacius adhaerent magistri Galeni dictatis.\n',
  'tag': 'text'},
 {'coordinates': [563.280029296875,
   2878.079833984375,
   2214.97705078125,
   2882.8798828125],
  'text': 'Tertia factio est PARACELSISTARVM ab autore Paracelso, quon¬\n',
  'tag': 'text'},
 {'coordinates': [432.0, 2953.919921875, 2212.4072265625, 2958.719970703125],
  'text': 'dam Galenicae & Arabum disciplinae addicto, chymicoque non indocto\n',
  'tag': 'text'},
 {'coordinates': [434.6400146484375,
   3030.719970703125,
   2208.04736328125,
   3035.52001953125],
  'text': 'nec imperito, sed qui propriantandem sectam condidit coaceruatis ex omni¬\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3107.280029296875,
   2206.38671875,
   3112.080078125],
  'text': 'paradoxorum absurdorumque & deliramentorum angulo portentis, quae\n',
  'tag': 'text'},
 {'coordinates': [424.79998779296875,
   3183.864013671875,
   2214.892822265625,
   3188.783935546875],
  'text': 'fucato quodam colore inducta studuit verisimilia reddere. Statim hoc\n',
  'tag': 'text'},
 {'coordinates': [429.6000061035156,
   3259.679931640625,
   2208.2880859375,
   3264.47998046875],
  'text': 'genus in duos diuulsum est greges. Nam cum nouitas quidem arrideret\n',
  'tag': 'text'},
 {'coordinates': [473.2799987792969,
   3337.919921875,
   2205.98486328125,
   3342.719970703125],
  'text': '& in insolitas quasdam spes, consiliaque plurium excitaret pelliceretque\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3416.8798828125,
   2204.18701171875,
   3421.679931640625],
  'text': 'animos; tamen magian impiam, & affinia deliramenta pauci sunt\n',
  'tag': 'text'},
 {'coordinates': [427.20001220703125,
   3492.0,
   660.1680908203125,
   3496.800048828125],
  'text': 'amplexi.\n',
  'tag': 'text'}]

In [60]:
[sent["sent_text"] for sent in sent_dicts_with_coords if sent["tokens_data"][-1]["ref"]["page"][-1]==4]

['Ego uero nec Quercetanum in magna dignitate apud Gallorum regem constitutum, medicumque & philosophum parabolicum quidem, sed minime stultum aut indoctum, id quod in publicum edita scripta, & plurium doctorum testimonia hactenus comprobarunt, meo calculo ausim aut uelim de gradum deiicere, nec eius medicinam & physiologiam, licet non undiquaque ad sensus meos compositam, contumelia aut dedecore afficere, cuius consilii ratio non obscure podaeque & ratio & familia.',
 'Primam appellant sectam dogmaticorum & rationalium, cuius professores ab Hippocrate & Galeno Hippocratici & Galenici nuncupantur, quia potissmum, istorum, instituta sequuntur.',
 'Quidam adiiciunt & Arabum doctrinam, quanquam non omnem, & sic in diuersas factiones etiam alias hoc genus diuiditur, ex quibus quaedam etiam Galeni placitis non omnino acquiescunt.',
 'Sed hoc palam est.',
 'Iuxta praesentem considerationem, Galenici sunt duplices:',
 'Quidam seruiles, qui nihil ne latum quidem unguem a dogmatibus Galeni sibi discedendum putant.',
 'Quidam nullius adicti iurare in uerba magistri, liberalem, amplectuntur disciplinam, & ingenue in medicina uersantur, ausi uel ipsum Galenum reprehendere & Hippocratem sicubi a uero discedunt.',
 'Manent tamen intra ueterum praeceptorum scholae Galenicae septa, eandemque medendi tenent consuetudinem.',
 'Quidam nomen & famam Logempiriae aucupantur, cum priores dogmatici uel rationales solummodo audire uelint.',
 'Secundum medicorum genus est ChumiatroRum, qui ueterum methodo adiecerunt pharmaceuticen chymicam, & non tantum uulgariter praeparatis utuntur medicamentis uerum etiam ex Alchymia petitis.',
 'In hac classe excellunt prisci illi Arabes & Saraceni, Auicenna, Mesue, Rhases, Bulcasis, & alii, quos secuti sunt recentium plurimi, Albertus, Arnoldus, Lullius, Ulstadius, & omnino innumerabiles:',
 'Ex quibus aliqui simpliciter & uulgari consuetoque Galenicis sermone disserunt de medicinae regulis, in chymicis saltem chymica proferentes:',
 'Nonnulli ad dogmata prisca accommodant disciplinam chymicam, & quod Galenici uulgares suae scholae uerbis enunciant, id hi chymice uel macrocosmice expediunt, utrobique tamen eodem circa catholica praecepta necessariamque scientiam, & praxin sensu.',
 'Hi parabolici & Hermetici dici consueuerunt, aut genuine chymiatri.',
 'Sed sunt & alii sophistici, qui, cum aliqua consentiant cum ueterum Hippocratica schola, multa immiscent praua, & sophisticis opinionibus, chymicorum more enuntiatis, multas excitant turbas, nec patiuntur caeteros prae se quid sapere, siue uerba spectes siue sententias, siue facta, quae praedicant ingentia.',
 'Hostes hi sunt Galenicorum, potissimum eorum, qui rigidius & pertinacius adhaerent magistri Galeni dictatis.',
 'Tertia factio est Paracelsistarum ab autore Paracelso, quondam Galenicae & Arabum disciplinae addicto, chymicoque non indocto nec imperito, sed qui propriantandem sectam condidit coaceruatis ex omniparadoxorum absurdorumque & deliramentorum angulo portentis, quae fucato quodam colore inducta studuit uerisimilia reddere.',
 'Statim hoc genus in duos diuulsum est greges.',
 'Nam cum nouitas quidem arrideret & in insolitas quasdam spes, consiliaque plurium excitaret pelliceretque animos;',
 'tamen magian impiam, & affinia deliramenta pauci sunt amplexi.']

In [57]:
sent_dicts_margins_with_coords[:5]

[{'work_id': '100085',
  'sent_id': 0,
  'sent_text': 'In specie tot medicorum hodie sectae, ut uideantur innumerabila, genere ad tres classes reduci possunt.',
  'tokens_data': [{'token_text': 'In',
    'lemma': 'in',
    'pos': 'ADP',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 2,
    'coordinates': [235.44000244140625,
     684.7200317382812,
     409.4384460449219,
     689.5200805664062]},
   {'token_text': 'specie',
    'lemma': 'species',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 3,
    'char_end': 9,
    'coordinates': [235.44000244140625,
     684.7200317382812,
     409.4384460449219,
     689.5200805664062]},
   {'token_text': 'tot',
    'lemma': 'tot',
    'pos': 'DET',
    'ref': {'page': [4],
     'textblock': [0],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 13,
    'coordinates': [235.44000244140625,
     684.7200317382812,
     409.4384460449219,
     689.5200805664062]},
   {'token_text': 'medicorum',
    'lemma': 'medicus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [1],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 14,
    'char_end': 23,
    'coordinates': [235.44000244140625,
     725.0398559570312,
     410.12158203125,
     729.8399047851562]},
   {'token_text': 'hodie',
    'lemma': 'hodie',
    'pos': 'ADV',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 24,
    'char_end': 29,
    'coordinates': [235.44000244140625,
     765.8640747070312,
     409.9117736816406,
     770.7840576171875]},
   {'token_text': 'sectae',
    'lemma': 'secta',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 30,
    'char_end': 36,
    'coordinates': [235.44000244140625,
     765.8640747070312,
     409.9117736816406,
     770.7840576171875]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [2],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 36,
    'char_end': 37,
    'coordinates': [235.44000244140625,
     765.8640747070312,
     409.9117736816406,
     770.7840576171875]},
   {'token_text': 'ut',
    'lemma': 'ut',
    'pos': 'SCONJ',
    'ref': {'page': [4],
     'textblock': [3],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 38,
    'char_end': 40,
    'coordinates': [240.24000549316406,
     806.3999633789062,
     399.8396301269531,
     811.2000122070312]},
   {'token_text': 'uideantur',
    'lemma': 'uideo',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [3, 4],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 41,
    'char_end': 50,
    'coordinates': [240.24000549316406,
     806.3999633789062,
     399.8396301269531,
     811.2000122070312]},
   {'token_text': 'innumerabila',
    'lemma': 'innumerabilum',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [4, 5],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 51,
    'char_end': 63,
    'coordinates': [237.83999633789062,
     846.2639770507812,
     409.64459228515625,
     851.1839599609375]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [5],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 63,
    'char_end': 64,
    'coordinates': [237.83999633789062,
     885.8640747070312,
     410.22802734375,
     890.7840576171875]},
   {'token_text': 'genere',
    'lemma': 'genus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [5, 6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 65,
    'char_end': 71,
    'coordinates': [237.83999633789062,
     885.8640747070312,
     410.22802734375,
     890.7840576171875]},
   {'token_text': 'ad',
    'lemma': 'ad',
    'pos': 'ADP',
    'ref': {'page': [4],
     'textblock': [6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 72,
    'char_end': 74,
    'coordinates': [237.83999633789062,
     929.0398559570312,
     394.5736389160156,
     933.8399047851562]},
   {'token_text': 'tres',
    'lemma': 'tres',
    'pos': 'NUM',
    'ref': {'page': [4],
     'textblock': [6],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 75,
    'char_end': 79,
    'coordinates': [237.83999633789062,
     929.0398559570312,
     394.5736389160156,
     933.8399047851562]},
   {'token_text': 'classes',
    'lemma': 'classis',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [7],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 80,
    'char_end': 87,
    'coordinates': [240.24000549316406,
     969.8399047851562,
     409.71844482421875,
     974.6399536132812]},
   {'token_text': 'reduci',
    'lemma': 'reduco',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [7],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 88,
    'char_end': 94,
    'coordinates': [240.24000549316406,
     969.8399047851562,
     409.71844482421875,
     974.6399536132812]},
   {'token_text': 'possunt',
    'lemma': 'possum',
    'pos': 'VERB',
    'ref': {'page': [4],
     'textblock': [8],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 95,
    'char_end': 102,
    'coordinates': [235.44000244140625,
     1013.5200805664062,
     369.552001953125,
     1018.3201293945312]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [8],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 102,
    'char_end': 103,
    'coordinates': [235.44000244140625,
     1013.5200805664062,
     369.552001953125,
     1018.3201293945312]}]},
 {'work_id': '100085',
  'sent_id': 1,
  'sent_text': 'Galenici ingenui.',
  'tokens_data': [{'token_text': 'Galenici',
    'lemma': 'galenicus',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [9],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 8,
    'coordinates': [242.8800048828125,
     1045.4400634765625,
     409.9608154296875,
     1050.239990234375]},
   {'token_text': 'ingenui',
    'lemma': 'ingigno',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [9, 10],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 9,
    'char_end': 16,
    'coordinates': [242.8800048828125,
     1045.4400634765625,
     409.9608154296875,
     1050.239990234375]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [10],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 16,
    'char_end': 17,
    'coordinates': [240.24000549316406,
     1094.4000244140625,
     343.356201171875,
     1099.199951171875]}]},
 {'work_id': '100085',
  'sent_id': 2,
  'sent_text': 'Chymiatri uulgares seu simplices.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'PROPN',
    'ref': {'page': [4],
     'textblock': [11],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [245.27999877929688,
     1392.02392578125,
     410.1197204589844,
     1396.9439697265625]},
   {'token_text': 'uulgares',
    'lemma': 'uulgaris',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [12],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 18,
    'coordinates': [247.67999267578125,
     1429.6800537109375,
     410.7650451660156,
     1434.47998046875]},
   {'token_text': 'seu',
    'lemma': 'seu',
    'pos': 'CCONJ',
    'ref': {'page': [4],
     'textblock': [12],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 19,
    'char_end': 22,
    'coordinates': [247.67999267578125,
     1429.6800537109375,
     410.7650451660156,
     1434.47998046875]},
   {'token_text': 'simplices',
    'lemma': 'simplex',
    'pos': 'ADJ',
    'ref': {'page': [4],
     'textblock': [13],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 23,
    'char_end': 32,
    'coordinates': [237.83999633789062,
     1477.9200439453125,
     390.0096435546875,
     1482.719970703125]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [13],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 32,
    'char_end': 33,
    'coordinates': [237.83999633789062,
     1477.9200439453125,
     390.0096435546875,
     1482.719970703125]}]},
 {'work_id': '100085',
  'sent_id': 3,
  'sent_text': 'Chymiatri hermetici.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [14],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [250.0800018310547,
     2001.5999755859375,
     409.78240966796875,
     2006.39990234375]},
   {'token_text': 'hermetici',
    'lemma': 'hermeticus',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [15],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 10,
    'char_end': 19,
    'coordinates': [245.27999877929688,
     2045.2801513671875,
     404.2020263671875,
     2050.080078125]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [15],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 19,
    'char_end': 20,
    'coordinates': [245.27999877929688,
     2045.2801513671875,
     404.2020263671875,
     2050.080078125]}]},
 {'work_id': '100085',
  'sent_id': 4,
  'sent_text': 'Chymiatri.',
  'tokens_data': [{'token_text': 'Chymiatri',
    'lemma': 'Chymiater',
    'pos': 'NOUN',
    'ref': {'page': [4],
     'textblock': [16],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [250.0800018310547,
     2377.199951171875,
     408.7648010253906,
     2382.0]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [4],
     'textblock': [16],
     'tags': None,
     'blocktype': 'margin'},
    'char_start': 9,
    'char_end': 10,
    'coordinates': [250.0800018310547,
     2377.199951171875,
     408.7648010253906,
     2382.0]}]}]

In [52]:
for sent in sent_dicts_margins[:3]:
    print(f"SENT #{sent['sent_id']}: {sent['sent_text']}")
    for tok in sent["tokens_data"]:
        coords = get_token_coordinates(tok, textblocks)
        print("  ", tok["token_text"], coords)

SENT #0: In specie tot medicorum hodie sectae, ut uideantur innumerabila, genere ad tres classes reduci possunt.
   In [235.44000244140625, 684.7200317382812, 409.4384460449219, 689.5200805664062]
   specie [235.44000244140625, 684.7200317382812, 409.4384460449219, 689.5200805664062]
   tot [235.44000244140625, 684.7200317382812, 409.4384460449219, 689.5200805664062]
   medicorum [235.44000244140625, 725.0398559570312, 410.12158203125, 729.8399047851562]
   hodie [235.44000244140625, 765.8640747070312, 409.9117736816406, 770.7840576171875]
   sectae [235.44000244140625, 765.8640747070312, 409.9117736816406, 770.7840576171875]
   , [235.44000244140625, 765.8640747070312, 409.9117736816406, 770.7840576171875]
   ut [240.24000549316406, 806.3999633789062, 399.8396301269531, 811.2000122070312]
   uideantur [240.24000549316406, 806.3999633789062, 399.8396301269531, 811.2000122070312]
   innumerabila [237.83999633789062, 846.2639770507812, 409.64459228515625, 851.1839599609375]
   , [237.83999633789062, 885.8640747070312, 410.22802734375, 890.7840576171875]
   genere [237.83999633789062, 885.8640747070312, 410.22802734375, 890.7840576171875]
   ad [237.83999633789062, 929.0398559570312, 394.5736389160156, 933.8399047851562]
   tres [237.83999633789062, 929.0398559570312, 394.5736389160156, 933.8399047851562]
   classes [240.24000549316406, 969.8399047851562, 409.71844482421875, 974.6399536132812]
   reduci [240.24000549316406, 969.8399047851562, 409.71844482421875, 974.6399536132812]
   possunt [235.44000244140625, 1013.5200805664062, 369.552001953125, 1018.3201293945312]
   . [235.44000244140625, 1013.5200805664062, 369.552001953125, 1018.3201293945312]
SENT #1: Galenici ingenui.
   Galenici [242.8800048828125, 1045.4400634765625, 409.9608154296875, 1050.239990234375]
   ingenui [242.8800048828125, 1045.4400634765625, 409.9608154296875, 1050.239990234375]
   . [240.24000549316406, 1094.4000244140625, 343.356201171875, 1099.199951171875]
SENT #2: Chymiatri uulgares seu simplices.
   Chymiatri [245.27999877929688, 1392.02392578125, 410.1197204589844, 1396.9439697265625]
   uulgares [247.67999267578125, 1429.6800537109375, 410.7650451660156, 1434.47998046875]
   seu [247.67999267578125, 1429.6800537109375, 410.7650451660156, 1434.47998046875]
   simplices [237.83999633789062, 1477.9200439453125, 390.0096435546875, 1482.719970703125]
   . [237.83999633789062, 1477.9200439453125, 390.0096435546875, 1482.719970703125]

In [113]:
altblocks = []
for n, sent in enumerate(sent_dicts):
    for token in sent["tokens_data"]:
        if token["ref"]["blocktype"] == "margin":
            altblocks.append([sent_dicts[n -1], sent])
            break

In [114]:
len(altblocks)

62

In [115]:
altblocks

[[{'work_id': '100085',
   'sent_id': 28,
   'sent_text': 'Ego uero nec Quercetanum in magna dignitate apud Gallorum regem constitutum, medicumque & philosophum parabolicum quidem, sed minime stultum aut indoctum, id quod in publicum edita scripta, & plurium doctorum testimonia hactenus comprobarunt, meo calculo ausim aut uelim de gradum deiicere, nec eius medicinam & physiologiam, licet non undiquaque ad sensus meos compositam, contumelia aut dedecore afficere, cuius consilii ratio non obscure',
   'tokens_data': [{'token_text': 'Ego',
     'lemma': 'ego',
     'pos': 'PRON',
     'ref': {'page': [3],
      'textblock': [27],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 0,
     'char_end': 3},
    {'token_text': 'uero',
     'lemma': 'uero',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [27],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 4,
     'char_end': 8},
    {'token_text': 'nec',
     'lemma': 'neque',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [27],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 9,
     'char_end': 12},
    {'token_text': 'Quercetanum',
     'lemma': 'quercetanus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [27],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 13,
     'char_end': 24},
    {'token_text': 'in',
     'lemma': 'in',
     'pos': 'ADP',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 25,
     'char_end': 27},
    {'token_text': 'magna',
     'lemma': 'magnus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 28,
     'char_end': 33},
    {'token_text': 'dignitate',
     'lemma': 'dignitas',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 34,
     'char_end': 43},
    {'token_text': 'apud',
     'lemma': 'apud',
     'pos': 'ADP',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 44,
     'char_end': 48},
    {'token_text': 'Gallorum',
     'lemma': 'Galli',
     'pos': 'PROPN',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 49,
     'char_end': 57},
    {'token_text': 'regem',
     'lemma': 'rex',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 58,
     'char_end': 63},
    {'token_text': 'constitutum',
     'lemma': 'constitutum',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 64,
     'char_end': 75},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 75,
     'char_end': 76},
    {'token_text': 'medicum',
     'lemma': 'medicus',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 77,
     'char_end': 84},
    {'token_text': 'que',
     'lemma': 'que',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 84,
     'char_end': 87},
    {'token_text': '&',
     'lemma': '&',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [28],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 88,
     'char_end': 89},
    {'token_text': 'philosophum',
     'lemma': 'philosophus',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 90,
     'char_end': 101},
    {'token_text': 'parabolicum',
     'lemma': 'parabolicus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 102,
     'char_end': 113},
    {'token_text': 'quidem',
     'lemma': 'quidem',
     'pos': 'PART',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 114,
     'char_end': 120},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 120,
     'char_end': 121},
    {'token_text': 'sed',
     'lemma': 'sed',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 122,
     'char_end': 125},
    {'token_text': 'minime',
     'lemma': 'parum',
     'pos': 'ADV',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 126,
     'char_end': 132},
    {'token_text': 'stultum',
     'lemma': 'stultus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 133,
     'char_end': 140},
    {'token_text': 'aut',
     'lemma': 'aut',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 141,
     'char_end': 144},
    {'token_text': 'indoctum',
     'lemma': 'indoctus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 145,
     'char_end': 153},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 153,
     'char_end': 154},
    {'token_text': 'id',
     'lemma': 'is',
     'pos': 'PRON',
     'ref': {'page': [3],
      'textblock': [29],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 155,
     'char_end': 157},
    {'token_text': 'quod',
     'lemma': 'qui',
     'pos': 'PRON',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 158,
     'char_end': 162},
    {'token_text': 'in',
     'lemma': 'in',
     'pos': 'ADP',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 163,
     'char_end': 165},
    {'token_text': 'publicum',
     'lemma': 'publicum',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 166,
     'char_end': 174},
    {'token_text': 'edita',
     'lemma': 'edo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 175,
     'char_end': 180},
    {'token_text': 'scripta',
     'lemma': 'scribo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 181,
     'char_end': 188},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 188,
     'char_end': 189},
    {'token_text': '&',
     'lemma': '&',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 190,
     'char_end': 191},
    {'token_text': 'plurium',
     'lemma': 'plus',
     'pos': 'DET',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 192,
     'char_end': 199},
    {'token_text': 'doctorum',
     'lemma': 'doceo',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 200,
     'char_end': 208},
    {'token_text': 'testimonia',
     'lemma': 'testimonium',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 209,
     'char_end': 219},
    {'token_text': 'hactenus',
     'lemma': 'hactenus',
     'pos': 'ADV',
     'ref': {'page': [3],
      'textblock': [30],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 220,
     'char_end': 228},
    {'token_text': 'comprobarunt',
     'lemma': 'comprobo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 229,
     'char_end': 241},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 241,
     'char_end': 242},
    {'token_text': 'meo',
     'lemma': 'meus',
     'pos': 'DET',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 243,
     'char_end': 246},
    {'token_text': 'calculo',
     'lemma': 'calculo',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 247,
     'char_end': 254},
    {'token_text': 'ausim',
     'lemma': 'audeo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 255,
     'char_end': 260},
    {'token_text': 'aut',
     'lemma': 'aut',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 261,
     'char_end': 264},
    {'token_text': 'uelim',
     'lemma': 'uolo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 265,
     'char_end': 270},
    {'token_text': 'de',
     'lemma': 'de',
     'pos': 'ADP',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 271,
     'char_end': 273},
    {'token_text': 'gradum',
     'lemma': 'gradus',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 274,
     'char_end': 280},
    {'token_text': 'deiicere',
     'lemma': 'deiico',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 281,
     'char_end': 289},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 289,
     'char_end': 290},
    {'token_text': 'nec',
     'lemma': 'neque',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 291,
     'char_end': 294},
    {'token_text': 'eius',
     'lemma': 'is',
     'pos': 'PRON',
     'ref': {'page': [3],
      'textblock': [31],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 295,
     'char_end': 299},
    {'token_text': 'medicinam',
     'lemma': 'medicina',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 300,
     'char_end': 309},
    {'token_text': '&',
     'lemma': '&',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 310,
     'char_end': 311},
    {'token_text': 'physiologiam',
     'lemma': 'physiologia',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 312,
     'char_end': 324},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 324,
     'char_end': 325},
    {'token_text': 'licet',
     'lemma': 'licet',
     'pos': 'SCONJ',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 326,
     'char_end': 331},
    {'token_text': 'non',
     'lemma': 'non',
     'pos': 'PART',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 332,
     'char_end': 335},
    {'token_text': 'undiqua',
     'lemma': 'undiquus',
     'pos': 'ADJ',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 336,
     'char_end': 343},
    {'token_text': 'que',
     'lemma': 'que',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 343,
     'char_end': 346},
    {'token_text': 'ad',
     'lemma': 'ad',
     'pos': 'ADP',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 347,
     'char_end': 349},
    {'token_text': 'sensus',
     'lemma': 'sensus',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 350,
     'char_end': 356},
    {'token_text': 'meos',
     'lemma': 'meus',
     'pos': 'DET',
     'ref': {'page': [3],
      'textblock': [32],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 357,
     'char_end': 361},
    {'token_text': 'compositam',
     'lemma': 'compositus',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [32, 33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 362,
     'char_end': 372},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 372,
     'char_end': 373},
    {'token_text': 'contumelia',
     'lemma': 'contumelia',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 374,
     'char_end': 384},
    {'token_text': 'aut',
     'lemma': 'aut',
     'pos': 'CCONJ',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 385,
     'char_end': 388},
    {'token_text': 'dedecore',
     'lemma': 'dedecus',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 389,
     'char_end': 397},
    {'token_text': 'afficere',
     'lemma': 'afficeo',
     'pos': 'VERB',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 398,
     'char_end': 406},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 406,
     'char_end': 407},
    {'token_text': 'cuius',
     'lemma': 'qui',
     'pos': 'PRON',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 408,
     'char_end': 413},
    {'token_text': 'consilii',
     'lemma': 'consilium',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 414,
     'char_end': 422},
    {'token_text': 'ratio',
     'lemma': 'ratio',
     'pos': 'NOUN',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 423,
     'char_end': 428},
    {'token_text': 'non',
     'lemma': 'non',
     'pos': 'PART',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 429,
     'char_end': 432},
    {'token_text': 'obscure',
     'lemma': 'obscurus',
     'pos': 'ADV',
     'ref': {'page': [3],
      'textblock': [33],
      'tags': None,
      'blocktype': 'text'},
     'char_start': 433,
     'char_end': 440}]},
  {'work_id': '100085',
   'sent_id': 29,
   'sent_text': 'poIn specie tot medicorum hodie sectae, ut uideantur innumerabila, genere ad tres classes reduci possunt.',
   'tokens_data': [{'token_text': 'poIn',
     'lemma': 'poIn',
     'pos': 'NOUN',
     'ref': {'page': [3, 4],
      'textblock': [0, 33],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 0,
     'char_end': 4},
    {'token_text': 'specie',
     'lemma': 'species',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [0],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 5,
     'char_end': 11},
    {'token_text': 'tot',
     'lemma': 'tot',
     'pos': 'DET',
     'ref': {'page': [4],
      'textblock': [0],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 12,
     'char_end': 15},
    {'token_text': 'medicorum',
     'lemma': 'medicus',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [1],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 16,
     'char_end': 25},
    {'token_text': 'hodie',
     'lemma': 'hodie',
     'pos': 'ADV',
     'ref': {'page': [4],
      'textblock': [2],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 26,
     'char_end': 31},
    {'token_text': 'sectae',
     'lemma': 'secta',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [2],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 32,
     'char_end': 38},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [4],
      'textblock': [2],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 38,
     'char_end': 39},
    {'token_text': 'ut',
     'lemma': 'ut',
     'pos': 'SCONJ',
     'ref': {'page': [4],
      'textblock': [3],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 40,
     'char_end': 42},
    {'token_text': 'uideantur',
     'lemma': 'uideo',
     'pos': 'VERB',
     'ref': {'page': [4],
      'textblock': [3, 4],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 43,
     'char_end': 52},
    {'token_text': 'innumerabila',
     'lemma': 'innumerabilum',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [4, 5],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 53,
     'char_end': 65},
    {'token_text': ',',
     'lemma': ',',
     'pos': 'PUNCT',
     'ref': {'page': [4],
      'textblock': [5],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 65,
     'char_end': 66},
    {'token_text': 'genere',
     'lemma': 'genus',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [5, 6],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 67,
     'char_end': 73},
    {'token_text': 'ad',
     'lemma': 'ad',
     'pos': 'ADP',
     'ref': {'page': [4],
      'textblock': [6],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 74,
     'char_end': 76},
    {'token_text': 'tres',
     'lemma': 'tres',
     'pos': 'NUM',
     'ref': {'page': [4],
      'textblock': [6],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 77,
     'char_end': 81},
    {'token_text': 'classes',
     'lemma': 'classis',
     'pos': 'NOUN',
     'ref': {'page': [4],
      'textblock': [7],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 82,
     'char_end': 89},
    {'token_text': 'reduci',
     'lemma': 'reduco',
     'pos': 'VERB',
     'ref': {'page': [4],
      'textblock': [7],
      'tags': None,
      'blocktype': 'margin'},
     'char_start': 90,
     'char_end': 96},

In [107]:
def process_file_to_v2_json(filepath, work_id, outpath, nlp):
    """
    Load OCR textblocks → build Doc → convert to v2 sentence dicts → write JSON.
    """

    # Load textblocks
    with open(filepath, 'r', encoding='utf-8') as f:
        textblocks_pages = json.load(f)

    # Build annotated doc
    doc = process_with_source_tracking(textblocks_pages, nlp)

    # Convert doc to sentence dictionaries
    sent_dicts = doc_to_sent_dicts(doc, work_id)

    # Write JSON
    with open(outpath, "w", encoding="utf-8") as f:
        json.dump(sent_dicts, f, ensure_ascii=False, indent=2)

In [ ]:
source_path = "../data/emlap_annotated_textblocks/"
target_path = "../data/sents_data_jsons_dicts/"
os.makedirs(target_path, exist_ok=True)

for filename in os.listdir(source_path):

    if not filename.endswith(".json"):      # textblocks files
        continue

    work_id = filename[:6]
    outpath = os.path.join(target_path, f"{work_id}.json")

    # Skip if already processed
    if os.path.exists(outpath):
        continue

    filepath = os.path.join(source_path, filename)
    print("Processing", filename)

    try:
        process_file_to_v2_json(
            filepath=filepath,
            work_id=work_id,
            outpath=outpath,
            nlp=tomela.nlp
        )
    except Exception as e:
        print("FAILED:", filename, "→", e)

In [98]:
sent_data_updated[100:120]

[('100085',
  100,
  'Non alium liquorem uesica reddunt.',
  [('Non',
    'non',
    'PART',
    (0, 3),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('alium',
    'alius',
    'DET',
    (4, 9),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('liquorem',
    'liquor',
    'NOUN',
    (10, 18),
    {'page': [7], 'texblock': [23], 'tags': None, 'blocktype': 'text'}),
   ('uesica',
    'uesica',
    'NOUN',
    (19, 25),
    {'page': [7], 'texblock': [23, 24], 'tags': None, 'blocktype': 'text'}),
   ('reddunt',
    'reddo',
    'VERB',
    (26, 33),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (33, 34),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  101,
  'Non habent alia membra, quam nos, non sudores alios.',
  [('Non',
    'non',
    'PART',
    (0, 3),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('habent',
    'habeo',
    'VERB',
    (4, 10),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('alia',
    'alius',
    'DET',
    (11, 15),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('membra',
    'membrum',
    'NOUN',
    (16, 22),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (22, 23),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('quam',
    'qui',
    'PRON',
    (24, 28),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (29, 32),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (32, 33),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (34, 37),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('sudores',
    'sudor',
    'NOUN',
    (38, 45),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('alios',
    'alius',
    'DET',
    (46, 51),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (51, 52),
    {'page': [7], 'texblock': [24], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  102,
  'Quo rhabarbaro purgantur ipsi, eodem & nos.',
  [('Quo',
    'quo',
    'SCONJ',
    (0, 3),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('rhabarbaro',
    'rhabarbarum',
    'NOUN',
    (4, 14),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('purgantur',
    'purgo',
    'VERB',
    (15, 24),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ipsi',
    'ipse',
    'DET',
    (25, 29),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (29, 30),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('eodem',
    'idem',
    'ADV',
    (31, 36),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (37, 38),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (39, 42),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (42, 43),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  103,
  'Quod ex ipsis segregatur per sennam idem ex nobis.',
  [('Quod',
    'qui',
    'PRON',
    (0, 4),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ex',
    'ex',
    'ADP',
    (5, 7),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('ipsis',
    'ipse',
    'DET',
    (8, 13),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('segregatur',
    'segrego',
    'VERB',
    (14, 24),
    {'page': [7], 'texblock': [25], 'tags': None, 'blocktype': 'text'}),
   ('per',
    'per',
    'ADP',
    (25, 28),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('sennam',
    'senna',
    'NOUN',
    (29, 35),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('idem',
    'idem',
    'DET',
    (36, 40),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('ex',
    'ex',
    'ADP',
    (41, 43),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('nobis',
    'nos',
    'PRON',
    (44, 49),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (49, 50),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  104,
  'Uulnerati fundunt sanguinem nostro congenerem, qui in pus mutatur eodem modo:',
  [('Uulnerati',
    'uulnerati',
    'VERB',
    (0, 9),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('fundunt',
    'fundo',
    'VERB',
    (10, 17),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('sanguinem',
    'sanguis',
    'NOUN',
    (18, 27),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('nostro',
    'noster',
    'DET',
    (28, 34),
    {'page': [7], 'texblock': [26], 'tags': None, 'blocktype': 'text'}),
   ('congenerem',
    'congenero',
    'NOUN',
    (35, 45),
    {'page': [7], 'texblock': [26, 27], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (45, 46),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (47, 50),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (51, 53),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('pus',
    'pus',
    'NOUN',
    (54, 57),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('mutatur',
    'muto',
    'VERB',
    (58, 65),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('eodem',
    'idem',
    'DET',
    (66, 71),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('modo',
    'modus',
    'NOUN',
    (72, 76),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   (':',
    ':',
    'PUNCT',
    (76, 77),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  105,
  'eadem sanantur Chirurgia.',
  [('eadem',
    'idem',
    'DET',
    (0, 5),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('sanantur',
    'sano',
    'VERB',
    (6, 14),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('Chirurgia',
    'Chirurgia',
    'PROPN',
    (15, 24),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (24, 25),
    {'page': [7], 'texblock': [27], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  106,
  'Et omnino qui nihil non commune secundum naturam nobiscum habent, nisi quod opinionum turba moueantur secus ac nos, indeque phantasmatibus decipiantur & linguam nouis sonis instruant, quid est secundum rei ueritatem, ut a nobis discedant primum, nisi opinio?',
  [('Et',
    'et',
    'CCONJ',
    (0, 2),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('omnino',
    'omnino',
    'ADV',
    (3, 9),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (10, 13),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('nihil',
    'nihil',
    'PRON',
    (14, 19),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (20, 23),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('commune',
    'communis',
    'ADJ',
    (24, 31),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('secundum',
    'secundum',
    'ADP',
    (32, 40),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('naturam',
    'natura',
    'NOUN',
    (41, 48),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('nobiscum',
    'nobiscus',
    'NOUN',
    (49, 57),
    {'page': [7], 'texblock': [28], 'tags': None, 'blocktype': 'text'}),
   ('habent',
    'habeo',
    'VERB',
    (58, 64),
    {'page': [7], 'texblock': [28, 29], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (64, 65),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (66, 70),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('quod',
    'quod',
    'SCONJ',
    (71, 75),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('opinionum',
    'opinio',
    'NOUN',
    (76, 85),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('turba',
    'turba',
    'NOUN',
    (86, 91),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('moueantur',
    'moueo',
    'VERB',
    (92, 101),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('secus',
    'secus',
    'ADV',
    (102, 107),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('ac',
    'ac',
    'CCONJ',
    (108, 110),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('nos',
    'nos',
    'PRON',
    (111, 114),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (114, 115),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('inde',
    'inde',
    'ADV',
    (116, 120),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('que',
    'que',
    'CCONJ',
    (120, 123),
    {'page': [7], 'texblock': [29], 'tags': None, 'blocktype': 'text'}),
   ('phantasmatibus',
    'phantasma',
    'NOUN',
    (124, 138),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('decipiantur',
    'decipio',
    'VERB',
    (139, 150),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (151, 152),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('linguam',
    'lingua',
    'NOUN',
    (153, 160),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('nouis',
    'nouus',
    'ADJ',
    (161, 166),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('sonis',
    'sonus',
    'NOUN',
    (167, 172),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('instruant',
    'instruo',
    'VERB',
    (173, 182),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (182, 183),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('quid',
    'quis',
    'PRON',
    (184, 188),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('est',
    'sum',
    'AUX',
    (189, 192),
    {'page': [7], 'texblock': [30], 'tags': None, 'blocktype': 'text'}),
   ('secundum',
    'secundum',
    'ADP',
    (193, 201),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('rei',
    'res',
    'NOUN',
    (202, 205),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('ueritatem',
    'ueritas',
    'NOUN',
    (206, 215),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (215, 216),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('ut',
    'ut',
    'SCONJ',
    (217, 219),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('a',
    'ab',
    'ADP',
    (220, 221),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('nobis',
    'nos',
    'PRON',
    (222, 227),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('discedant',
    'discedo',
    'VERB',
    (228, 237),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('primum',
    'primum',
    'ADV',
    (238, 244),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (244, 245),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (246, 250),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('opinio',
    'opinio',
    'NOUN',
    (251, 257),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'}),
   ('?',
    '?',
    'PUNCT',
    (257, 258),
    {'page': [7], 'texblock': [31], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  107,
  'Hos qui opinione ducuntur, & in caeteris nihil aliud faciunt aut patiuntur, an non risu, quam acerba insectatione potius dignos iudicem?',
  [('Hos',
    'hic',
    'DET',
    (0, 3),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('qui',
    'qui',
    'PRON',
    (4, 7),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('opinione',
    'opinio',
    'NOUN',
    (8, 16),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('ducuntur',
    'duco',
    'VERB',
    (17, 25),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (25, 26),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (27, 28),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('in',
    'in',
    'ADP',
    (29, 31),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('caeteris',
    'caeterus',
    'ADJ',
    (32, 40),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('nihil',
    'nihil',
    'PRON',
    (41, 46),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('aliud',
    'alius',
    'DET',
    (47, 52),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('faciunt',
    'facio',
    'VERB',
    (53, 60),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('aut',
    'aut',
    'CCONJ',
    (61, 64),
    {'page': [7], 'texblock': [32], 'tags': None, 'blocktype': 'text'}),
   ('patiuntur',
    'patior',
    'VERB',
    (65, 74),
    {'page': [7], 'texblock': [32, 33], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (74, 75),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('an',
    'an',
    'PART',
    (76, 78),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('non',
    'non',
    'PART',
    (79, 82),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('risu',
    'risus',
    'NOUN',
    (83, 87),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (87, 88),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('quam',
    'qui',
    'PRON',
    (89, 93),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('acerba',
    'acerbus',
    'ADJ',
    (94, 100),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('insectatione',
    'insectatio',
    'NOUN',
    (101, 113),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('potius',
    'potior',
    'ADV',
    (114, 120),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('dignos',
    'dignus',
    'ADJ',
    (121, 127),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('iudicem',
    'iudico',
    'NOUN',
    (128, 135),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'}),
   ('?',
    '?',
    'PUNCT',
    (135, 136),
    {'page': [7], 'texblock': [33], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  108,
  'Cum chymiatris autem parabolicis stultum est digladiari uelle.',
  [('Cum',
    'cum',
    'SCONJ',
    (0, 3),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('chymiatris',
    'chymiatr',
    'NOUN',
    (4, 14),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('autem',
    'autem',
    'CCONJ',
    (15, 20),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('parabolicis',
    'parabolicus',
    'ADJ',
    (21, 32),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('stultum',
    'stultus',
    'ADJ',
    (33, 40),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('est',
    'sum',
    'AUX',
    (41, 44),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('digladiari',
    'digladio',
    'VERB',
    (45, 55),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('uelle',
    'uolo',
    'VERB',
    (56, 61),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'}),
   ('.',
    '.',
    'PUNCT',
    (61, 62),
    {'page': [7], 'texblock': [34], 'tags': None, 'blocktype': 'text'})]),
 ('100085',
  109,
  'Nihil enim, proficitur, nisi quod cerebrum, rumpitur & tempus perit, Quin fiat hic idem, quod in disciplina Aristotelico ramaea.',
  [('Nihil',
    'nihil',
    'PRON',
    (0, 5),
    {'page': [7], 'texblock': [34, 35], 'tags': None, 'blocktype': 'text'}),
   ('enim',
    'enim',
    'PART',
    (6, 10),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (10, 11),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('proficitur',
    'profico',
    'VERB',
    (12, 22),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (22, 23),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('nisi',
    'nisi',
    'SCONJ',
    (24, 28),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('quod',
    'quod',
    'SCONJ',
    (29, 33),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('cerebrum',
    'cerebrum',
    'NOUN',
    (34, 42),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (42, 43),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('rumpitur',
    'rumpo',
    'VERB',
    (44, 52),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('&',
    '&',
    'PUNCT',
    (53, 54),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('tempus',
    'tempus',
    'NOUN',
    (55, 61),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('perit',
    'pereo',
    'VERB',
    (62, 67),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (67, 68),
    {'page': [7], 'texblock': [35], 'tags': None, 'blocktype': 'text'}),
   ('Quin',
    'quin',
    'ADV',
    (69, 73),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   ('fiat',
    'fio',
    'VERB',
    (74, 78),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   ('hic',
    'hic',
    'DET',
    (79, 82),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   ('idem',
    'idem',
    'DET',
    (83, 87),
    {'page': [7], 'texblock': [36], 'tags': None, 'blocktype': 'text'}),
   (',',
    ',',
    'PUNCT',
    (87, 88),

In [ ]:
    target_path = "/srv/data/tome/tome-corpus/sents_data_id_jsons_v4-0/"
os.makedirs(target_path, exist_ok=True)

In [ ]:
# filename_id_dict.items()

In [ ]:
source_path = "../data/emlap_annotated_textblocks/"
len(os.listdir(source_path)) # 100 for textblocks, 100 for parameters used for their extraction

In [ ]:
os.listdir(source_path)

In [ ]:
for filename in os.listdir(source_path):
    if "_params" not in filename:
            id = filename[:6]
            try:
                if id + ".json" not in os.listdir(target_path):
                    # filename = filename.replace(".pdf", ".json")
                    filepath = os.path.join(source_path, filename)
                    with open(filepath, 'r', encoding='utf-8') as f:
                            textblocks_pages = json.load(f)
                    print("currently processing: ", filename)
                    doc = process_with_source_tracking(textblocks_pages, tomela.nlp)
                    doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)),  {"page" : t._.pages, "texblock" : t._.textblocks}) for t in sent]) for sent in doc.sents]
                    sent_data_updated = []
                    for n_sent, sent_data in enumerate(doc_sentdata):
                            sent_data_updated.append((id, n_sent, sent_data[0], sent_data[1]))
                    with open(target_path + str(id) + ".json", "w") as f:
                            json.dump(sent_data_updated, f)
            except:
                print("failed with file: ", id, filename)
                pass

In [ ]:
fns_jsons = os.listdir(target_path)
fns_jsons[:10]

In [ ]:
len(fns_jsons)

In [ ]:
sents_data = json.load(open(target_path + fns_jsons[20], "r"))
sents_data[100:103]

In [ ]:
import os, json, pickle
prev_path   = target_path  # where your old .pickle / .json live
target_path = "../data/sents_data_jsons_dicts/"
os.makedirs(target_path, exist_ok=True)

def token_tuple_to_dict(tok):
    """
    Accepts token tuples of length 4 or 5:
      4: (text, lemma, pos, (start, end))
      5: (text, lemma, pos, (start, end), ref_dict)
    Returns a JSON-serializable dict.
    """
    if len(tok) < 4:
        raise ValueError(f"Unexpected token shape: {tok}")

    token_text, lemma, pos, span = tok[0], tok[1], tok[2], tok[3]
    if not isinstance(span, (list, tuple)) or len(span) != 2:
        raise ValueError(f"Bad span in token: {tok}")

    char_start, char_end = int(span[0]), int(span[1])

    # Optional ref at index 4
    ref = tok[4] if len(tok) >= 5 else None

    # Make sure ref is JSON-friendly
    if isinstance(ref, dict):
        page = ref.get("page")
        # convert sets/tuples to lists to be JSON-serializable
        if isinstance(page, (set, tuple)):
            page = list(page)
        ref = {
            "page": page,
            "textblock": ref.get("textblock") or ref.get("texblock")  # tolerate earlier key name
        }
    elif ref is not None:
        # unexpected type → stringify to avoid JSON errors
        ref = str(ref)

    return {
        "token_text": token_text,
        "lemma": lemma,
        "pos": pos,
        "ref": ref,                  # << stays None if we don’t have it
        "char_start": char_start,
        "char_end": char_end,
    }

def sent_tuple_to_dict(entry):
    """
    entry is typically: (work_id, sent_id, sent_text, tokens_list)
    """
    if len(entry) != 4:
        raise ValueError(f"Unexpected sentence shape: {type(entry)} {entry}")

    work_id, sent_id, sent_text, tokens_list = entry
    tokens_dicts = [token_tuple_to_dict(tok) for tok in tokens_list]
    return {
        "work_id": work_id,
        "sent_id": int(sent_id),
        "sent_text": sent_text,
        "tokens_data": tokens_dicts,
    }

def load_any(path):
    """
    Load .pickle OR .json produced by your previous run.
    Must return a list of sentence entries (tuples/lists).
    """
    if path.endswith(".pickle"):
        with open(path, "rb") as f:
            return pickle.load(f)
    elif path.endswith(".json"):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    else:
        raise ValueError(f"Unsupported file type: {path}")

for fn in os.listdir(prev_path):
    if not (fn.endswith(".pickle") or fn.endswith(".json")):
        continue

    # Keep your 6-char doc id convention if you like
    doc_id = fn[:6]
    out_path = os.path.join(target_path, f"{doc_id}.json")
    if os.path.exists(out_path):
        continue

    try:
        prev_data = load_any(os.path.join(prev_path, fn))
        # If the previous version stored only (sent_text, tokens) per sentence,
        # reconstruct work_id/sent_id here as needed:
        # e.g., prev_data == [(sent_text, tokens), ...]
        if prev_data and len(prev_data[0]) == 2:
            # synthesize (work_id, sent_id, sent_text, tokens)
            prev_data = [(doc_id, i, s[0], s[1]) for i, s in enumerate(prev_data)]

        sents_dicts = [sent_tuple_to_dict(row) for row in prev_data]

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(sents_dicts, f, ensure_ascii=False, indent=2)

        print("wrote:", out_path)

    except Exception as e:
        print("failed:", fn, "-", e)

In [32]:
doc, doc_margins = process_with_source_tracking(textblocks[:20], tomela.nlp)

In [ ]:
lemmatized_sents_path = "/srv/data/tome/tome-corpus/lemmatized_sents_v4-0/"
try:
    os.mkdir(lemmatized_sents_path)
except:
    pass

In [ ]:
os.listdir(lemmatized_sents_path)

In [ ]:
for fn in fns_jsons:
    lemmatized_sents = []
    sents_data = json.load(open(target_path + fn, "rb"))
    print(fn)
    for (doc_id, sent_id, sent_text, sent_data) in sents_data:
        lemmasent = []
        for wordform, lemma, tag, position, t_ref in sent_data:
            if tag in ["NOUN", "PROPN", "ADJ", "VERB"]:
                lemmasent.append(lemma.lower())
        lemmatized_sents.append(" ".join(lemmasent) + "\n")
    with open(lemmatized_sents_path + fn.replace(".json", ".txt"), "w", encoding="utf-8") as f:
        f.writelines(lemmatized_sents)

In [ ]:
import shutil
shutil.copytree("/srv/data/tome/tome-corpus/lemmatized_sents_v4-0/", "../data/lemmatized_sents", dirs_exist_ok=True)
shutil.copytree("/srv/data/tome/tome-corpus/sents_data_id_jsons_v4-0/", "../data/sents_data", dirs_exist_ok=True)