# About this notebook.

This notebook goes through all the texts and aplies on them a NLP pipeline consisting of (1) cleaning of the raw text, (2) sentence tokenization, (3) part-of-speech annotation, (4) lemmatization, and (5) named entity recognition.

The processed textual data are saved for future reuse.

In [43]:
import spacy
import os
import glob
from spacy.tokens import Doc
from spacy.language import Language
import pickle
from unidecode import unidecode
import sddk
import pandas as pd
import re
import sys
import importlib
import json
from spacy.tokens import Token
from spacy.language import Language
import google_conf
import pandas as pd

In [80]:
emlap_catalogue = google_conf.setup(sheet_url="https://docs.google.com/spreadsheets/d/1bkHHTYc86K2IuEXqfYfkDNt5LovtvCU3gvqHIbVio88/edit?usp=sharing", service_account_path="../../../ServiceAccountsKey.json")


# Get the data and transpose
emlap_metadata_raw = google_conf.get_as_dataframe(emlap_catalogue.worksheet("Copy_of_Catalogue_08_04_2025"), row=1, include_index=False)
emlap_metadata_raw.set_index("author_working", inplace=True)
emlap_metadata_raw.index.name = None
emlap_metadata= emlap_metadata_raw.T
emlap_metadata.index = emlap_metadata.index.astype(str)
emlap_metadata.head(5)

,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,author_name,...,link,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments,OTHER,filename,NaN
"Augurello, Chrysopoeia",100001,True,True,713324,NaN,NaN,True,NaN,True,"Augurelli, Giovanni Aurelio",...,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,Noscemus,Unknown,NaN,Noscemus Wiki,Soranzo 2019,The 1518 Basel version is also in Noscemus,NaN,"Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Ven...",NaN
"Pseudo-Lull, Secretis",100002,True,False,NaN,NaN,NaN,True,NaN,True,Pseudo-Lull,...,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,Hirsch 1950,NaN,"There is a prior, 1514 edition of De secretis ...",NaN,Pseudo-Lull1518_De_secretis_naturae_MDZ.pdf,NaN
"Pantheus, Ars Transmutatione",100003,True,False,NaN,NaN,NaN,True,NaN,True,"Panteo, Giovanni Agostino",...,NaN,GB,BL,NaN,NaN,NaN,This book was first published in 1518 with an ...,NaN,Pantheus1518_Ars_Transmutationis_Metallicae_BL...,NaN
"Pantheus, Commentarium",100004,True,False,NaN,NaN,NaN,True,NaN,True,"Panteo, Giovanni Agostino",...,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MSB,NaN,NaN,NaN,This 1519 book is catalogued wrongly by many l...,NaN,Pantheus1519_Commentarium_Transmutationis_Meta...,NaN
"Pantheus, Voarchadumia",100005,True,False,NaN,NaN,NaN,True,NaN,True,"Panteo, Giovanni Agostino",...,NaN,ONB,ONB,NaN,NaN,NaN,Dedicated to Leonellus Marquis of Estense,NaN,Pantheus1530_Voarchadumia_ONB.pdf,NaN

In [81]:
emlap_metadata[emlap_metadata["author_name"].str.startswith("Dorn", na=False)]

,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,author_name,...,link,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments,OTHER,filename,NaN
"Dorn, Artificii chymistici",100020,True,False,NaN,NaN,NaN,False,NaN,True,"Dorn, Gerard",...,NaN,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Dorn1569_Artificii_chymistici_MDZ_MBS.pdf,NaN
"Dorn, Clavis",100021,True,False,NaN,NaN,NaN,False,NaN,True,"Dorn, Gerard",...,NaN,ONB,ONB,NaN,NaN,NaN,NaN,NaN,Dorn1567_Clavis_totius_philosophiae_chymistica...,NaN
"Dorn, Lapis metaphysicus",100035,True,False,NaN,NaN,NaN,True,NaN,True,"Dorn, Gerard",...,NaN,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.pdf,NaN
"Dorn, Theophrasti Germani",100044,True,False,NaN,NaN,NaN,True,NaN,True,"Dorn, Gerard",...,NaN,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS...,NaN
"Dorn, De naturae luce physica",100045,True,False,NaN,NaN,NaN,False,NaN,True,"Dorn, Gerard",...,NaN,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Dorn1583_De_Naturae_luce_physica_MDZ_MBS.pdf,NaN
"Dorn, Commentaria",100046,True,False,NaN,NaN,NaN,True,NaN,True,"Dorn, Gerard",...,NaN,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.pdf,NaN

In [82]:
filename_id_dict = dict(zip(emlap_metadata["filename"], emlap_metadata["No."]))

For preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level one level up.

The module can be clonned from here: https://github.com/CCS-ZCU/latin-preprocessing and imported to python following the steps below:

In [47]:
# for preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level as the current project.
current_working_directory = os.getcwd()
relative_path = '../../latin-preprocessing/' # change according to your location...
module_path = os.path.abspath(os.path.join(current_working_directory, relative_path))
if module_path not in sys.path:
    sys.path.insert(0, module_path)
# Now import the module
import tomela

Tomela contains tuned latin preprocessing pipeline relying on spaCy and latinCy. You can check the pipeline as here:

In [48]:
tomela.nlp.pipeline

[('source_tracker', <function __main__.source_tracker(doc)>),
 ('senter', <spacy.pipeline.senter.SentenceRecognizer at 0x71371a27cbf0>),
 ('normer', <function la_core_web_lg.functions.normer(doc)>),
 ('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x71371a27cef0>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x71371a27d1f0>),
 ('morphologizer',
  <spacy.pipeline.morphologizer.Morphologizer at 0x71371a27d130>),
 ('trainable_lemmatizer',
  <spacy.pipeline.edit_tree_lemmatizer.EditTreeLemmatizer at 0x71371a27d070>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x71371bec0a50>),
 ('lookup_lemmatizer',
  <function la_core_web_lg.functions.make_lookup_lemmatizer_function(doc)>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x71371bec0890>)]

In [49]:
tomela.nlp.max_length = 4000000

In [50]:
doc = tomela.nlp("Veritas, vt vlla dicit, semper est universalis et a principiis fundamentalis oritur (lib. 3, cap. VI)")
for token in doc:
    print((token.text, token.lemma_, token.pos_))

('Veritas', 'ueritas', 'NOUN')
(',', ',', 'PUNCT')
('vt', 'vt', 'ADV')
('vlla', 'vllus', 'NOUN')
('dicit', 'dico', 'VERB')
(',', ',', 'PUNCT')
('semper', 'semper', 'ADV')
('est', 'sum', 'AUX')
('universalis', 'uniuersalis', 'ADJ')
('et', 'et', 'CCONJ')
('a', 'ab', 'ADP')
('principiis', 'principium', 'NOUN')
('fundamentalis', 'fundamentalis', 'ADJ')
('oritur', 'orior', 'VERB')
('(', '(', 'PUNCT')
('lib', 'liber', 'NOUN')
('.', '.', 'PUNCT')
('3', '3', 'NUM')
(',', ',', 'PUNCT')
('cap', 'capitulum', 'NOUN')
('.', '.', 'PUNCT')
('VI', 'uis', 'NUM')
(')', ')', 'PUNCT')

In [51]:
source_path = "/srv/data/tome/tome-corpus/emlap_annotated_textblocks/"
len(os.listdir(source_path))

152

In [52]:
[f for f in sorted(os.listdir(source_path)) if "_params" not in f]

['Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.json',
 'Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.json',
 'Anon1550_De_alchemia_opuscula_MDZ_MBS.json',
 'Anon1550_Rosarium_philosophorum_Erara.json',
 'Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.json',
 'Auriferae_artisI1572_MBZ_Augsburg.json',
 'Barnaud1599_Quadriga_aurifera_IA_Madrid.json',
 'Bodenstein1559_Isagoge_MDZ_MBS.json',
 'Bonus1546_Pretiosa_Margarita_Novella_ONB.json',
 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json',
 'Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json',
 'De_alchemia1541_MDZ_MBS.json',
 'Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json',
 'Dorn1569_Artificii_chymistici_MDZ_MBS.json',
 'Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.json',
 'Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json',
 'Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.json',
 'Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json',
 'Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json',
 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
 'DuChesne1575_Sclopetarius_MDZ_Augsburg.json',
 'Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json',
 'Fanianus1560_De_arte_metallicae_ONB_pdf.json',
 'Fanianus1576_De_arte_metallicae_MDZ_MBS.json',
 'Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json',
 'Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json',
 'Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json',
 'Greverus1599_Secretum_MDZ_MBS.json',
 'Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.json',
 'Hagecius1596_Actio_medica_ER_UBB.json',
 'Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.json',
 'Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json',
 'Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.json',
 'Libavius1594_Neoparacelsica_MDZ_MBS.json',
 'Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.json',
 'Mirandola1586_De_auro_libri_tres_MDZ_MBS.json',
 'Moffett1588_Nosomantica_Hippocrates_ONB.json',
 'Moffett_De_iure_et_praestantia_MDZ_MBS.json',
 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 'Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json',
 'Pantheus1530_Voarchadumia_ONB.json',
 'Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json',
 'Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json',
 'Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json',
 'Pedemontanus1563_De_Secretis_MDZ_MBS.json',
 'Penotus1594_Tractatus_varii_MDZ_MBS.json',
 'Phaedro1562_Aquila_coelestis_MBZ_MBS.json',
 'Portaleone1584_De_auro_dialogi_tres_ONB.json',
 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 'Pseudo-Democritus1572_Ars_magna.json',
 'Pseudo-Lull1518_De_secretis_naturae_MDZ.json',
 'Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json',
 'Pseudo-Lull1566_Testamentum_MDZ_MBS.json',
 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 'Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json',
 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 'Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.json',
 'Rossi1585_De_destillatione_MDZ_MBS.json',
 'Ruland1564_Medicina_practica_recens_MDZ_MDS.json',
 'Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json',
 'Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json',
 'Senior1560_De_chemia_senioris_MDZ_MBS.json',
 'Severinus1571_Idea_medicinae_MDZ_MBS.json',
 'Severinus1572_Epistola_MBZ_MBS.json',
 'Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json',
 'Suchten1575_De_secretis_antimonii_ONB.json',
 'Toxites1567_Spongia_stibii_MDZ_MBS.json',
 'Trevisanus1567_De_alchemia_MDZ_MBS.json',
 'Trevisanus1583_De_chymico_miraculo_MDZ_MBS.json',
 'Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json',
 'Ulstadt1526_De_epidemia_ONB.json',
 'Vadis1595_Dialogus_IA_Wellcome.json',
 'Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json',
 'Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json',
 'Wecker1582_De_secretis_ONB.json',
 'Witestein1583_Disceptatio_philosophica_MDZ_MBS.json']

In [83]:
[(f, filename_id_dict.get(f.replace(".json", ".pdf"), None)) for f in sorted(os.listdir(source_path)) if "_params" not in f]

[('Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.json',
  100062),
 ('Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.json', 100072),
 ('Anon1550_De_alchemia_opuscula_MDZ_MBS.json', 100022),
 ('Anon1550_Rosarium_philosophorum_Erara.json', 100007),
 ('Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.json', 100001),
 ('Auriferae_artisI1572_MBZ_Augsburg.json', 100038),
 ('Barnaud1599_Quadriga_aurifera_IA_Madrid.json', 100050),
 ('Bodenstein1559_Isagoge_MDZ_MBS.json', 100017),
 ('Bonus1546_Pretiosa_Margarita_Novella_ONB.json', 100016),
 ('Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json', 100010),
 ('Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json', 100056),
 ('De_alchemia1541_MDZ_MBS.json', 100011),
 ('Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json', 100021),
 ('Dorn1569_Artificii_chymistici_MDZ_MBS.json', 100020),
 ('Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.json', 100035),
 ('Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json', 100044),
 ('Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.json', 100075),
 ('Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json', 100045),
 ('Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json', 100046),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json', 100037),
 ('DuChesne1575_Sclopetarius_MDZ_Augsburg.json', 100043),
 ('Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json', 100055),
 ('Fanianus1560_De_arte_metallicae_ONB_pdf.json', 100024),
 ('Fanianus1576_De_arte_metallicae_MDZ_MBS.json', None),
 ('Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json', 100026),
 ('Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json', 100012),
 ('Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json',
  100015),
 ('Greverus1599_Secretum_MDZ_MBS.json', 100073),
 ('Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.json', 100057),
 ('Hagecius1596_Actio_medica_ER_UBB.json', 100058),
 ('Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.json', 100074),
 ('Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json', 100052),
 ('Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.json', 100070),
 ('Libavius1594_Neoparacelsica_MDZ_MBS.json', 100065),
 ('Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.json',
  100063),
 ('Mirandola1586_De_auro_libri_tres_MDZ_MBS.json', 100053),
 ('Moffett1588_Nosomantica_Hippocrates_ONB.json', 100061),
 ('Moffett_De_iure_et_praestantia_MDZ_MBS.json', 100054),
 ('Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json', 100003),
 ('Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json', 100004),
 ('Pantheus1530_Voarchadumia_ONB.json', 100005),
 ('Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json', 100023),
 ('Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json', 100029),
 ('Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json', 100033),
 ('Pedemontanus1563_De_Secretis_MDZ_MBS.json', 100028),
 ('Penotus1594_Tractatus_varii_MDZ_MBS.json', 100034),
 ('Phaedro1562_Aquila_coelestis_MBZ_MBS.json', 100031),
 ('Portaleone1584_De_auro_dialogi_tres_ONB.json', 100047),
 ('Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json', 100048),
 ('Pseudo-Democritus1572_Ars_magna.json', 100039),
 ('Pseudo-Lull1518_De_secretis_naturae_MDZ.json', 100002),
 ('Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json', 100025),
 ('Pseudo-Lull1566_Testamentum_MDZ_MBS.json', 100071),
 ('Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json', 100040),
 ('Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json', 100042),
 ('Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json', 100027),
 ('Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.json', 100068),
 ('Rossi1585_De_destillatione_MDZ_MBS.json', 100049),
 ('Ruland1564_Medicina_practica_recens_MDZ_MDS.json', 100051),
 ('Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json', 100030),
 ('Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json', 100006),
 ('Senior1560_De_chemia_senioris_MDZ_MBS.json', 100041),
 ('Severinus1571_Idea_medicinae_MDZ_MBS.json', 100069),
 ('Severinus1572_Epistola_MBZ_MBS.json', 100008),
 ('Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json', 100059),
 ('Suchten1575_De_secretis_antimonii_ONB.json', 100066),
 ('Toxites1567_Spongia_stibii_MDZ_MBS.json', 100014),
 ('Trevisanus1567_De_alchemia_MDZ_MBS.json', 100018),
 ('Trevisanus1583_De_chymico_miraculo_MDZ_MBS.json', 100064),
 ('Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json', 100013),
 ('Ulstadt1526_De_epidemia_ONB.json', 100019),
 ('Vadis1595_Dialogus_IA_Wellcome.json', 100036),
 ('Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json', 100009),
 ('Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json', 100032),
 ('Wecker1582_De_secretis_ONB.json', 100067),
 ('Witestein1583_Disceptatio_philosophica_MDZ_MBS.json', 100060)]

In [84]:
files_overview = []
for filename in os.listdir(source_path):
    #filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
    if "_params" not in filename:
        filepath = os.path.join(source_path, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            textblocks = json.load(f)
        pages_n = len(textblocks)
        chars_n = sum([sum([len(tb["text"]) for tb in p]) for p in textblocks])
        files_overview.append({"filename" : filename, "pages_n" : pages_n, "chars_n" : chars_n})
files_processed = pd.DataFrame(files_overview)
files_processed

                                             filename  pages_n  chars_n
0         Moffett_De_iure_et_praestantia_MDZ_MBS.json      115   120620
1             Toxites1567_Spongia_stibii_MDZ_MBS.json       21    14543
2      Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json      405   340776
3   Pantheus1518_Ars_Transmutationis_Metallicae_BL...       53    49495
4   Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_...       69   105063
..                                                ...      ...      ...
71  Paracelsus1553_Labyrinthus_medicorum_errantium...       95   173322
72       Fanianus1576_De_arte_metallicae_MDZ_MBS.json      129    96521
73               Pseudo-Democritus1572_Ars_magna.json      153   174854
74          Severinus1571_Idea_medicinae_MDZ_MBS.json      449    39747
75  Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json      233   275466

[76 rows x 3 columns]

In [56]:
google_conf.set_with_dataframe(emlap_catalogue.add_worksheet("files_processed", 1,1), files_processed, include_index=False)


# Develop and test with one example test

In [57]:
filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
filepath = os.path.join(source_path, filename)
with open(filepath, 'r', encoding='utf-8') as f:
    textblocks = json.load(f)

In [58]:
len(textblocks)

93

In [59]:
textblocks[30][:10]

[{'coordinates': [165.1199951171875,
   40.31997299194336,
   427.239990234375,
   48.62395477294922],
  'text': '14\nRESPONSIO\n',
  'tag': 'header'},
 {'coordinates': [165.1199951171875,
   69.11996459960938,
   512.6112670898438,
   73.91996002197266],
  'text': 'calculo aut renum tartaro, tanta vi pro¬\n',
  'tag': 'text'},
 {'coordinates': [165.1199951171875,
   93.3840103149414,
   515.9405517578125,
   98.30400848388672],
  'text': 'desse diceres? Intelligo, Confugeres\n',
  'tag': 'text'},
 {'coordinates': [165.1199951171875,
   116.66397857666016,
   512.2813720703125,
   121.58397674560547],
  'text': 'ad sacram asinorum anchoram, nem¬\n',
  'tag': 'text'},
 {'coordinates': [168.72000122070312,
   140.87997436523438,
   509.6862487792969,
   145.6799774169922],
  'text': 'pe proprietatum occultarum: quod ta¬\n',
  'tag': 'text'},
 {'coordinates': [169.1999969482422,
   165.11996459960938,
   515.7952880859375,
   169.9199676513672],
  'text': 'men ipso sale fieri, qui illos resoluit, &\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   188.16000366210938,
   513.2568359375,
   192.9600067138672],
  'text': 'per vrinas expellit, ratio ipsa docet.\n',
  'tag': 'text'},
 {'coordinates': [170.8800048828125,
   211.94400024414062,
   511.9048156738281,
   216.86399841308594],
  'text': 'Quid ergo diceres de Troglodyte lau¬\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   235.94400024414062,
   511.7084655761719,
   240.86399841308594],
  'text': 'datissimo illo antiquorum medicamen¬\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   259.6799621582031,
   512.2210693359375,
   264.4799499511719],
  'text': 'to ad eandem affectionem, cuius me¬\n',
  'tag': 'text'}]

In [60]:

# Modify the token extensions for simpler output
if not Token.has_extension("pages"):
    Token.set_extension("pages", default=None)
if not Token.has_extension("textblocks"):
    Token.set_extension("textblocks", default=None)
if not Doc.has_extension("char_to_source"):
    Doc.set_extension("char_to_source", default=None)


def process_textblocks(textblocks):
    full_text = ""
    char_to_source = {}

    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):
            if tb["tag"] == "text":
                start_idx = len(full_text)
                text = tomela.text_cleaner(tb["text"])

                for char_idx in range(len(text)):
                    char_to_source[start_idx + char_idx] = {
                        "page_idx": page_idx,
                        "textblock_idx": tb_idx
                    }

                full_text +=  text

    return full_text, char_to_source


@Language.component("source_tracker")
def source_tracker(doc):
    if doc._.char_to_source is not None:
        for token in doc:
            # Get the character span of the entire token
            token_char_range = range(token.idx, token.idx + len(token.text))

            pages = set()
            textblocks = set()

            for char_idx in token_char_range:
                if char_idx in doc._.char_to_source:
                    source_info = doc._.char_to_source[char_idx]
                    pages.add(source_info["page_idx"])
                    textblocks.add(source_info["textblock_idx"])

            token._.pages = sorted(list(pages))
            token._.textblocks = sorted(list(textblocks))
    return doc


# Add the custom component to your existing pipeline if not already added
if "source_tracker" not in tomela.nlp.pipe_names:
    tomela.nlp.add_pipe("source_tracker", before="senter")


def process_with_source_tracking(textblocks, nlp):
    full_text, char_to_source = process_textblocks(textblocks)
    # Create the doc with the text
    doc = nlp.make_doc(full_text)
    # Set the char_to_source before running the pipeline
    doc._.char_to_source = char_to_source
    # Process the doc through each pipeline component
    for name, proc in nlp.pipeline:
        doc = proc(doc)
    return doc

In [61]:
textblocks[21:22]

[[{'coordinates': [146.63999938964844,
    46.55996322631836,
    435.6400146484375,
    51.599952697753906],
   'text': '5\nAD AVBERTVM.\n',
   'tag': 'header'},
  {'coordinates': [88.55999755859375,
    74.66397857666016,
    435.73681640625,
    79.58397674560547],
   'text': 'naturae iuuandum robur, & aduersus af¬\n',
   'tag': 'text'},
  {'coordinates': [91.19999694824219,
    98.66397857666016,
    444.1780700683594,
    103.58397674560547],
   'text': 'fectus melancholicos, ad exolutum ven¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    122.87997436523438,
    438.64984130859375,
    127.67996978759766],
   'text': 'triculum; ad cardiacos, & praeter ratio¬\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    146.87997436523438,
    441.6309814453125,
    151.6799774169922],
   'text': 'nem moestos efficax remedium. Certe\n',
   'tag': 'text'},
  {'coordinates': [89.27999877929688,
    172.31997680664062,
    441.3201904296875,
    177.11997985839844],
   'text': 'in ipsius essentia, quàm in tuo auro fo¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    195.60000610351562,
    444.3800354003906,
    200.40000915527344],
   'text': 'liato, multò maiorem facultatem inesse\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    220.31997680664062,
    438.85797119140625,
    225.11997985839844],
   'text': 'meritò credideris. Dabis & illud, mi\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    244.55996704101562,
    437.1007995605469,
    249.35997009277344],
   'text': 'Auberte, in eo purissimo, vim illam oc¬\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    268.5839538574219,
    438.9518737792969,
    273.50396728515625],
   'text': 'cultarum proprietatum maiorem esse,\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    292.8240051269531,
    439.442626953125,
    297.7440185546875],
   'text': 'quàm in tuis iusculis cum auro coctis.\n',
   'tag': 'text'},
  {'coordinates': [95.04000091552734,
    316.5839538574219,
    436.8152770996094,
    321.50396728515625],
   'text': 'Nec tamen, puto, credes (hoc enim ni¬\n',
   'tag': 'text'},
  {'coordinates': [88.08000183105469,
    341.7599792480469,
    437.74407958984375,
    346.5599670410156],
   'text': 'mis esset absurdum) aurum, quod ne i¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    366.0,
    441.1604309082031,
    370.79998779296875],
   'text': 'gnis quidem ardore torreri absumive\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    391.4639892578125,
    170.05992126464844,
    396.3840026855469],
   'text': 'potest¬\n',
   'tag': 'text'},
  {'coordinates': [96.0,
    413.7839660644531,
    440.809814453125,
    418.7039794921875],
   'text': '"(Vni enim (vt scribit Poeta) nil deperit aurò\n',
   'tag': 'text'},
  {'coordinates': [89.76000213623047,
    438.50396728515625,
    438.0096435546875,
    443.4239807128906],
   'text': 'Igne, velut solum consumit nulla vetustas,\n',
   'tag': 'text'},
  {'coordinates': [89.27999877929688,
    462.47998046875,
    440.6310729980469,
    467.27996826171875],
   'text': 'Ac neque rubigo, aut aerugo conficit vlla:\xa0\n',
   'tag': 'text'},
  {'coordinates': [97.68000030517578,
    486.9599914550781,
    434.4278869628906,
    491.7599792480469],
   'text': 'Cuncta adeò firmis illic compagibus haerent)"\n',
   'tag': 'text'},
  {'coordinates': [89.76000213623047,
    511.9200134277344,
    446.9093933105469,
    516.7200317382812],
   'text': 'à natiuo calore decoqui aut deuinci\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    536.1840209960938,
    438.8242492675781,
    541.10400390625],
   'text': 'ita posse, quin cor, integra remanente\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    560.1840209960938,
    439.9804382324219,
    565.10400390625],
   'text': 'illius substantia, ipso corroborari quo¬\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    584.9039916992188,
    438.4349060058594,
    589.823974609375],
   'text': 'dammodo queat: quum sit haec Philoso¬\n',
   'tag': 'text'},
  {'coordinates': [88.55999755859375,
    609.6240234375,
    446.4131164550781,
    614.5440063476562],
   'text': 'phorum sententia, Terram videlicet\n',
   'tag': 'text'},
  {'coordinates': [88.55999755859375,
    633.1199340820312,
    442.3680419921875,
    637.9199829101562],
   'text': 'omnem esse mortuam, & spiritus rerum\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    656.8799438476562,
    435.6803894042969,
    661.6799926757812],
   'text': 'in corporibus solos agere posse.\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    681.3839721679688,
    446.1756286621094,
    686.303955078125],
   'text': 'Caeterum Laudanum ipsum quanuis\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    706.10400390625,
    447.25701904296875,
    711.0239868164062],
   'text': 'opiaticum, non ita tamen conuitiis est\n',
   'tag': 'text'},
  {'coordinates': [346.32000732421875,
    730.583984375,
    398.04974365234375,
    735.5039672851562],
   'text': 'B.iij.\n',
   'tag': 'footer'}]]

In [62]:
doc = process_with_source_tracking(textblocks[21:22], tomela.nlp)
doc

naturae iuuandum robur, & aduersus affectus melancholicos, ad exolutum uentriculum; ad cardiacos, & praeter rationem moestos efficax remedium. Certe in ipsius essentia, quam in tuo auro foliato, multo maiorem facultatem inesse merito credideris. Dabis & illud, mi Auberte, in eo purissimo, uim illam occultarum proprietatum maiorem esse, quam in tuis iusculis cum auro coctis. Nec tamen, puto, credes (hoc enim nimis esset absurdum) aurum, quod ne ignis quidem ardore torreri absumiue potest"(Uni enim (ut scribit Poeta) nil deperit auro Igne, uelut solum consumit nulla uetustas, Ac neque rubigo, aut aerugo conficit ulla: Cuncta adeo firmis illic compagibus haerent)" a natiuo calore decoqui aut deuinci ita posse, quin cor, integra remanente illius substantia, ipso corroborari quodammodo queat: quum sit haec Philosophorum sententia, Terram uidelicet omnem esse mortuam, & spiritus rerum in corporibus solos agere posse. Caeterum Laudanum ipsum quanuis opiaticum, non ita tamen conuitiis est

In [63]:
doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)), t._.pages, t._.textblocks) for t in sent]) for sent in doc.sents]
sent_data_updated = []
for n_sent, sent_data in enumerate(doc_sentdata):
    sent_data_updated.append((filename, n_sent, sent_data[0], sent_data[1]))

In [64]:
sent_data_updated

[('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  0,
  'naturae iuuandum robur, & aduersus affectus melancholicos, ad exolutum uentriculum;',
  [('naturae', 'natura', 'NOUN', (0, 7), [0], [1]),
   ('iuuandum', 'iuuo', 'VERB', (8, 16), [0], [1]),
   ('robur', 'robur', 'NOUN', (17, 22), [0], [1]),
   (',', ',', 'PUNCT', (22, 23), [0], [1]),
   ('&', '&', 'PUNCT', (24, 25), [0], [1]),
   ('aduersus', 'aduersus', 'ADP', (26, 34), [0], [1]),
   ('affectus', 'affectus', 'NOUN', (35, 43), [0], [1, 2]),
   ('melancholicos', 'melancholicus', 'ADJ', (44, 57), [0], [2]),
   (',', ',', 'PUNCT', (57, 58), [0], [2]),
   ('ad', 'ad', 'ADP', (59, 61), [0], [2]),
   ('exolutum', 'exoluo', 'VERB', (62, 70), [0], [2]),
   ('uentriculum', 'uentriculus', 'ADJ', (71, 82), [0], [2, 3]),
   (';', ';', 'PUNCT', (82, 83), [0], [3])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  1,
  'ad cardiacos, & praeter rationem moestos efficax remedium.',
  [('ad', 'ad', 'ADP', (0, 2), [0], [3]),
   ('cardiacos', 'cardiacus', 'NOUN', (3, 12), [0], [3]),
   (',', ',', 'PUNCT', (12, 13), [0], [3]),
   ('&', '&', 'PUNCT', (14, 15), [0], [3]),
   ('praeter', 'praeter', 'ADP', (16, 23), [0], [3]),
   ('rationem', 'ratio', 'NOUN', (24, 32), [0], [3, 4]),
   ('moestos', 'moestus', 'ADJ', (33, 40), [0], [4]),
   ('efficax', 'efficax', 'ADJ', (41, 48), [0], [4]),
   ('remedium', 'remedium', 'NOUN', (49, 57), [0], [4]),
   ('.', '.', 'PUNCT', (57, 58), [0], [4])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  2,
  'Certe in ipsius essentia, quam in tuo auro foliato, multo maiorem facultatem inesse merito credideris.',
  [('Certe', 'certe', 'ADV', (0, 5), [0], [4]),
   ('in', 'in', 'ADP', (6, 8), [0], [5]),
   ('ipsius', 'ipse', 'DET', (9, 15), [0], [5]),
   ('essentia', 'essentia', 'NOUN', (16, 24), [0], [5]),
   (',', ',', 'PUNCT', (24, 25), [0], [5]),
   ('quam', 'qui', 'PRON', (26, 30), [0], [5]),
   ('in', 'in', 'ADP', (31, 33), [0], [5]),
   ('tuo', 'tuus', 'DET', (34, 37), [0], [5]),
   ('auro', 'aurum', 'NOUN', (38, 42), [0], [5]),
   ('foliato', 'foliatus', 'VERB', (43, 50), [0], [5, 6]),
   (',', ',', 'PUNCT', (50, 51), [0], [6]),
   ('multo', 'multo', 'ADV', (52, 57), [0], [6]),
   ('maiorem', 'maior', 'ADJ', (58, 65), [0], [6]),
   ('facultatem', 'facultas', 'NOUN', (66, 76), [0], [6]),
   ('inesse', 'insum', 'VERB', (77, 83), [0], [6]),
   ('merito', 'merito', 'ADV', (84, 90), [0], [7]),
   ('credideris', 'credo', 'VERB', (91, 101), [0], [7]),
   ('.', '.', 'PUNCT', (101, 102), [0], [7])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  3,
  'Dabis & illud, mi Auberte, in eo purissimo, uim illam occultarum proprietatum maiorem esse, quam in tuis iusculis cum auro coctis.',
  [('Dabis', 'do', 'VERB', (0, 5), [0], [7]),
   ('&', '&', 'PUNCT', (6, 7), [0], [7]),
   ('illud', 'ille', 'DET', (8, 13), [0], [7]),
   (',', ',', 'PUNCT', (13, 14), [0], [7]),
   ('mi', 'meus', 'DET', (15, 17), [0], [7]),
   ('Auberte', 'Auberta', 'PROPN', (18, 25), [0], [8]),
   (',', ',', 'PUNCT', (25, 26), [0], [8]),
   ('in', 'in', 'ADP', (27, 29), [0], [8]),
   ('eo', 'is', 'PRON', (30, 32), [0], [8]),
   ('purissimo', 'purissimus', 'ADJ', (33, 42), [0], [8]),
   (',', ',', 'PUNCT', (42, 43), [0], [8]),
   ('uim', 'uis', 'NOUN', (44, 47), [0], [8]),
   ('illam', 'ille', 'DET', (48, 53), [0], [8]),
   ('occultarum', 'occulo', 'VERB', (54, 64), [0], [8, 9]),
   ('proprietatum', 'proprietas', 'NOUN', (65, 77), [0], [9]),
   ('maiorem', 'maior', 'ADJ', (78, 85), [0], [9]),
   ('esse', 'sum', 'AUX', (86, 90), [0], [9]),
   (',', ',', 'PUNCT', (90, 91), [0], [9]),
   ('quam', 'qui', 'PRON', (92, 96), [0], [10]),
   ('in', 'in', 'ADP', (97, 99), [0], [10]),
   ('tuis', 'tuus', 'DET', (100, 104), [0], [10]),
   ('iusculis', 'iusculum', 'NOUN', (105, 113), [0], [10]),
   ('cum', 'cum', 'ADP', (114, 117), [0], [10]),
   ('auro', 'aurum', 'NOUN', (118, 122), [0], [10]),
   ('coctis', 'coquo', 'VERB', (123, 129), [0], [10]),
   ('.', '.', 'PUNCT', (129, 130), [0], [10])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  4,
  'Nec tamen, puto, credes (hoc enim nimis esset absurdum) aurum, quod ne ignis quidem ardore torreri absumiue potest"(Uni enim (ut scribit Poeta) nil deperit auro Igne, uelut solum consumit nulla uetustas, Ac neque rubigo, aut aerugo conficit ulla:',
  [('Nec', 'nec', 'CCONJ', (0, 3), [0], [11]),
   ('tamen', 'tamen', 'ADV', (4, 9), [0], [11]),
   (',', ',', 'PUNCT', (9, 10), [0], [11]),
   ('puto', 'puto', 'VERB', (11, 15), [0], [11]),
   (',', ',', 'PUNCT', (15, 16), [0], [11]),
   ('credes', 'credo', 'VERB', (17, 23), [0], [11]),
   ('(', '(', 'PUNCT', (24, 25), [0], [11]),
   ('hoc', 'hic', 'DET', (25, 28), [0], [11]),
   ('enim', 'enim', 'PART', (29, 33), [0], [11]),
   ('nimis', 'nimis', 'ADV', (34, 39), [0], [11, 12]),
   ('esset', 'sum', 'AUX', (40, 45), [0], [12]),
   ('absurdum', 'absurdus', 'ADJ', (46, 54), [0], [12]),
   (')', ')', 'PUNCT', (54, 55), [0], [12]),
   ('aurum', 'aurum', 'NOUN', (56, 61), [0], [12]),
   (',', ',', 'PUNCT', (61, 62), [0], [12]),
   ('quod', 'qui', 'PRON', (63, 67), [0], [12]),
   ('ne', 'ne', 'ADV', (68, 70), [0], [12]),
   ('ignis', 'ignis', 'NOUN', (71, 76), [0], [12, 13]),
   ('quidem', 'quidem', 'PART', (77, 83), [0], [13]),
   ('ardore', 'ardor', 'NOUN', (84, 90), [0], [13]),
   ('torreri', 'torreo', 'VERB', (91, 98), [0], [13]),
   ('absumiue', 'absumiue', 'ADV', (99, 107), [0], [13]),
   ('potest"(Uni', '', 'VERB', (108, 119), [0], [14, 15]),
   ('enim', 'enim', 'PART', (120, 124), [0], [15]),
   ('(', '(', 'PUNCT', (125, 126), [0], [15]),
   ('ut', 'ut', 'SCONJ', (126, 128), [0], [15]),
   ('scribit', 'scribo', 'VERB', (129, 136), [0], [15]),
   ('Poeta', 'poeta', 'NOUN', (137, 142), [0], [15]),
   (')', ')', 'PUNCT', (142, 143), [0], [15]),
   ('nil', 'nihil', 'ADV', (144, 147), [0], [15]),
   ('deperit', 'depereo', 'VERB', (148, 155), [0], [15]),
   ('auro', 'aurum', 'NOUN', (156, 160), [0], [15]),
   ('Igne', 'ignis', 'PROPN', (161, 165), [0], [16]),
   (',', ',', 'PUNCT', (165, 166), [0], [16]),
   ('uelut', 'uelut', 'SCONJ', (167, 172), [0], [16]),
   ('solum', 'solum', 'ADV', (173, 178), [0], [16]),
   ('consumit', 'consumo', 'VERB', (179, 187), [0], [16]),
   ('nulla', 'nullus', 'DET', (188, 193), [0], [16]),
   ('uetustas', 'uetustas', 'NOUN', (194, 202), [0], [16]),
   (',', ',', 'PUNCT', (202, 203), [0], [16]),
   ('Ac', 'atque', 'CCONJ', (204, 206), [0], [17]),
   ('neque', 'neque', 'CCONJ', (207, 212), [0], [17]),
   ('rubigo', 'rubigo', 'NOUN', (213, 219), [0], [17]),
   (',', ',', 'PUNCT', (219, 220), [0], [17]),
   ('aut', 'aut', 'CCONJ', (221, 224), [0], [17]),
   ('aerugo', 'aerugo', 'NOUN', (225, 231), [0], [17]),
   ('conficit', 'conficio', 'VERB', (232, 240), [0], [17]),
   ('ulla', 'ullus', 'DET', (241, 245), [0], [17]),
   (':', ':', 'PUNCT', (245, 246), [0], [17])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  5,
  'Cuncta adeo firmis illic compagibus haerent)" a natiuo calore decoqui aut deuinci ita posse, quin cor, integra remanente illius substantia, ipso corroborari quodammodo queat:',
  [('Cuncta', 'cunctus', 'DET', (0, 6), [0], [18]),
   ('adeo', 'adeo', 'ADV', (7, 11), [0], [18]),
   ('firmis', 'firmus', 'ADJ', (12, 18), [0], [18]),
   ('illic', 'illic', 'ADV', (19, 24), [0], [18]),
   ('compagibus', 'compages', 'NOUN', (25, 35), [0], [18]),
   ('haerent', 'haereo', 'VERB', (36, 43), [0], [18]),
   (')', ')', 'PUNCT', (43, 44), [0], [18]),
   ('"', '"', 'PUNCT', (44, 45), [0], [18]),
   ('a', 'ab', 'ADP', (46, 47), [0], [19]),
   ('natiuo', 'natiuus', 'ADJ', (48, 54), [0], [19]),
   ('calore', 'calor', 'NOUN', (55, 61), [0], [19]),
   ('decoqui', 'decoquo', 'VERB', (62, 69), [0], [19]),
   ('aut', 'aut', 'CCONJ', (70, 73), [0], [19]),
   ('deuinci', 'deuinco', 'VERB', (74, 81), [0], [19]),
   ('ita', 'ita', 'ADV', (82, 85), [0], [20]),
   ('posse', 'possum', 'VERB', (86, 91), [0], [20]),
   (',', ',', 'PUNCT', (91, 92), [0], [20]),
   ('quin', 'quin', 'SCONJ', (93, 97), [0], [20]),
   ('cor', 'cor', 'NOUN', (98, 101), [0], [20]),
   (',', ',', 'PUNCT', (101, 102), [0], [20]),
   ('integra', 'integer', 'ADJ', (103, 110), [0], [20]),
   ('remanente', 'remaneo', 'VERB', (111, 120), [0], [20]),
   ('illius', 'ille', 'DET', (121, 127), [0], [21]),
   ('substantia', 'substantia', 'NOUN', (128, 138), [0], [21]),
   (',', ',', 'PUNCT', (138, 139), [0], [21]),
   ('ipso', 'ipse', 'DET', (140, 144), [0], [21]),
   ('corroborari', 'corroboro', 'VERB', (145, 156), [0], [21]),
   ('quodammodo', 'quodammodo', 'ADV', (157, 167), [0], [21, 22]),
   ('queat', 'queo', 'VERB', (168, 173), [0], [22]),
   (':', ':', 'PUNCT', (173, 174), [0], [22])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  6,
  'quum sit haec Philosophorum sententia, Terram uidelicet omnem esse mortuam, & spiritus rerum in corporibus solos agere posse.',
  [('quum', 'quum', 'SCONJ', (0, 4), [0], [22]),
   ('sit', 'sum', 'AUX', (5, 8), [0], [22]),
   ('haec', 'hic', 'DET', (9, 13), [0], [22]),
   ('Philosophorum', 'philosophus', 'NOUN', (14, 27), [0], [22, 23]),
   ('sententia', 'sententia', 'NOUN', (28, 37), [0], [23]),
   (',', ',', 'PUNCT', (37, 38), [0], [23]),
   ('Terram', 'terra', 'NOUN', (39, 45), [0], [23]),
   ('uidelicet', 'uidelicet', 'CCONJ', (46, 55), [0], [23]),
   ('omnem', 'omnis', 'DET', (56, 61), [0], [24]),
   ('esse', 'sum', 'AUX', (62, 66), [0], [24]),
   ('mortuam', 'morior', 'VERB', (67, 74), [0], [24]),
   (',', ',', 'PUNCT', (74, 75), [0], [24]),
   ('&', '&', 'PUNCT', (76, 77), [0], [24]),
   ('spiritus', 'spiritus', 'NOUN', (78, 86), [0], [24]),
   ('rerum', 'res', 'NOUN', (87, 92), [0], [24]),
   ('in', 'in', 'ADP', (93, 95), [0], [25]),
   ('corporibus', 'corpus', 'NOUN', (96, 106), [0], [25]),
   ('solos', 'solus', 'DET', (107, 112), [0], [25]),
   ('agere', 'ago', 'VERB', (113, 118), [0], [25]),
   ('posse', 'possum', 'VERB', (119, 124), [0], [25]),
   ('.', '.', 'PUNCT', (124, 125), [0], [25])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  7,
  'Caeterum Laudanum ipsum quanuis opiaticum, non ita tamen conuitiis est',
  [('Caeterum', 'caeterum', 'ADV', (0, 8), [0], [26]),
   ('Laudanum', 'Laudanus', 'ADJ', (9, 17), [0], [26]),
   ('ipsum', 'ipse', 'DET', (18, 23), [0], [26]),
   ('quanuis', 'quanua', 'NOUN', (24, 31), [0], [26]),
   ('opiaticum', 'opiaticus', 'ADJ', (32, 41), [0], [27]),
   (',', ',', 'PUNCT', (41, 42), [0], [27]),
   ('non', 'non', 'PART', (43, 46), [0], [27]),
   ('ita', 'ita', 'ADV', (47, 50), [0], [27]),
   ('tamen', 'tamen', 'ADV', (51, 56), [0], [27]),
   ('conuitiis', 'conuitium', 'NOUN', (57, 66), [0], [27]),
   ('est', 'sum', 'AUX', (67, 70), [0], [27])])]

In [85]:
target_path = "/srv/data/tome/tome-corpus/sents_data_id_jsons_v3-0/"
try:
    os.mkdir(target_path)
except:
    pass

In [91]:
filename_id_dict.items()

dict_items([('Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.pdf', 100001), ('Pseudo-Lull1518_De_secretis_naturae_MDZ.pdf', 100002), ('Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.pdf', 100003), ('Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.pdf', 100004), ('Pantheus1530_Voarchadumia_ONB.pdf', 100005), ('Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.pdf', 100006), ('Anon1550_Rosarium_philosophorum_Erara.pdf', 100007), ('Severinus1572_Epistola_MBZ_MBS.pdf', 100008), ('Vegius1518_Inter_inferiora_corpora_disputatio_ONB.pdf', 100009), ('Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.pdf', 100010), ('De_alchemia1541_MDZ_MBS.pdf', 100011), ('Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.pdf', 100012), ('Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.pdf', 100013), ('Toxites1567_Spongia_stibii_MDZ_MBS.pdf', 100014), ('Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.pdf', 100015), ('Bonus1546_Pretiosa_Margarita_Novella_ONB.pdf', 100016), ('Bodenstein1559_Isagoge_MDZ_MBS.pdf', 100017), ('Trevisanus1567_De_alchemia_MDZ_MBS.pdf', 100018), ('Ulstadt1526_De_epidemia_ONB.pdf', 100019), ('Dorn1569_Artificii_chymistici_MDZ_MBS.pdf', 100020), ('Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.pdf', 100021), ('Anon1550_De_alchemia_opuscula_MDZ_MBS.pdf', 100022), ('Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.pdf', 100023), ('Fanianus1560_De_arte_metallicae_ONB_pdf.pdf', 100024), ('Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.pdf', 100025), ('Garlandius1560_Compendium_Alchemiae_SLUB_pdf.pdf', 100026), ('Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.pdf', 100027), ('Pedemontanus1563_De_Secretis_MDZ_MBS.pdf', 100028), ('Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.pdf', 100029), ('Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.pdf', 100030), ('Phaedro1562_Aquila_coelestis_MBZ_MBS.pdf', 100031), ('Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.pdf', 100032), ('Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.pdf', 100033), ('Penotus1594_Tractatus_varii_MDZ_MBS.pdf', 100034), ('Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.pdf', 100035), ('Vadis1595_Dialogus_IA_Wellcome.pdf', 100036), ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.pdf', 100037), ('Auriferae_artisI1572_MBZ_Augsburg.pdf', 100038), ('Pseudo-Democritus1572_Ars_magna.pdf', 100039), ('Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.pdf', 100040), ('Senior1560_De_chemia_senioris_MDZ_MBS.pdf', 100041), ('Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.pdf', 100042), ('DuChesne1575_Sclopetarius_MDZ_Augsburg.pdf', 100043), ('Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.pdf', 100044), ('Dorn1583_De_Naturae_luce_physica_MDZ_MBS.pdf', 100045), ('Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.pdf', 100046), ('Portaleone1584_De_auro_dialogi_tres_ONB.pdf', 100047), ('Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.pdf', 100048), ('Rossi1585_De_destillatione_MDZ_MBS.pdf', 100049), ('Barnaud1599_Quadriga_aurifera_IA_Madrid.pdf', 100050), ('Ruland1564_Medicina_practica_recens_MDZ_MDS.pdf', 100051), ('Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.pdf', 100052), ('Mirandola1586_De_auro_libri_tres_MDZ_MBS.pdf', 100053), ('Moffett_De_iure_et_praestantia_MDZ_MBS.pdf', 100054), ('Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.pdf', 100055), ('Claveus1598_Apologia_crysopoeiae_MDZ_MBS.pdf', 100056), ('Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.pdf', 100057), ('Hagecius1596_Actio_medica_ER_UBB.pdf', 100058), ('Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.pdf', 100059), ('Witestein1583_Disceptatio_philosophica_MDZ_MBS.pdf', 100060), ('Moffett1588_Nosomantica_Hippocrates_ONB.pdf', 100061), ('Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.pdf', 100062), ('Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.pdf', 100063), ('Trevisanus1583_De_chymico_miraculo_MDZ_MBS.pdf', 100064), ('Libavius1594_Neoparacelsica_MDZ_MBS.pdf', 100065), ('Suchten1575_De_secretis_antimonii_ONB.pdf', 100066), ('Wecker1582_De_secretis_ONB.pdf', 100067), ('Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.pdf', 100068), ('Severinus1571_Idea_medicinae_MDZ_MBS.pdf', 100069), ('Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.pdf', 100070), ('Pseudo-Lull1566_Testamentum_MDZ_MBS.pdf', 100071), ('Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.pdf', 100072), ('Greverus1599_Secretum_MDZ_MBS.pdf', 100073), ('Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.pdf', 100074), ('Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.pdf', 100075)])

In [94]:
%%time
source_path = "/srv/data/tome/tome-corpus/emlap_annotated_textblocks/"
for filename, id in filename_id_dict.items():
        try:
                if str(id) + ".json " not in os.listdir(target_path):
                    filename = filename.replace(".pdf", ".json")
                    filepath = os.path.join(source_path, filename.replace(".pdf", ".json"))
                    with open(filepath, 'r', encoding='utf-8') as f:
                            textblocks_pages = json.load(f)
                    print("currently processing: ", filename)
                    doc = process_with_source_tracking(textblocks_pages, tomela.nlp)
                    doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)), t._.pages, t._.textblocks) for t in sent]) for sent in doc.sents]
                    sent_data_updated = []
                    for n_sent, sent_data in enumerate(doc_sentdata):
                            sent_data_updated.append((id, n_sent, sent_data[0], sent_data[1]))
                    with open(target_path + str(id) + ".json", "w") as f:
                            json.dump(sent_data_updated, f)
        except:
            print("failed with file: ", id, filename)
            pass

currently processing:  Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.json
currently processing:  Pseudo-Lull1518_De_secretis_naturae_MDZ.json
currently processing:  Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json
currently processing:  Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json
currently processing:  Pantheus1530_Voarchadumia_ONB.json
currently processing:  Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json
currently processing:  Anon1550_Rosarium_philosophorum_Erara.json
currently processing:  Severinus1572_Epistola_MBZ_MBS.json
currently processing:  Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json
currently processing:  Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json
currently processing:  De_alchemia1541_MDZ_MBS.json
currently processing:  Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json
currently processing:  Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json
currently processing:  Toxites1567_Spongia_stibii_MDZ_MBS.json
currently processing:  Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json
currently processing:  Bonus1546_Pretiosa_Margarita_Novella_ONB.json
currently processing:  Bodenstein1559_Isagoge_MDZ_MBS.json
currently processing:  Trevisanus1567_De_alchemia_MDZ_MBS.json
currently processing:  Ulstadt1526_De_epidemia_ONB.json
currently processing:  Dorn1569_Artificii_chymistici_MDZ_MBS.json
currently processing:  Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json
currently processing:  Anon1550_De_alchemia_opuscula_MDZ_MBS.json
currently processing:  Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json
currently processing:  Fanianus1560_De_arte_metallicae_ONB_pdf.json
currently processing:  Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json
currently processing:  Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json
currently processing:  Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json
currently processing:  Pedemontanus1563_De_Secretis_MDZ_MBS.json
currently processing:  Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json
currently processing:  Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json
currently processing:  Phaedro1562_Aquila_coelestis_MBZ_MBS.json
currently processing:  Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json
currently processing:  Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json
currently processing:  Penotus1594_Tractatus_varii_MDZ_MBS.json
currently processing:  Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.json
currently processing:  Vadis1595_Dialogus_IA_Wellcome.json
currently processing:  DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json
currently processing:  Auriferae_artisI1572_MBZ_Augsburg.json
currently processing:  Pseudo-Democritus1572_Ars_magna.json
currently processing:  Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json
currently processing:  Senior1560_De_chemia_senioris_MDZ_MBS.json
currently processing:  Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json
currently processing:  DuChesne1575_Sclopetarius_MDZ_Augsburg.json
currently processing:  Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json
currently processing:  Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json
currently processing:  Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.json
currently processing:  Portaleone1584_De_auro_dialogi_tres_ONB.json
currently processing:  Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json
currently processing:  Rossi1585_De_destillatione_MDZ_MBS.json
currently processing:  Barnaud1599_Quadriga_aurifera_IA_Madrid.json
currently processing:  Ruland1564_Medicina_practica_recens_MDZ_MDS.json
currently processing:  Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json
currently processing:  Mirandola1586_De_auro_libri_tres_MDZ_MBS.json
currently processing:  Moffett_De_iure_et_praestantia_MDZ_MBS.json
currently processing:  Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json
currently processing:  Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json
currently processing:  Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.json
currently processing:  Hagecius1596_Actio_medica_ER_UBB.json
currently processing:  Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json
currently processing:  Witestein1583_Disceptatio_philosophica_MDZ_MBS.json
currently processing:  Moffett1588_Nosomantica_Hippocrates_ONB.json
currently processing:  Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.json
currently processing:  Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.json
currently processing:  Trevisanus1583_De_chymico_miraculo_MDZ_MBS.json
currently processing:  Libavius1594_Neoparacelsica_MDZ_MBS.json
currently processing:  Suchten1575_De_secretis_antimonii_ONB.json
currently processing:  Wecker1582_De_secretis_ONB.json
currently processing:  Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.json
currently processing:  Severinus1571_Idea_medicinae_MDZ_MBS.json
currently processing:  Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.json
currently processing:  Pseudo-Lull1566_Testamentum_MDZ_MBS.json
currently processing:  Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.json
currently processing:  Greverus1599_Secretum_MDZ_MBS.json
currently processing:  Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.json
currently processing:  Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.json
CPU times: user 5min 26s, sys: 12.9 s, total: 5min 38s
Wall time: 5min 38s

In [104]:
fns_jsons = os.listdir(target_path)
fns_jsons[:10]

['100044.json',
 '100034.json',
 '100014.json',
 '100060.json',
 '100010.json',
 '100068.json',
 '100043.json',
 '100072.json',
 '100041.json',
 '100012.json']

In [105]:
len(fns_jsons)

75

In [99]:
sents_data = json.load(open(target_path + fns_jsons[20], "r"))
sents_data[100:103]

[[100042,
  100,
  'Quare certius atque perfectius alio quouis docere potest:',
  [['Quare', 'quare', 'ADV', [0, 5], [18], [7]],
   ['certius', 'certior', 'ADV', [6, 13], [18], [7]],
   ['atque', 'atque', 'CCONJ', [14, 19], [18], [7]],
   ['perfectius', 'perfectior', 'ADV', [20, 30], [18], [7]],
   ['alio', 'alius', 'DET', [31, 35], [18], [7]],
   ['quouis', 'quiuis', 'ADV', [36, 42], [18], [8]],
   ['docere', 'doceo', 'VERB', [43, 49], [18], [8]],
   ['potest', 'possum', 'VERB', [50, 56], [18], [8]],
   [':', ':', 'PUNCT', [56, 57], [18], [8]]]],
 [100042,
  101,
  'item absolute nos ab eo discere ualemus, quod loquitur inquiens:',
  [['item', 'item', 'ADV', [0, 4], [18], [8]],
   ['absolute', 'absolute', 'ADV', [5, 13], [18], [8]],
   ['nos', 'nos', 'PRON', [14, 17], [18], [8]],
   ['ab', 'ab', 'ADP', [18, 20], [18], [8]],
   ['eo', 'is', 'PRON', [21, 23], [18], [9]],
   ['discere', 'disco', 'VERB', [24, 31], [18], [9]],
   ['ualemus', 'ualeo', 'VERB', [32, 39], [18], [9]],
   [',', ',', 'PUNCT', [39, 40], [18], [9]],
   ['quod', 'quod', 'SCONJ', [41, 45], [18], [9]],
   ['loquitur', 'loquor', 'VERB', [46, 54], [18], [9]],
   ['inquiens', 'inquam', 'VERB', [55, 63], [18], [9]],
   [':', ':', 'PUNCT', [63, 64], [18], [9]]]],
 [100042,
  102,
  'A me discetis omnia:',
  [['A', 'ab', 'ADP', [0, 1], [18], [10]],
   ['me', 'ego', 'PRON', [2, 4], [18], [10]],
   ['discetis', 'disco', 'VERB', [5, 13], [18], [10]],
   ['omnia', 'omnis', 'DET', [14, 19], [18], [10]],
   [':', ':', 'PUNCT', [19, 20], [18], [10]]]]]

In [108]:
lemmatized_sents_path = "/srv/data/tome/tome-corpus/lemmatized_sents_v3-0/"
try:
    os.mkdir(lemmatized_sents_path)
except:
    pass

In [109]:
os.listdir(lemmatized_sents_path)

[]

In [110]:
for fn in fns_jsons:
    lemmatized_sents = []
    sents_data = json.load(open(target_path + fn, "rb"))
    print(fn)
    for (doc_id, sent_id, sent_text, sent_data) in sents_data:
        lemmasent = []
        for wordform, lemma, tag, position, t_pages, t_textblocks in sent_data:
            if tag in ["NOUN", "PROPN", "ADJ", "VERB"]:
                lemmasent.append(lemma)
        lemmatized_sents.append(" ".join(lemmasent) + "\n")
    with open(lemmatized_sents_path + fn.replace(".json", ".txt"), "w", encoding="utf-8") as f:
        f.writelines(lemmatized_sents)

100044.json
100034.json
100014.json
100060.json
100010.json
100068.json
100043.json
100072.json
100041.json
100012.json
100025.json
100019.json
100047.json
100013.json
100028.json
100073.json
100070.json
100048.json
100038.json
100035.json
100042.json
100071.json
100053.json
100003.json
100059.json
100002.json
100049.json
100032.json
100052.json
100066.json
100045.json
100051.json
100001.json
100054.json
100065.json
100064.json
100004.json
100050.json
100046.json
100069.json
100058.json
100062.json
100033.json
100006.json
100029.json
100017.json
100061.json
100007.json
100074.json
100027.json
100063.json
100037.json
100067.json
100026.json
100023.json
100056.json
100024.json
100040.json
100021.json
100055.json
100005.json
100030.json
100018.json
100020.json
100009.json
100075.json
100008.json
100031.json
100015.json
100039.json
100036.json
100057.json
100016.json
100022.json
100011.json