# About this notebook.

This notebook goes through all the texts and aplies on them a NLP pipeline consisting of (1) cleaning of the raw text, (2) sentence tokenization, (3) part-of-speech annotation, (4) lemmatization, and (5) named entity recognition.

The processed textual data are saved for future reuse.

In [3]:
import spacy
import os
import glob
from spacy.tokens import Doc
from spacy.language import Language
import pickle
from unidecode import unidecode
import sddk
import pandas as pd
import re
import sys
import importlib
import json
from spacy.tokens import Token
from spacy.language import Language

In [94]:
import pandas as pd

# Convert the sharing URL to a CSV export URL
sheet_id = "1bkHHTYc86K2IuEXqfYfkDNt5LovtvCU3gvqHIbVio88"
sheet_name = "Catalogue"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

# Read directly into pandas
emlap_metadata = pd.read_csv(url, index_col=0).T
emlap_metadata.reset_index(inplace=True, names=["Author"])
emlap_metadata.head(5)

,Author,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,genre,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments
0,"Augurello, Chrysopoeia",100001,TRUE,TRUE,713324,NaN,NaN,TRUE,NaN,TRUE,...,Didactic Poem,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,Noscemus,Unknown,NaN,Noscemus Wiki,Soranzo 2019,The 1518 Basel version is also in Noscemus
1,"Pseudo-Lull, Secretis",100002,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,Treatise,NaN,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,Hirsch 1950,NaN,"There is a prior, 1514 edition of De secretis ..."
2,"Pantheus, Ars Transmutatione",100003,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,Treatise,NaN,NaN,NaN,GB,BL,NaN,NaN,NaN,This book was first published in 1518 with an ...
3,"Pantheus, Commentarium",100004,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,Treatise,alchemy,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MSB,NaN,NaN,NaN,This 1519 book is catalogued wrongly by many l...
4,"Pantheus, Voarchadumia",100005,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,Treatise,NaN,NaN,NaN,ONB,ONB,NaN,NaN,NaN,Dedicated to Leonellus Marquis of Estense

In [95]:
emlap_automapping = pd.read_csv("../data/emlap_automapping.csv")
emlap_automapping["No."].tolist()

[100001.0,
 100002.0,
 100003.0,
 100004.0,
 100005.0,
 100006.0,
 nan,
 100008.0,
 100009.0,
 100010.0,
 100011.0,
 100012.0,
 100013.0,
 100014.0,
 100015.0,
 100016.0,
 100017.0,
 100018.0,
 100019.0,
 nan,
 100021.0,
 nan,
 100023.0,
 100024.0,
 100025.0,
 100026.0,
 100027.0,
 100028.0,
 100029.0,
 100030.0,
 nan,
 100032.0,
 100033.0,
 100034.0,
 nan,
 100036.0,
 100037.0,
 100038.0,
 100039.0,
 100040.0,
 nan,
 100042.0,
 100043.0,
 100044.0,
 100045.0,
 nan,
 100047.0,
 100048.0,
 100049.0,
 nan,
 nan,
 100052.0,
 100053.0,
 100054.0,
 100055.0,
 100056.0,
 nan,
 nan,
 100059.0,
 100060.0,
 100061.0,
 100062.0,
 100063.0,
 100064.0,
 nan,
 100066.0,
 nan,
 nan,
 100069.0,
 100070.0,
 nan,
 100072.0,
 100073.0,
 100074.0,
 100075.0]

In [96]:
emlap_automapping = emlap_automapping[emlap_automapping["No."].notnull()]
emlap_automapping["No."] = emlap_automapping["No."].astype(int).astype(str)

In [97]:
emlap_id_file_dict = dict(zip(emlap_automapping["No."], emlap_automapping["autofile"]))
emlap_id_file_dict

{'100001': nan,
 '100002': 'Pseudo-Lull1518_De_secretis_naturae_MDZ.json',
 '100003': 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 '100004': 'Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json',
 '100005': 'Pantheus1530_Voarchadumia_ONB.json',
 '100006': 'Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json',
 '100008': 'Severinus1572_Epistola_MBZ_MBS.json',
 '100009': 'Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json',
 '100010': 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json',
 '100011': 'De_alchemia1541_MDZ_MBS.json',
 '100012': 'Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json',
 '100013': 'Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json',
 '100014': 'Toxites1567_Spongia_stibii_MDZ_MBS.json',
 '100015': 'Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json',
 '100016': 'Bonus1546_Pretiosa_Margarita_Novella_ONB.json',
 '100017': 'Bodenstein1559_Isagoge_MDZ_MBS.json',
 '100018': nan,
 '100019': 'Ulstadt1526_De_epidemia_ONB.json',
 '100021': 'Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json',
 '100023': 'Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json',
 '100024': 'Fanianus1560_De_arte_metallicae_ONB_pdf.json',
 '100025': 'Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json',
 '100026': 'Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json',
 '100027': 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 '100028': 'Pedemontanus1563_De_Secretis_MDZ_MBS.json',
 '100029': 'Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json',
 '100030': 'Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json',
 '100032': 'Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json',
 '100033': 'Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json',
 '100034': 'Penotus1594_Tractatus_varii_MDZ_MBS.json',
 '100036': 'Vadis1595_Dialogus_IA_Wellcome.json',
 '100037': 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
 '100038': 'Auriferae_artisI1572_MBZ_Augsburg.json',
 '100039': 'Pseudo-Democritus1572_Ars_magna.json',
 '100040': 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 '100042': 'Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json',
 '100043': 'DuChesne1575_Sclopetarius_MDZ_Augsburg.json',
 '100044': 'Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json',
 '100045': 'Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json',
 '100047': 'Portaleone1584_De_auro_dialogi_tres_ONB.json',
 '100048': 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 '100049': 'Rossi1585_De_destillatione_MDZ_MBS.json',
 '100052': 'Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json',
 '100053': 'Mirandola1586_De_auro_libri_tres_MDZ_MBS.json',
 '100054': 'Moffett_De_iure_et_praestantia_MDZ_MBS.json',
 '100055': 'Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json',
 '100056': 'Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json',
 '100059': 'Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json',
 '100060': 'Witestein1583_Disceptatio_philosophica_MDZ_MBS.json',
 '100061': nan,
 '100062': nan,
 '100063': nan,
 '100064': nan,
 '100066': nan,
 '100069': nan,
 '100070': nan,
 '100072': nan,
 '100073': nan,
 '100074': nan,
 '100075': nan}

In [99]:
emlap_metadata["filename"] = emlap_metadata["No."].apply(lambda x:  emlap_id_file_dict.get(x, None))
emlap_metadata.head(5)

,Author,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments,filename
0,"Augurello, Chrysopoeia",100001,TRUE,TRUE,713324,NaN,NaN,TRUE,NaN,TRUE,...,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,Noscemus,Unknown,NaN,Noscemus Wiki,Soranzo 2019,The 1518 Basel version is also in Noscemus,NaN
1,"Pseudo-Lull, Secretis",100002,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,Hirsch 1950,NaN,"There is a prior, 1514 edition of De secretis ...",Pseudo-Lull1518_De_secretis_naturae_MDZ.json
2,"Pantheus, Ars Transmutatione",100003,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,NaN,GB,BL,NaN,NaN,NaN,This book was first published in 1518 with an ...,Pantheus1518_Ars_Transmutationis_Metallicae_BL...
3,"Pantheus, Commentarium",100004,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,alchemy,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MSB,NaN,NaN,NaN,This 1519 book is catalogued wrongly by many l...,Pantheus1519_Commentarium_Transmutationis_Meta...
4,"Pantheus, Voarchadumia",100005,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,NaN,ONB,ONB,NaN,NaN,NaN,Dedicated to Leonellus Marquis of Estense,Pantheus1530_Voarchadumia_ONB.json

For preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level one level up.

The module can be clonned from here: https://github.com/CCS-ZCU/latin-preprocessing and imported to python following the steps below:

In [100]:
# for preprocessing the latin texts, we will use a module located outside of the current repository, specifically at the same level as the current project.
current_working_directory = os.getcwd()
relative_path = '../../latin-preprocessing/' # change according to your location...
module_path = os.path.abspath(os.path.join(current_working_directory, relative_path))
if module_path not in sys.path:
    sys.path.insert(0, module_path)
# Now import the module
import tomela

Tomela contains tuned latin preprocessing pipeline relying on spaCy and latinCy. You can check the pipeline as here:

In [101]:
tomela.nlp.pipeline

[('source_tracker', <function __main__.source_tracker(doc)>),
 ('senter', <spacy.pipeline.senter.SentenceRecognizer at 0x702cc483af30>),
 ('normer', <function la_core_web_lg.functions.normer(doc)>),
 ('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x702cc483ac30>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x702cc483ab10>),
 ('morphologizer',
  <spacy.pipeline.morphologizer.Morphologizer at 0x702cc483bd70>),
 ('trainable_lemmatizer',
  <spacy.pipeline.edit_tree_lemmatizer.EditTreeLemmatizer at 0x702d6ff3fdd0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x702d6ffcdb60>),
 ('lookup_lemmatizer',
  <function la_core_web_lg.functions.make_lookup_lemmatizer_function(doc)>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x702cc4c58b30>)]

In [114]:
tomela.nlp.max_length = 4000000

In [102]:
doc = tomela.nlp("Veritas, vt vlla dicit, semper est universalis et a principiis fundamentalis oritur (lib. 3, cap. VI)")
for token in doc:
    print((token.text, token.lemma_, token.pos_))

('Veritas', 'ueritas', 'NOUN')
(',', ',', 'PUNCT')
('vt', 'vt', 'ADV')
('vlla', 'vllus', 'NOUN')
('dicit', 'dico', 'VERB')
(',', ',', 'PUNCT')
('semper', 'semper', 'ADV')
('est', 'sum', 'AUX')
('universalis', 'uniuersalis', 'ADJ')
('et', 'et', 'CCONJ')
('a', 'ab', 'ADP')
('principiis', 'principium', 'NOUN')
('fundamentalis', 'fundamentalis', 'ADJ')
('oritur', 'orior', 'VERB')
('(', '(', 'PUNCT')
('lib', 'liber', 'NOUN')
('.', '.', 'PUNCT')
('3', '3', 'NUM')
(',', ',', 'PUNCT')
('cap', 'capitulum', 'NOUN')
('.', '.', 'PUNCT')
('VI', 'uis', 'NUM')
(')', ')', 'PUNCT')

In [103]:
source_path = "/srv/data/tome/tome-corpus/emlap_annotated_textblocks/"
len(os.listdir(source_path))

118

In [104]:
[f for f in sorted(os.listdir(source_path)) if "_params" not in f]

['Anon1550_De_alchemia_opuscula_MDZ_MBS.json',
 'Anon1550_Rosarium_philosophorum_Erara.json',
 'Auriferae_artisI1572_MBZ_Augsburg.json',
 'Barnaud1599_Quadriga_aurifera_IA_Madrid.json',
 'Bodenstein1559_Isagoge_MDZ_MBS.json',
 'Bonus1546_Pretiosa_Margarita_Novella_ONB.json',
 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json',
 'Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json',
 'De_alchemia1541_MDZ_MBS.json',
 'Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json',
 'Dorn1569_Artificii_chymistici_MDZ_MBS.json',
 'Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.json',
 'Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json',
 'Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json',
 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
 'DuChesne1575_Sclopetarius_MDZ_Augsburg.json',
 'Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json',
 'Fanianus1560_De_arte_metallicae_ONB_pdf.json',
 'Fanianus1576_De_arte_metallicae_MDZ_MBS.json',
 'Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json',
 'Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json',
 'Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json',
 'Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.json',
 'Hagecius1596_Actio_medica_ER_UBB.json',
 'Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json',
 'Mirandola1586_De_auro_libri_tres_MDZ_MBS.json',
 'Moffett_De_iure_et_praestantia_MDZ_MBS.json',
 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 'Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json',
 'Pantheus1530_Voarchadumia_ONB.json',
 'Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json',
 'Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json',
 'Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json',
 'Pedemontanus1563_De_Secretis_MDZ_MBS.json',
 'Penotus1594_Tractatus_varii_MDZ_MBS.json',
 'Phaedro1562_Aquila_coelestis_MBZ_MBS.json',
 'Portaleone1584_De_auro_dialogi_tres_ONB.json',
 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 'Pseudo-Democritus1572_Ars_magna.json',
 'Pseudo-Lull1518_De_secretis_naturae_MDZ.json',
 'Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json',
 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 'Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json',
 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 'Rossi1585_De_destillatione_MDZ_MBS.json',
 'Ruland1564_Medicina_practica_recens_MDZ_MDS.json',
 'Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json',
 'Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json',
 'Senior1560_De_chemia_senioris_MDZ_MBS.json',
 'Severinus1572_Epistola_MBZ_MBS.json',
 'Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json',
 'Toxites1567_Spongia_stibii_MDZ_MBS.json',
 'Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json',
 'Ulstadt1526_De_epidemia_ONB.json',
 'Vadis1595_Dialogus_IA_Wellcome.json',
 'Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json',
 'Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json',
 'Wecker1582_De_secretis_ONB.json',
 'Witestein1583_Disceptatio_philosophica_MDZ_MBS.json']

In [105]:
files_overview = []
for filename in os.listdir(source_path):
    #filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
    if "_params" not in filename:
        filepath = os.path.join(source_path, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            textblocks = json.load(f)
        pages_n = len(textblocks)
        chars_n = sum([sum([len(tb["text"]) for tb in p]) for p in textblocks])
        files_overview.append({"filename" : filename, "pages_n" : pages_n, "chars_n" : chars_n})
pd.DataFrame(files_overview)

                                             filename  pages_n  chars_n
0         Moffett_De_iure_et_praestantia_MDZ_MBS.json      115   120620
1             Toxites1567_Spongia_stibii_MDZ_MBS.json       21    14543
2      Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json      405   340776
3   Pantheus1518_Ars_Transmutationis_Metallicae_BL...       53    49495
4   Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_...       69   105063
5   Pseudo-Paracelsus1568_Pyrophilia_vexationumque...      153   136322
6   Bracesco1548_De_alchemia_dialogi_II_IA_Madrid....      131   246242
7   Hagecius1585_De_cervisia_ejusque_conficiendi_r...       65    73530
8           Pedemontanus1563_De_Secretis_MDZ_MBS.json      551   581004
9           Phaedro1562_Aquila_coelestis_MBZ_MBS.json       55    15562
10  Suavius1567_Theophrasti_Paracelsi_Philosophiae...      417   481870
11                   Ulstadt1526_De_epidemia_ONB.json      193   185046
12  Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_...      519   629295
13  Dorn1567_Clavis_totius_philosophiae_chymistica...      313   214749
14      Bonus1546_Pretiosa_Margarita_Novella_ONB.json      485   749662
15             Auriferae_artisI1572_MBZ_Augsburg.json     1343  1509719
16  Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json      198   148955
17  Pantheus1519_Commentarium_Transmutationis_Meta...       73    19292
18         Anon1550_De_alchemia_opuscula_MDZ_MBS.json      352   430390
19  Ventura1571_De_ratione_conficiendi_lapis_MBZ_M...      547   632506
20      Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json      457   559059
21   DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json       93    90637
22         Anon1550_Rosarium_philosophorum_Erara.json      202   222882
23      Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json      233   233328
24       Barnaud1599_Quadriga_aurifera_IA_Madrid.json       97   130063
25                Severinus1572_Epistola_MBZ_MBS.json       23    14718
26         Dorn1569_Artificii_chymistici_MDZ_MBS.json      465   537079
27  Rupescissa1561_De_Consideratione_Quintae_essen...      361   334803
28  Savonarola1532_De_arte_conficiendi_aquam_vitae...      111    93362
29                Vadis1595_Dialogus_IA_Wellcome.json      196   159459
30      Mirandola1586_De_auro_libri_tres_MDZ_MBS.json      141   183230
31       Pseudo-Lull1518_De_secretis_naturae_MDZ.json       62   144113
32                 Pantheus1530_Voarchadumia_ONB.json      147   119910
33  Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ....      633   555669
34  Khunrath1599_Confessio_de_chao_chymicorum_MDZ_...       96    31333
35  Erastus1578_Disputatio_de_auro_potabili_MDZ_MB...      193   197643
36  Paracelsus1582_Centum_quindecim_curationes_MDZ...      201   208304
37  Witestein1583_Disceptatio_philosophica_MDZ_MBS...      241   289377
38   Ruland1564_Medicina_practica_recens_MDZ_MDS.json      313   206239
39                       De_alchemia1541_MDZ_MBS.json      403   537945
40       Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.json      151   172050
41         Senior1560_De_chemia_senioris_MDZ_MBS.json      137   126250
42  Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json      113   237793
43       Portaleone1584_De_auro_dialogi_tres_ONB.json      223   168177
44       Fanianus1560_De_arte_metallicae_ONB_pdf.json       57    52263
45        DuChesne1575_Sclopetarius_MDZ_Augsburg.json      245   239637
46  Vegius1518_Inter_inferiora_corpora_disputatio_...       89   162186
47  Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ...      103    86874
48  Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS...      329   351171
49  Pseudo-Paracelsus1568_De_summis_naturae_myster...      177   179729
50        Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json      281   210381
51            Rossi1585_De_destillatione_MDZ_MBS.json      305   396249
52           Penotus1594_Tractatus_varii_MDZ_MBS.json      257   244502
53                Bodenstein1559_Isagoge_MDZ_MBS.json      141    91305
54              Hagecius1596_Actio_medica_ER_UBB.json       89   104677
55                    Wecker1582_De_secretis_ONB.json     1015  1317506
56  Paracelsus1553_Labyrinthus_medicorum_errantium...       95   173322
57       Fanianus1576_De_arte_metallicae_MDZ_MBS.json      129    96521
58               Pseudo-Democritus1572_Ars_magna.json      153   174854


# Develop and test with one example test

In [106]:
filename = 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json'
filepath = os.path.join(source_path, filename)
with open(filepath, 'r', encoding='utf-8') as f:
    textblocks = json.load(f)

In [107]:
len(textblocks)

93

In [108]:
textblocks[30][:10]

[{'coordinates': [165.1199951171875,
   40.31997299194336,
   427.239990234375,
   48.62395477294922],
  'text': '14\nRESPONSIO\n',
  'tag': 'header'},
 {'coordinates': [165.1199951171875,
   69.11996459960938,
   512.6112670898438,
   73.91996002197266],
  'text': 'calculo aut renum tartaro, tanta vi pro¬\n',
  'tag': 'text'},
 {'coordinates': [165.1199951171875,
   93.3840103149414,
   515.9405517578125,
   98.30400848388672],
  'text': 'desse diceres? Intelligo, Confugeres\n',
  'tag': 'text'},
 {'coordinates': [165.1199951171875,
   116.66397857666016,
   512.2813720703125,
   121.58397674560547],
  'text': 'ad sacram asinorum anchoram, nem¬\n',
  'tag': 'text'},
 {'coordinates': [168.72000122070312,
   140.87997436523438,
   509.6862487792969,
   145.6799774169922],
  'text': 'pe proprietatum occultarum: quod ta¬\n',
  'tag': 'text'},
 {'coordinates': [169.1999969482422,
   165.11996459960938,
   515.7952880859375,
   169.9199676513672],
  'text': 'men ipso sale fieri, qui illos resoluit, &\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   188.16000366210938,
   513.2568359375,
   192.9600067138672],
  'text': 'per vrinas expellit, ratio ipsa docet.\n',
  'tag': 'text'},
 {'coordinates': [170.8800048828125,
   211.94400024414062,
   511.9048156738281,
   216.86399841308594],
  'text': 'Quid ergo diceres de Troglodyte lau¬\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   235.94400024414062,
   511.7084655761719,
   240.86399841308594],
  'text': 'datissimo illo antiquorum medicamen¬\n',
  'tag': 'text'},
 {'coordinates': [167.52000427246094,
   259.6799621582031,
   512.2210693359375,
   264.4799499511719],
  'text': 'to ad eandem affectionem, cuius me¬\n',
  'tag': 'text'}]

In [109]:

# Modify the token extensions for simpler output
if not Token.has_extension("pages"):
    Token.set_extension("pages", default=None)
if not Token.has_extension("textblocks"):
    Token.set_extension("textblocks", default=None)
if not Doc.has_extension("char_to_source"):
    Doc.set_extension("char_to_source", default=None)


def process_textblocks(textblocks):
    full_text = ""
    char_to_source = {}

    for page_idx, page in enumerate(textblocks):
        for tb_idx, tb in enumerate(page):
            if tb["tag"] == "text":
                start_idx = len(full_text)
                text = tomela.text_cleaner(tb["text"])

                for char_idx in range(len(text)):
                    char_to_source[start_idx + char_idx] = {
                        "page_idx": page_idx,
                        "textblock_idx": tb_idx
                    }

                full_text += text

    return full_text, char_to_source


@Language.component("source_tracker")
def source_tracker(doc):
    if doc._.char_to_source is not None:
        for token in doc:
            # Get the character span of the entire token
            token_char_range = range(token.idx, token.idx + len(token.text))

            pages = set()
            textblocks = set()

            for char_idx in token_char_range:
                if char_idx in doc._.char_to_source:
                    source_info = doc._.char_to_source[char_idx]
                    pages.add(source_info["page_idx"])
                    textblocks.add(source_info["textblock_idx"])

            token._.pages = sorted(list(pages))
            token._.textblocks = sorted(list(textblocks))
    return doc


# Add the custom component to your existing pipeline if not already added
if "source_tracker" not in tomela.nlp.pipe_names:
    tomela.nlp.add_pipe("source_tracker", before="senter")


def process_with_source_tracking(textblocks, nlp):
    full_text, char_to_source = process_textblocks(textblocks)
    # Create the doc with the text
    doc = nlp.make_doc(full_text)
    # Set the char_to_source before running the pipeline
    doc._.char_to_source = char_to_source
    # Process the doc through each pipeline component
    for name, proc in nlp.pipeline:
        doc = proc(doc)
    return doc

In [110]:
textblocks[21:22]

[[{'coordinates': [146.63999938964844,
    46.55996322631836,
    435.6400146484375,
    51.599952697753906],
   'text': '5\nAD AVBERTVM.\n',
   'tag': 'header'},
  {'coordinates': [88.55999755859375,
    74.66397857666016,
    435.73681640625,
    79.58397674560547],
   'text': 'naturae iuuandum robur, & aduersus af¬\n',
   'tag': 'text'},
  {'coordinates': [91.19999694824219,
    98.66397857666016,
    444.1780700683594,
    103.58397674560547],
   'text': 'fectus melancholicos, ad exolutum ven¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    122.87997436523438,
    438.64984130859375,
    127.67996978759766],
   'text': 'triculum; ad cardiacos, & praeter ratio¬\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    146.87997436523438,
    441.6309814453125,
    151.6799774169922],
   'text': 'nem moestos efficax remedium. Certe\n',
   'tag': 'text'},
  {'coordinates': [89.27999877929688,
    172.31997680664062,
    441.3201904296875,
    177.11997985839844],
   'text': 'in ipsius essentia, quàm in tuo auro fo¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    195.60000610351562,
    444.3800354003906,
    200.40000915527344],
   'text': 'liato, multò maiorem facultatem inesse\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    220.31997680664062,
    438.85797119140625,
    225.11997985839844],
   'text': 'meritò credideris. Dabis & illud, mi\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    244.55996704101562,
    437.1007995605469,
    249.35997009277344],
   'text': 'Auberte, in eo purissimo, vim illam oc¬\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    268.5839538574219,
    438.9518737792969,
    273.50396728515625],
   'text': 'cultarum proprietatum maiorem esse,\n',
   'tag': 'text'},
  {'coordinates': [91.44000244140625,
    292.8240051269531,
    439.442626953125,
    297.7440185546875],
   'text': 'quàm in tuis iusculis cum auro coctis.\n',
   'tag': 'text'},
  {'coordinates': [95.04000091552734,
    316.5839538574219,
    436.8152770996094,
    321.50396728515625],
   'text': 'Nec tamen, puto, credes (hoc enim ni¬\n',
   'tag': 'text'},
  {'coordinates': [88.08000183105469,
    341.7599792480469,
    437.74407958984375,
    346.5599670410156],
   'text': 'mis esset absurdum) aurum, quod ne i¬\n',
   'tag': 'text'},
  {'coordinates': [88.80000305175781,
    366.0,
    441.1604309082031,
    370.79998779296875],
   'text': 'gnis quidem ardore torreri absumive\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    391.4639892578125,
    170.05992126464844,
    396.3840026855469],
   'text': 'potest¬\n',
   'tag': 'text'},
  {'coordinates': [96.0,
    413.7839660644531,
    440.809814453125,
    418.7039794921875],
   'text': '"(Vni enim (vt scribit Poeta) nil deperit aurò\n',
   'tag': 'text'},
  {'coordinates': [89.76000213623047,
    438.50396728515625,
    438.0096435546875,
    443.4239807128906],
   'text': 'Igne, velut solum consumit nulla vetustas,\n',
   'tag': 'text'},
  {'coordinates': [89.27999877929688,
    462.47998046875,
    440.6310729980469,
    467.27996826171875],
   'text': 'Ac neque rubigo, aut aerugo conficit vlla:\xa0\n',
   'tag': 'text'},
  {'coordinates': [97.68000030517578,
    486.9599914550781,
    434.4278869628906,
    491.7599792480469],
   'text': 'Cuncta adeò firmis illic compagibus haerent)"\n',
   'tag': 'text'},
  {'coordinates': [89.76000213623047,
    511.9200134277344,
    446.9093933105469,
    516.7200317382812],
   'text': 'à natiuo calore decoqui aut deuinci\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    536.1840209960938,
    438.8242492675781,
    541.10400390625],
   'text': 'ita posse, quin cor, integra remanente\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    560.1840209960938,
    439.9804382324219,
    565.10400390625],
   'text': 'illius substantia, ipso corroborari quo¬\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    584.9039916992188,
    438.4349060058594,
    589.823974609375],
   'text': 'dammodo queat: quum sit haec Philoso¬\n',
   'tag': 'text'},
  {'coordinates': [88.55999755859375,
    609.6240234375,
    446.4131164550781,
    614.5440063476562],
   'text': 'phorum sententia, Terram videlicet\n',
   'tag': 'text'},
  {'coordinates': [88.55999755859375,
    633.1199340820312,
    442.3680419921875,
    637.9199829101562],
   'text': 'omnem esse mortuam, & spiritus rerum\n',
   'tag': 'text'},
  {'coordinates': [91.91999816894531,
    656.8799438476562,
    435.6803894042969,
    661.6799926757812],
   'text': 'in corporibus solos agere posse.\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    681.3839721679688,
    446.1756286621094,
    686.303955078125],
   'text': 'Caeterum Laudanum ipsum quanuis\n',
   'tag': 'text'},
  {'coordinates': [90.72000122070312,
    706.10400390625,
    447.25701904296875,
    711.0239868164062],
   'text': 'opiaticum, non ita tamen conuitiis est\n',
   'tag': 'text'},
  {'coordinates': [346.32000732421875,
    730.583984375,
    398.04974365234375,
    735.5039672851562],
   'text': 'B.iij.\n',
   'tag': 'footer'}]]

In [111]:
doc = process_with_source_tracking(textblocks, tomela.nlp)

In [112]:
doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)), t._.pages, t._.textblocks) for t in sent]) for sent in doc.sents]
sent_data_updated = []
for n_sent, sent_data in enumerate(doc_sentdata):
    sent_data_updated.append((filename, n_sent, sent_data[0], sent_data[1]))

In [113]:
sent_data_updated[500:505]

[('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  500,
  'patrocinandonobis ipsis contradicere putet Aubertus) & grauis immixta terrae tenuissimaesulphuree, quae dicitur argentum uiuum,ex quo tanquam propinquiore materiamediante mixtione & actione sulphuris extrinseci, fit aurum, uel metallumaliud secundum maiorem aut minoremdigestionem ipsius naturae.',
  [('patrocinandonobis', 'patrocinandonobum', 'NOUN', (0, 17), [62], [8, 9]),
   ('ipsis', 'ipse', 'DET', (18, 23), [62], [9]),
   ('contradicere', 'contradico', 'VERB', (24, 36), [62], [9]),
   ('putet', 'puto', 'VERB', (37, 42), [62], [9]),
   ('Aubertus', 'Aubertus', 'PROPN', (43, 51), [62], [9, 10]),
   (')', ')', 'PUNCT', (51, 52), [62], [10]),
   ('&', '&', 'PUNCT', (53, 54), [62], [10]),
   ('grauis', 'grauis', 'ADJ', (55, 61), [62], [10]),
   ('immixta', 'immisceo', 'VERB', (62, 69), [62], [10]),
   ('terrae', 'terra', 'NOUN', (70, 76), [62], [10]),
   ('tenuissimaesulphuree',
    'tenuissimaesulphureus',
    'ADJ',
    (77, 97),
    [62],
    [10, 11]),
   (',', ',', 'PUNCT', (97, 98), [62], [11]),
   ('quae', 'qui', 'PRON', (99, 103), [62], [11]),
   ('dicitur', 'dico', 'VERB', (104, 111), [62], [11]),
   ('argentum', 'argentum', 'NOUN', (112, 120), [62], [11]),
   ('uiuum', 'uiuum', 'ADJ', (121, 126), [62], [11]),
   (',', ',', 'PUNCT', (126, 127), [62], [11]),
   ('ex', 'ex', 'ADP', (127, 129), [62], [12]),
   ('quo', 'qui', 'PRON', (130, 133), [62], [12]),
   ('tanquam', 'tamquam', 'ADV', (134, 141), [62], [12]),
   ('propinquiore', 'propinquior', 'ADJ', (142, 154), [62], [12]),
   ('materiamediante', 'materiamedio', 'VERB', (155, 170), [62], [12, 13]),
   ('mixtione', 'mixtio', 'NOUN', (171, 179), [62], [13]),
   ('&', '&', 'PUNCT', (180, 181), [62], [13]),
   ('actione', 'actio', 'NOUN', (182, 189), [62], [13]),
   ('sulphuris', 'sulphur', 'NOUN', (190, 199), [62], [13, 14]),
   ('extrinseci', 'extrinsecus', 'ADJ', (200, 210), [62], [14]),
   (',', ',', 'PUNCT', (210, 211), [62], [14]),
   ('fit', 'facio', 'VERB', (212, 215), [62], [14]),
   ('aurum', 'aurum', 'NOUN', (216, 221), [62], [14]),
   (',', ',', 'PUNCT', (221, 222), [62], [14]),
   ('uel', 'uel', 'CCONJ', (223, 226), [62], [14]),
   ('metallumaliud', 'metallumaliud', 'NOUN', (227, 240), [62], [14, 15]),
   ('secundum', 'secundum', 'ADP', (241, 249), [62], [15]),
   ('maiorem', 'maior', 'ADJ', (250, 257), [62], [15]),
   ('aut', 'aut', 'CCONJ', (258, 261), [62], [15]),
   ('minoremdigestionem',
    'minoremdigestio',
    'NOUN',
    (262, 280),
    [62],
    [15, 16]),
   ('ipsius', 'ipse', 'DET', (281, 287), [62], [16]),
   ('naturae', 'natura', 'NOUN', (288, 295), [62], [16]),
   ('.', '.', 'PUNCT', (295, 296), [62], [16])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  501,
  'Nam ut scribitPhilosophus Metaph. 6.',
  [('Nam', 'nam', 'PART', (0, 3), [62], [16]),
   ('ut', 'ut', 'SCONJ', (4, 6), [62], [16]),
   ('scribitPhilosophus',
    'scribitPhilosophus',
    'NOUN',
    (7, 25),
    [62],
    [16, 17]),
   ('Metaph', 'Metaphus', 'PROPN', (26, 32), [62], [17]),
   ('.', '.', 'PUNCT', (32, 33), [62], [17]),
   ('6', '6', 'NUM', (34, 35), [62], [17]),
   ('.', '.', 'PUNCT', (35, 36), [62], [17])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  502,
  'Quando aliquidfieri ex aliquo dicitur, fit aut ex medio& imperfecto extremum & perfectum, utex puero uir:',
  [('Quando', 'quando', 'SCONJ', (0, 6), [62], [17]),
   ('aliquidfieri', 'aliquidfieo', 'VERB', (7, 19), [62], [17, 18]),
   ('ex', 'ex', 'ADP', (20, 22), [62], [18]),
   ('aliquo', 'aliquis', 'PRON', (23, 29), [62], [18]),
   ('dicitur', 'dico', 'VERB', (30, 37), [62], [18]),
   (',', ',', 'PUNCT', (37, 38), [62], [18]),
   ('fit', 'facio', 'VERB', (39, 42), [62], [18]),
   ('aut', 'aut', 'CCONJ', (43, 46), [62], [18]),
   ('ex', 'ex', 'ADP', (47, 49), [62], [18]),
   ('medio', 'medius', 'ADJ', (50, 55), [62], [18]),
   ('&', '&', 'PUNCT', (55, 56), [62], [19]),
   ('imperfecto', 'imperfectus', 'ADJ', (57, 67), [62], [19]),
   ('extremum', 'extremus', 'NOUN', (68, 76), [62], [19]),
   ('&', '&', 'PUNCT', (77, 78), [62], [19]),
   ('perfectum', 'perfectus', 'ADJ', (79, 88), [62], [19]),
   (',', ',', 'PUNCT', (88, 89), [62], [19]),
   ('utex', 'utex', 'NOUN', (90, 94), [62], [19, 20]),
   ('puero', 'puer', 'NOUN', (95, 100), [62], [20]),
   ('uir', 'uir', 'NOUN', (101, 104), [62], [20]),
   (':', ':', 'PUNCT', (104, 105), [62], [20])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  503,
  'aut ex extremo extremum,ut ex aqua, aer.',
  [('aut', 'aut', 'CCONJ', (0, 3), [62], [20]),
   ('ex', 'ex', 'ADP', (4, 6), [62], [20]),
   ('extremo', 'extremus', 'ADJ', (7, 14), [62], [20]),
   ('extremum', 'extremus', 'ADJ', (15, 23), [62], [20]),
   (',', ',', 'PUNCT', (23, 24), [62], [20]),
   ('ut', 'ut', 'SCONJ', (24, 26), [62], [21]),
   ('ex', 'ex', 'ADP', (27, 29), [62], [21]),
   ('aqua', 'aqua', 'NOUN', (30, 34), [62], [21]),
   (',', ',', 'PUNCT', (34, 35), [62], [21]),
   ('aer', 'aer', 'NOUN', (36, 39), [62], [21]),
   ('.', '.', 'PUNCT', (39, 40), [62], [21])]),
 ('DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json',
  504,
  'Sed age, redeamus adnostrum Aubertum.',
  [('Sed', 'sed', 'CCONJ', (0, 3), [62], [21]),
   ('age', 'ago', 'VERB', (4, 7), [62], [21]),
   (',', ',', 'PUNCT', (7, 8), [62], [21]),
   ('redeamus', 'redeo', 'VERB', (9, 17), [62], [21]),
   ('adnostrum', 'adnoster', 'NOUN', (18, 27), [62], [21, 22]),
   ('Aubertum', 'Aubertus', 'PROPN', (28, 36), [62], [22]),
   ('.', '.', 'PUNCT', (36, 37), [62], [22])])]

In [43]:

# prepare function for working with segments...
def from_textblocks_to_doc(textblocks_pages):
    segment_len = 400
    if len(textblocks_pages) > segment_len: # if there is more than 400 pages
        segment_docs = []
        for n in range(0, len(textblocks_pages), segment_len):
            textblocks_segment = textblocks_pages[n:n+segment_len]
            segment_doc = process_with_source_tracking(textblocks_segment, tomela.nlp)

            segment_docs.append(segment_doc)
        doc = Doc.from_docs(segment_docs)
    else:
        doc = process_with_source_tracking(textblocks_pages, tomela.nlp)

    return doc

In [124]:
target_path = "/srv/data/tome/tome-corpus/sents_data_ids_jsons_v3-0/"
try:
    os.mkdir(target_path)
except:
    pass

In [125]:
emlap_metadata.head(5)

,Author,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments,filename
0,"Augurello, Chrysopoeia",100001,TRUE,TRUE,713324,NaN,NaN,TRUE,NaN,TRUE,...,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,Noscemus,Unknown,NaN,Noscemus Wiki,Soranzo 2019,The 1518 Basel version is also in Noscemus,NaN
1,"Pseudo-Lull, Secretis",100002,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN,Hirsch 1950,NaN,"There is a prior, 1514 edition of De secretis ...",Pseudo-Lull1518_De_secretis_naturae_MDZ.json
2,"Pantheus, Ars Transmutatione",100003,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,NaN,GB,BL,NaN,NaN,NaN,This book was first published in 1518 with an ...,Pantheus1518_Ars_Transmutationis_Metallicae_BL...
3,"Pantheus, Commentarium",100004,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,alchemy,NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MSB,NaN,NaN,NaN,This 1519 book is catalogued wrongly by many l...,Pantheus1519_Commentarium_Transmutationis_Meta...
4,"Pantheus, Voarchadumia",100005,TRUE,FALSE,NaN,NaN,NaN,TRUE,NaN,TRUE,...,NaN,NaN,NaN,ONB,ONB,NaN,NaN,NaN,Dedicated to Leonellus Marquis of Estense,Pantheus1530_Voarchadumia_ONB.json

In [126]:
%%time
source_path = "/srv/data/tome/tome-corpus/emlap_annotated_textblocks/"
for id, filename in zip(emlap_metadata["No."], emlap_metadata["filename"]):
#for filename in .listdir(source_path):
    #if "_params" not in filename:
    try:
        if id + ".json" not in os.listdir(target_path):
            filepath = os.path.join(source_path, filename)
            with open(filepath, 'r', encoding='utf-8') as f:
                textblocks_pages = json.load(f)
            print("currently processing: ", filename)
            doc = process_with_source_tracking(textblocks_pages, tomela.nlp)
            doc_sentdata = [(sent.text, [(t.text, t.lemma_, t.pos_, (t.idx - sent[0].idx, t.idx - sent[0].idx + len(t)), t._.pages, t._.textblocks) for t in sent]) for sent in doc.sents]
            sent_data_updated = []
            for n_sent, sent_data in enumerate(doc_sentdata):
                sent_data_updated.append((id, n_sent, sent_data[0], sent_data[1]))
            with open(target_path + id + ".json", "w") as f:
                json.dump(sent_data_updated, f)
    except:
        print("failed with file: ", filename)
        pass

failed with file:  nan
currently processing:  Pseudo-Lull1518_De_secretis_naturae_MDZ.json
currently processing:  Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json
currently processing:  Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.json
currently processing:  Pantheus1530_Voarchadumia_ONB.json
currently processing:  Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.json
failed with file:  None
currently processing:  Severinus1572_Epistola_MBZ_MBS.json
currently processing:  Vegius1518_Inter_inferiora_corpora_disputatio_ONB.json
currently processing:  Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json
currently processing:  De_alchemia1541_MDZ_MBS.json
currently processing:  Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.json
currently processing:  Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.json
currently processing:  Toxites1567_Spongia_stibii_MDZ_MBS.json
currently processing:  Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.json
currently processing:  Bonus1546_Pretiosa_Margarita_Novella_ONB.json
currently processing:  Bodenstein1559_Isagoge_MDZ_MBS.json
failed with file:  nan
currently processing:  Ulstadt1526_De_epidemia_ONB.json
failed with file:  None
currently processing:  Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.json
failed with file:  None
currently processing:  Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.json
currently processing:  Fanianus1560_De_arte_metallicae_ONB_pdf.json
currently processing:  Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.json
currently processing:  Garlandius1560_Compendium_Alchemiae_SLUB_pdf.json
currently processing:  Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json
currently processing:  Pedemontanus1563_De_Secretis_MDZ_MBS.json
currently processing:  Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.json
currently processing:  Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.json
failed with file:  None
currently processing:  Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.json
currently processing:  Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.json
currently processing:  Penotus1594_Tractatus_varii_MDZ_MBS.json
failed with file:  None
currently processing:  Vadis1595_Dialogus_IA_Wellcome.json
currently processing:  DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.json
currently processing:  Auriferae_artisI1572_MBZ_Augsburg.json
currently processing:  Pseudo-Democritus1572_Ars_magna.json
currently processing:  Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json
failed with file:  None
currently processing:  Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.json
currently processing:  DuChesne1575_Sclopetarius_MDZ_Augsburg.json
currently processing:  Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.json
currently processing:  Dorn1583_De_Naturae_luce_physica_MDZ_MBS.json
failed with file:  None
currently processing:  Portaleone1584_De_auro_dialogi_tres_ONB.json
currently processing:  Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json
currently processing:  Rossi1585_De_destillatione_MDZ_MBS.json
failed with file:  None
failed with file:  None
currently processing:  Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.json
currently processing:  Mirandola1586_De_auro_libri_tres_MDZ_MBS.json
currently processing:  Moffett_De_iure_et_praestantia_MDZ_MBS.json
currently processing:  Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.json
currently processing:  Claveus1598_Apologia_crysopoeiae_MDZ_MBS.json
failed with file:  None
failed with file:  None
currently processing:  Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.json
currently processing:  Witestein1583_Disceptatio_philosophica_MDZ_MBS.json
failed with file:  nan
failed with file:  nan
failed with file:  nan
failed with file:  nan
failed with file:  None
failed with file:  nan
failed with file:  None
failed with file:  None
failed with file:  nan
failed with file:  nan
failed with file:  None
failed with file:  nan
failed with file:  nan
failed with file:  nan
failed with file:  nan
CPU times: user 3min 19s, sys: 6.74 s, total: 3min 26s
Wall time: 3min 26s

In [140]:
target_path = "/srv/data/tome/tome-corpus/sents_data_jsons_v3-0/"

In [127]:
# Extract tahe lemmatized sentences

In [141]:
fns_jsons = os.listdir(target_path)
fns_jsons[:10]

['Moffett_De_iure_et_praestantia_MDZ_MBS.json',
 'Toxites1567_Spongia_stibii_MDZ_MBS.json',
 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.json',
 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.json',
 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.json',
 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.json',
 'Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.json',
 'Pedemontanus1563_De_Secretis_MDZ_MBS.json',
 'Phaedro1562_Aquila_coelestis_MBZ_MBS.json']

In [142]:
len(fns_jsons)

59

In [143]:
sents_data = json.load(open(target_path + fns_jsons[4], "r"))
sents_data[100:103]

[['Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
  100,
  'Similiter possimus dicere de aliis elementis,& ab istis elementis corpora supercoelestia esse composita peruirtutem diuinam aut intelligentiae regentis ipsam.',
  [['Similiter', 'similiter', 'ADV', [0, 9], [17], [15]],
   ['possimus', 'possum', 'VERB', [10, 18], [17], [15]],
   ['dicere', 'dico', 'VERB', [19, 25], [17], [15]],
   ['de', 'de', 'ADP', [26, 28], [17], [15]],
   ['aliis', 'alius', 'DET', [29, 34], [17], [15]],
   ['elementis', 'elementum', 'NOUN', [35, 44], [17], [15]],
   [',', ',', 'PUNCT', [44, 45], [17], [15]],
   ['&', '&', 'PUNCT', [45, 46], [17], [16]],
   ['ab', 'ab', 'ADP', [47, 49], [17], [16]],
   ['istis', 'iste', 'DET', [50, 55], [17], [16]],
   ['elementis', 'elementum', 'NOUN', [56, 65], [17], [16]],
   ['corpora', 'corpus', 'NOUN', [66, 73], [17], [16]],
   ['supercoelestia', '', 'VERB', [74, 88], [17], [16]],
   ['esse', 'sum', 'AUX', [89, 93], [17], [16]],
   ['composita', 'compositus', 'VERB', [94, 103], [17], [16]],
   ['peruirtutem', 'peruirtus', 'VERB', [104, 115], [17], [16, 17]],
   ['diuinam', 'diuinus', 'ADJ', [116, 123], [17], [17]],
   ['aut', 'aut', 'CCONJ', [124, 127], [17], [17]],
   ['intelligentiae', 'intellegentia', 'NOUN', [128, 142], [17], [17]],
   ['regentis', 'rego', 'VERB', [143, 151], [17], [17]],
   ['ipsam', 'ipse', 'DET', [152, 157], [17], [17]],
   ['.', '.', 'PUNCT', [157, 158], [17], [17]]]],
 ['Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
  101,
  'Ab elementis istis non potest generari grauitas autem leuitas, ut dicaturterra illa grauis uel ponderosa, quia solum inest terre illae crassae & ponderosae, & quasi elementariae.',
  [['Ab', 'ab', 'ADP', [0, 2], [17], [17]],
   ['elementis', 'elementum', 'NOUN', [3, 12], [17], [17, 18]],
   ['istis', 'iste', 'DET', [13, 18], [17], [18]],
   ['non', 'non', 'PART', [19, 22], [17], [18]],
   ['potest', 'possum', 'VERB', [23, 29], [17], [18]],
   ['generari', 'genero', 'VERB', [30, 38], [17], [18]],
   ['grauitas', 'grauitas', 'NOUN', [39, 47], [17], [18]],
   ['autem', 'autem', 'PART', [48, 53], [17], [18]],
   ['leuitas', 'leuitas', 'NOUN', [54, 61], [17], [18]],
   [',', ',', 'PUNCT', [61, 62], [17], [18]],
   ['ut', 'ut', 'SCONJ', [63, 65], [17], [18]],
   ['dicaturterra', 'dicaturterra', 'NOUN', [66, 78], [17], [18, 19]],
   ['illa', 'ille', 'DET', [79, 83], [17], [19]],
   ['grauis', 'grauis', 'ADJ', [84, 90], [17], [19]],
   ['uel', 'uel', 'CCONJ', [91, 94], [17], [19]],
   ['ponderosa', 'ponderosus', 'ADJ', [95, 104], [17], [19]],
   [',', ',', 'PUNCT', [104, 105], [17], [19]],
   ['quia', 'quia', 'SCONJ', [106, 110], [17], [19]],
   ['solum', 'solum', 'ADV', [111, 116], [17], [19]],
   ['inest', 'insum', 'VERB', [117, 122], [17], [19]],
   ['terre', 'terra', 'NOUN', [123, 128], [17], [19]],
   ['illae', 'ille', 'DET', [129, 134], [17], [19]],
   ['crassae', 'crassus', 'ADJ', [135, 142], [17], [19, 20]],
   ['&', '&', 'PUNCT', [143, 144], [17], [20]],
   ['ponderosae', 'ponderosus', 'ADJ', [145, 155], [17], [20]],
   [',', ',', 'PUNCT', [155, 156], [17], [20]],
   ['&', '&', 'PUNCT', [157, 158], [17], [20]],
   ['quasi', 'quasi', 'ADV', [159, 164], [17], [20]],
   ['elementariae', 'elementarius', 'ADJ', [165, 177], [17], [20]],
   ['.', '.', 'PUNCT', [177, 178], [17], [20]]]],
 ['Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.json',
  102,
  'Generantur tamen colores in corporibus supercoelestibus ab ipsis elementis.',
  [['Generantur', 'genero', 'VERB', [0, 10], [17], [20]],
   ['tamen', 'tamen', 'ADV', [11, 16], [17], [20]],
   ['colores', 'color', 'NOUN', [17, 24], [17], [20, 21]],
   ['in', 'in', 'ADP', [25, 27], [17], [21]],
   ['corporibus', 'corpus', 'NOUN', [28, 38], [17], [21]],
   ['supercoelestibus', 'supercoelestis', 'ADJ', [39, 55], [17], [21]],
   ['ab', 'ab', 'ADP', [56, 58], [17], [21]],
   ['ipsis', 'ipse', 'DET', [59, 64], [17], [21]],
   ['elementis', 'elementum', 'NOUN', [65, 74], [17], [21]],
   ['.', '.', 'PUNCT', [74, 75], [17], [21]]]]]

In [145]:
lemmatized_sents_path = "/srv/data/tome/tome-corpus/lemmatized_sents_v3-0/"
try:
    os.mkdir(lemmatized_sents_path)
except:
    pass

In [146]:
for fn in fns_jsons:
    lemmatized_sents = []
    sents_data = json.load(open(target_path + fn, "rb"))
    for (doc_id, sent_id, sent_text, sent_data) in sents_data:
        lemmasent = []
        for wordform, lemma, tag, position, t_pages, t_textblocks in sent_data:
            if tag in ["NOUN", "PROPN", "ADJ", "VERB"]:
                lemmasent.append(lemma)
        lemmatized_sents.append(" ".join(lemmasent) + "\n")
    with open(lemmatized_sents_path + fn.replace(".json", ".txt"), "w", encoding="utf-8") as f:
        f.writelines(lemmatized_sents)