In [ ]:
import importlib
import processing_textblocks_helpers as pth
import os
import spacy
import os
import glob
from spacy.tokens import Doc
from spacy.language import Language
import pickle
from unidecode import unidecode
import sddk
import pandas as pd
import re
import sys
import importlib
import json
from spacy.tokens import Token
from spacy.language import Language
import google_conf
import pandas as pd
import json
import fitz
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import spacy_stanza
import re
import unicodedata
from spacy.tokens import Token, Doc
from spacy.language import Language
from spacy.symbols import ORTH
import spacy
from spacy.tokenizer import Tokenizer
from spacy.util import compile_prefix_regex, compile_suffix_regex, compile_infix_regex

In [ ]:
#importlib.reload(pth)

In [ ]:
source_path = "../data/emlap_sanitized_textblocks/"
len(os.listdir(source_path))

In [ ]:
filenames = os.listdir(source_path)
filename = filenames[10]
print(filename)

In [ ]:
filepath = os.path.join(source_path, filename)
with open(filepath, 'r', encoding='utf-8') as f:
    textblocks = json.load(f)

In [ ]:
textblocks[1][:10]

In [7]:
doc, doc_margins = pth.process_with_source_tracking(textblocks[:], pth.nlp_latin)

In [8]:
work_id = filename[:6]
sent_dicts = pth.doc_to_sent_dicts(doc, work_id)
sent_dicts_margins = pth.doc_to_sent_dicts(doc_margins, work_id)

In [9]:
print(len(sent_dicts))
print(len(sent_dicts_margins))

25721
941

In [10]:
sent_dicts_with_coords = pth.attach_coordinates_to_sent_dicts(sent_dicts, textblocks)
sent_dicts_margins_with_coords = pth.attach_coordinates_to_sent_dicts(sent_dicts_margins, textblocks)

In [11]:
merged_sentences = pth.merge_main_and_margin_sentences(
    sent_dicts_with_coords,
    sent_dicts_margins_with_coords
)
len(merged_sentences)

26662

In [12]:
merged_sentences[:10]

[{'work_id': '100085',
  'sent_id': 0,
  'sent_text': 'Commentariorum',
  'tokens_data': [{'token_text': 'Commentariorum',
    'lemma': 'commentarius',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [1], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 14,
    'coordinates': [74.63999938964844,
     332.4238586425781,
     1787.7001953125,
     337.3438720703125]}]},
 {'work_id': '100085',
  'sent_id': 1,
  'sent_text': 'Alchymiae',
  'tokens_data': [{'token_text': 'Alchymiae',
    'lemma': 'alchymius',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [2], 'tag': '', 'blocktype': 'title'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [612.239990234375,
     450.7439270019531,
     1403.43505859375,
     455.6639404296875]}]},
 {'work_id': '100085',
  'sent_id': 2,
  'sent_text': 'Andreae Libauii Med.',
  'tokens_data': [{'token_text': 'Andreae',
    'lemma': 'Andreas',
    'pos': 'ADJ',
    'ref': {'page': [1], 'textblock': [3], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 7,
    'coordinates': [121.68000030517578,
     584.8799438476562,
     811.9956665039062,
     589.6799926757812]},
   {'token_text': 'Libauii',
    'lemma': 'Libauius',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [3], 'tag': '', 'blocktype': 'text'},
    'char_start': 8,
    'char_end': 15,
    'coordinates': [121.68000030517578,
     584.8799438476562,
     811.9956665039062,
     589.6799926757812]},
   {'token_text': 'Med',
    'lemma': 'ego',
    'pos': 'ADJ',
    'ref': {'page': [1], 'textblock': [3], 'tag': '', 'blocktype': 'text'},
    'char_start': 16,
    'char_end': 19,
    'coordinates': [121.68000030517578,
     584.8799438476562,
     811.9956665039062,
     589.6799926757812]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [3], 'tag': '', 'blocktype': 'text'},
    'char_start': 19,
    'char_end': 20,
    'coordinates': [121.68000030517578,
     584.8799438476562,
     811.9956665039062,
     589.6799926757812]}]},
 {'work_id': '100085',
  'sent_id': 3,
  'sent_text': 'D.',
  'tokens_data': [{'token_text': 'D.',
    'lemma': 'Decimus',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [3], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 2,
    'coordinates': [121.68000030517578,
     584.8799438476562,
     811.9956665039062,
     589.6799926757812]}]},
 {'work_id': '100085',
  'sent_id': 4,
  'sent_text': 'Pars Prima,',
  'tokens_data': [{'token_text': 'Pars',
    'lemma': 'pars',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [4], 'tag': '', 'blocktype': 'title'},
    'char_start': 0,
    'char_end': 4,
    'coordinates': [554.6400146484375,
     681.5999145507812,
     1296.906005859375,
     686.3999633789062]},
   {'token_text': 'Prima',
    'lemma': 'primus',
    'pos': 'ADJ',
    'ref': {'page': [1], 'textblock': [4], 'tag': '', 'blocktype': 'title'},
    'char_start': 5,
    'char_end': 10,
    'coordinates': [554.6400146484375,
     681.5999145507812,
     1296.906005859375,
     686.3999633789062]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [4], 'tag': '', 'blocktype': 'title'},
    'char_start': 10,
    'char_end': 11,
    'coordinates': [554.6400146484375,
     681.5999145507812,
     1296.906005859375,
     686.3999633789062]}]},
 {'work_id': '100085',
  'sent_id': 5,
  'sent_text': 'Sex Libris Declarata.',
  'tokens_data': [{'token_text': 'Sex',
    'lemma': 'sex',
    'pos': 'NUM',
    'ref': {'page': [1], 'textblock': [5], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 3,
    'coordinates': [435.1199951171875,
     767.3040161132812,
     1421.9512939453125,
     772.2239990234375]},
   {'token_text': 'Libris',
    'lemma': 'Liber',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [5], 'tag': '', 'blocktype': 'text'},
    'char_start': 4,
    'char_end': 10,
    'coordinates': [435.1199951171875,
     767.3040161132812,
     1421.9512939453125,
     772.2239990234375]},
   {'token_text': 'Declarata',
    'lemma': 'declaro',
    'pos': 'NUM',
    'ref': {'page': [1], 'textblock': [5], 'tag': '', 'blocktype': 'text'},
    'char_start': 11,
    'char_end': 20,
    'coordinates': [435.1199951171875,
     767.3040161132812,
     1421.9512939453125,
     772.2239990234375]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [5], 'tag': '', 'blocktype': 'text'},
    'char_start': 20,
    'char_end': 21,
    'coordinates': [435.1199951171875,
     767.3040161132812,
     1421.9512939453125,
     772.2239990234375]}]},
 {'work_id': '100085',
  'sent_id': 6,
  'sent_text': 'Continens Explicationem Operationum Chymicarum',
  'tokens_data': [{'token_text': 'Continens',
    'lemma': 'continenso',
    'pos': 'ADP',
    'ref': {'page': [1], 'textblock': [6], 'tag': '', 'blocktype': 'title'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [61.91999816894531,
     878.6399536132812,
     1813.84375,
     883.4400024414062]},
   {'token_text': 'Explicationem',
    'lemma': 'explicatio',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [6], 'tag': '', 'blocktype': 'title'},
    'char_start': 10,
    'char_end': 23,
    'coordinates': [61.91999816894531,
     878.6399536132812,
     1813.84375,
     883.4400024414062]},
   {'token_text': 'Operationum',
    'lemma': 'operatio',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [7], 'tag': '', 'blocktype': 'title'},
    'char_start': 24,
    'char_end': 35,
    'coordinates': [104.4000015258789,
     958.5840454101562,
     1768.1246337890625,
     963.5040283203125]},
   {'token_text': 'Chymicarum',
    'lemma': 'chymicus',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [7], 'tag': '', 'blocktype': 'title'},
    'char_start': 36,
    'char_end': 46,
    'coordinates': [104.4000015258789,
     958.5840454101562,
     1768.1246337890625,
     963.5040283203125]}]},
 {'work_id': '100085',
  'sent_id': 7,
  'sent_text': 'Prioreartis Libro Comprehensarum, Adiectis Fornacum Et Aliorum Uasorum Figuris, partim ex impressis antehac autoribus, partim aliunde acceptis, & ex latibulis officinarum productis.',
  'tokens_data': [{'token_text': 'Prioreartis',
    'lemma': 'prioreartus',
    'pos': 'ADP',
    'ref': {'page': [1], 'textblock': [7, 8], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 11,
    'coordinates': [104.4000015258789,
     958.5840454101562,
     1768.1246337890625,
     963.5040283203125]},
   {'token_text': 'Libro',
    'lemma': 'Liber',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
    'char_start': 12,
    'char_end': 17,
    'coordinates': [183.36000061035156,
     1033.4638671875,
     1669.21630859375,
     1038.3839111328125]},
   {'token_text': 'Comprehensarum',
    'lemma': 'comprehendo',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
    'char_start': 18,
    'char_end': 32,
    'coordinates': [183.36000061035156,
     1033.4638671875,
     1669.21630859375,
     1038.3839111328125]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
    'char_start': 32,
    'char_end': 33,
    'coordinates': [183.36000061035156,
     1033.4638671875,
     1669.21630859375,
     1038.3839111328125]},
   {'token_text': 'Adiectis',
    'lemma': 'Adiecio',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [8, 9], 'tag': '', 'blocktype': 'text'},
    'char_start': 34,
    'char_end': 42,
    'coordinates': [183.36000061035156,
     1033.4638671875,
     1669.21630859375,
     1038.3839111328125]},
   {'token_text': 'Fornacum',
    'lemma': 'fornax',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
    'char_start': 43,
    'char_end': 51,
    'coordinates': [240.9600067138672,
     1093.4400634765625,
     1615.7607421875,
     1098.239990234375]},
   {'token_text': 'Et',
    'lemma': 'et',
    'pos': 'CCONJ',
    'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
    'char_start': 52,
    'char_end': 54,
    'coordinates': [240.9600067138672,
     1093.4400634765625,
     1615.7607421875,
     1098.239990234375]},
   {'token_text': 'Aliorum',
    'lemma': 'alius',
    'pos': 'DET',
    'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
    'char_start': 55,
    'char_end': 62,
    'coordinates': [240.9600067138672,
     1093.4400634765625,
     1615.7607421875,
     1098.239990234375]},
   {'token_text': 'Uasorum',
    'lemma': 'uasum',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
    'char_start': 63,
    'char_end': 70,
    'coordinates': [240.9600067138672,
     1093.4400634765625,
     1615.7607421875,
     1098.239990234375]},
   {'token_text': 'Figuris',
    'lemma': 'figura',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [9, 10], 'tag': '', 'blocktype': 'text'},
    'char_start': 71,
    'char_end': 78,
    'coordinates': [240.9600067138672,
     1093.4400634765625,
     1615.7607421875,
     1098.239990234375]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 78,
    'char_end': 79,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'partim',
    'lemma': 'pars',
    'pos': 'ADV',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 80,
    'char_end': 86,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'ex',
    'lemma': 'ex',
    'pos': 'ADP',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 87,
    'char_end': 89,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'impressis',
    'lemma': 'imprimo',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 90,
    'char_end': 99,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'antehac',
    'lemma': 'antehac',
    'pos': 'ADV',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 100,
    'char_end': 107,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'autoribus',
    'lemma': 'autor',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 108,
    'char_end': 117,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 117,
    'char_end': 118,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'partim',
    'lemma': 'pars',
    'pos': 'ADV',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 119,
    'char_end': 125,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'aliunde',
    'lemma': 'aliunde',
    'pos': 'ADV',
    'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
    'char_start': 126,
    'char_end': 133,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': 'acceptis',
    'lemma': 'accipio',
    'pos': 'VERB',
    'ref': {'page': [1],
     'textblock': [10, 11],
     'tag': '',
     'blocktype': 'text'},
    'char_start': 134,
    'char_end': 142,
    'coordinates': [349.9200134277344,
     1151.783935546875,
     1522.6253662109375,
     1156.7039794921875]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 142,
    'char_end': 143,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': '&',
    'lemma': '&',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 144,
    'char_end': 145,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': 'ex',
    'lemma': 'ex',
    'pos': 'ADP',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 146,
    'char_end': 148,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': 'latibulis',
    'lemma': 'latibulum',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 149,
    'char_end': 158,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': 'officinarum',
    'lemma': 'officina',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 159,
    'char_end': 170,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': 'productis',
    'lemma': 'produco',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 171,
    'char_end': 180,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]},
   {'token_text': '.',
    'lemma': '.',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
    'char_start': 180,
    'char_end': 181,
    'coordinates': [584.4000244140625,
     1199.9998779296875,
     1333.544921875,
     1204.7998046875]}]},
 {'work_id': '100085',
  'sent_id': 8,
  'sent_text': 'Praemissa Est Defensio Alchemiae Et refutatio obiectionum ex Censura scholae Parisiensis, quae licet uideri nolit hanc Alchemiam, sed Quercetani damnasse, nimis tamen frigide de arte sentit, eaque proponit, quae in ludibrium & ignominiam artis simpliciter possunt conuerti, nec sonant aliter.',
  'tokens_data': [{'token_text': 'Praemissa',
    'lemma': 'praemitto',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [12], 'tag': '', 'blocktype': 'text'},
    'char_start': 0,
    'char_end': 9,
    'coordinates': [36.2400016784668,
     1315.223876953125,
     1725.3497314453125,
     1320.1439208984375]},
   {'token_text': 'Est',
    'lemma': 'sum',
    'pos': 'AUX',
    'ref': {'page': [1], 'textblock': [12], 'tag': '', 'blocktype': 'text'},
    'char_start': 10,
    'char_end': 13,
    'coordinates': [36.2400016784668,
     1315.223876953125,
     1725.3497314453125,
     1320.1439208984375]},
   {'token_text': 'Defensio',
    'lemma': 'defensio',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [12], 'tag': '', 'blocktype': 'text'},
    'char_start': 14,
    'char_end': 22,
    'coordinates': [36.2400016784668,
     1315.223876953125,
     1725.3497314453125,
     1320.1439208984375]},
   {'token_text': 'Alchemiae',
    'lemma': 'Alchemia',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [12], 'tag': '', 'blocktype': 'text'},
    'char_start': 23,
    'char_end': 32,
    'coordinates': [36.2400016784668,
     1315.223876953125,
     1725.3497314453125,
     1320.1439208984375]},
   {'token_text': 'Et',
    'lemma': 'et',
    'pos': 'CCONJ',
    'ref': {'page': [1], 'textblock': [12], 'tag': '', 'blocktype': 'text'},
    'char_start': 33,
    'char_end': 35,
    'coordinates': [36.2400016784668,
     1315.223876953125,
     1725.3497314453125,
     1320.1439208984375]},
   {'token_text': 'refutatio',
    'lemma': 'refutatio',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 36,
    'char_end': 45,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'obiectionum',
    'lemma': 'obiectio',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 46,
    'char_end': 57,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'ex',
    'lemma': 'ex',
    'pos': 'ADP',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 58,
    'char_end': 60,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'Censura',
    'lemma': 'censura',
    'pos': 'PROPN',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 61,
    'char_end': 68,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'scholae',
    'lemma': 'schola',
    'pos': 'NOUN',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 69,
    'char_end': 76,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'Parisiensis',
    'lemma': 'Parisiensis',
    'pos': 'ADJ',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 77,
    'char_end': 88,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': ',',
    'lemma': ',',
    'pos': 'PUNCT',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 88,
    'char_end': 89,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'quae',
    'lemma': 'qui',
    'pos': 'PRON',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 90,
    'char_end': 94,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'licet',
    'lemma': 'licet',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 95,
    'char_end': 100,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'uideri',
    'lemma': 'uideo',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [13], 'tag': '', 'blocktype': 'text'},
    'char_start': 101,
    'char_end': 107,
    'coordinates': [59.7599983215332,
     1393.4400634765625,
     1808.927978515625,
     1398.239990234375]},
   {'token_text': 'nolit',
    'lemma': 'nolo',
    'pos': 'VERB',
    'ref': {'page': [1], 'textblock': [14], 'tag': '', 'blocktype': 'text'},
    'char_start': 108,
    'char_end': 113,
    'coordinates': [166.32000732421875,
     1469.9998779296875,
     1709.4947509765625,
     1474.7998046875]},
   {'token_text': 'hanc',
    'lemma': 'hic',
    'pos': 'DET',
    'ref': {'page': [1], 'textblock': [14], 'tag': '', 'blocktype': 'text'},
    'char_start': 114,
    'char_end': 118,
    'coordinates': [166.32000732421875,
     1469.9998779296875,
     1709.4947509765625,
     1474.7998046875]},

In [13]:
merged_sentences[7]

{'work_id': '100085',
 'sent_id': 7,
 'sent_text': 'Prioreartis Libro Comprehensarum, Adiectis Fornacum Et Aliorum Uasorum Figuris, partim ex impressis antehac autoribus, partim aliunde acceptis, & ex latibulis officinarum productis.',
 'tokens_data': [{'token_text': 'Prioreartis',
   'lemma': 'prioreartus',
   'pos': 'ADP',
   'ref': {'page': [1], 'textblock': [7, 8], 'tag': '', 'blocktype': 'text'},
   'char_start': 0,
   'char_end': 11,
   'coordinates': [104.4000015258789,
    958.5840454101562,
    1768.1246337890625,
    963.5040283203125]},
  {'token_text': 'Libro',
   'lemma': 'Liber',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
   'char_start': 12,
   'char_end': 17,
   'coordinates': [183.36000061035156,
    1033.4638671875,
    1669.21630859375,
    1038.3839111328125]},
  {'token_text': 'Comprehensarum',
   'lemma': 'comprehendo',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
   'char_start': 18,
   'char_end': 32,
   'coordinates': [183.36000061035156,
    1033.4638671875,
    1669.21630859375,
    1038.3839111328125]},
  {'token_text': ',',
   'lemma': ',',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [8], 'tag': '', 'blocktype': 'text'},
   'char_start': 32,
   'char_end': 33,
   'coordinates': [183.36000061035156,
    1033.4638671875,
    1669.21630859375,
    1038.3839111328125]},
  {'token_text': 'Adiectis',
   'lemma': 'Adiecio',
   'pos': 'VERB',
   'ref': {'page': [1], 'textblock': [8, 9], 'tag': '', 'blocktype': 'text'},
   'char_start': 34,
   'char_end': 42,
   'coordinates': [183.36000061035156,
    1033.4638671875,
    1669.21630859375,
    1038.3839111328125]},
  {'token_text': 'Fornacum',
   'lemma': 'fornax',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
   'char_start': 43,
   'char_end': 51,
   'coordinates': [240.9600067138672,
    1093.4400634765625,
    1615.7607421875,
    1098.239990234375]},
  {'token_text': 'Et',
   'lemma': 'et',
   'pos': 'CCONJ',
   'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
   'char_start': 52,
   'char_end': 54,
   'coordinates': [240.9600067138672,
    1093.4400634765625,
    1615.7607421875,
    1098.239990234375]},
  {'token_text': 'Aliorum',
   'lemma': 'alius',
   'pos': 'DET',
   'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
   'char_start': 55,
   'char_end': 62,
   'coordinates': [240.9600067138672,
    1093.4400634765625,
    1615.7607421875,
    1098.239990234375]},
  {'token_text': 'Uasorum',
   'lemma': 'uasum',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [9], 'tag': '', 'blocktype': 'text'},
   'char_start': 63,
   'char_end': 70,
   'coordinates': [240.9600067138672,
    1093.4400634765625,
    1615.7607421875,
    1098.239990234375]},
  {'token_text': 'Figuris',
   'lemma': 'figura',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [9, 10], 'tag': '', 'blocktype': 'text'},
   'char_start': 71,
   'char_end': 78,
   'coordinates': [240.9600067138672,
    1093.4400634765625,
    1615.7607421875,
    1098.239990234375]},
  {'token_text': ',',
   'lemma': ',',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 78,
   'char_end': 79,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'partim',
   'lemma': 'pars',
   'pos': 'ADV',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 80,
   'char_end': 86,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'ex',
   'lemma': 'ex',
   'pos': 'ADP',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 87,
   'char_end': 89,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'impressis',
   'lemma': 'imprimo',
   'pos': 'VERB',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 90,
   'char_end': 99,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'antehac',
   'lemma': 'antehac',
   'pos': 'ADV',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 100,
   'char_end': 107,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'autoribus',
   'lemma': 'autor',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 108,
   'char_end': 117,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': ',',
   'lemma': ',',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 117,
   'char_end': 118,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'partim',
   'lemma': 'pars',
   'pos': 'ADV',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 119,
   'char_end': 125,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'aliunde',
   'lemma': 'aliunde',
   'pos': 'ADV',
   'ref': {'page': [1], 'textblock': [10], 'tag': '', 'blocktype': 'text'},
   'char_start': 126,
   'char_end': 133,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': 'acceptis',
   'lemma': 'accipio',
   'pos': 'VERB',
   'ref': {'page': [1], 'textblock': [10, 11], 'tag': '', 'blocktype': 'text'},
   'char_start': 134,
   'char_end': 142,
   'coordinates': [349.9200134277344,
    1151.783935546875,
    1522.6253662109375,
    1156.7039794921875]},
  {'token_text': ',',
   'lemma': ',',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 142,
   'char_end': 143,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': '&',
   'lemma': '&',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 144,
   'char_end': 145,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': 'ex',
   'lemma': 'ex',
   'pos': 'ADP',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 146,
   'char_end': 148,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': 'latibulis',
   'lemma': 'latibulum',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 149,
   'char_end': 158,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': 'officinarum',
   'lemma': 'officina',
   'pos': 'NOUN',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 159,
   'char_end': 170,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': 'productis',
   'lemma': 'produco',
   'pos': 'VERB',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 171,
   'char_end': 180,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]},
  {'token_text': '.',
   'lemma': '.',
   'pos': 'PUNCT',
   'ref': {'page': [1], 'textblock': [11], 'tag': '', 'blocktype': 'text'},
   'char_start': 180,
   'char_end': 181,
   'coordinates': [584.4000244140625,
    1199.9998779296875,
    1333.544921875,
    1204.7998046875]}]}

In [14]:
[s["sent_text"] for s in merged_sentences][:10]

['Commentariorum',
 'Alchymiae',
 'Andreae Libauii Med.',
 'D.',
 'Pars Prima,',
 'Sex Libris Declarata.',
 'Continens Explicationem Operationum Chymicarum',
 'Prioreartis Libro Comprehensarum, Adiectis Fornacum Et Aliorum Uasorum Figuris, partim ex impressis antehac autoribus, partim aliunde acceptis, & ex latibulis officinarum productis.',
 'Praemissa Est Defensio Alchemiae Et refutatio obiectionum ex Censura scholae Parisiensis, quae licet uideri nolit hanc Alchemiam, sed Quercetani damnasse, nimis tamen frigide de arte sentit, eaque proponit, quae in ludibrium & ignominiam artis simpliciter possunt conuerti, nec sonant aliter.',
 'Pag. 15.']

In [15]:
merged_tokens = pd.DataFrame(
    (lambda d, n=n: (d.update({"sent_n": n}) or d))(t)
    for n, token_list in enumerate([sent["tokens_data"] for sent in merged_sentences])
    for t in token_list
)
for attr in ["page", "textblock", "tag", "blocktype"]:
    merged_tokens[attr] = merged_tokens.apply(lambda row: row["ref"][attr], axis=1)
merged_tokens.drop(["ref", "coordinates"], axis=1, inplace=True)
merged_tokens.head(5)

,token_text,lemma,pos,char_start,char_end,sent_n,page,textblock,tag,blocktype
0,Commentariorum,commentarius,NOUN,0,14,0,[1],[1],,text
1,Alchymiae,alchymius,PROPN,0,9,1,[1],[2],,title
2,Andreae,Andreas,ADJ,0,7,2,[1],[3],,text
3,Libauii,Libauius,PROPN,8,15,2,[1],[3],,text
4,Med,ego,ADJ,16,19,2,[1],[3],,text

In [16]:
len(merged_tokens)

394698

In [17]:
merged_tokens["tag"].value_counts()

tag
      391234
GR      2825
G        340
S        297
I          2
Name: count, dtype: int64

In [18]:
merged_tokens[merged_tokens["tag"]=="S"]

,token_text,lemma,pos,char_start,char_end,sent_n,page,textblock,tag,blocktype
43288,◉,y,SYM,5,6,3113,[48],[0],S,margin
73799,◉,z,SYM,18,19,5672,[74],[31],S,text
73804,◉,z,SYM,9,10,5673,[74],[31],S,text
81471,◉,◉,SYM,35,36,6472,[82],[14],S,margin
81475,◉,◉,SYM,45,46,6472,[82],[15],S,margin
...,...,...,...,...,...,...,...,...,...,...
391941,◉,y,SYM,9,10,26456,[410],[48],S,text
391954,◉,y,SYM,0,1,26461,[410],[48],S,text
391972,◉,y,SYM,12,13,26467,[410],[48],S,text
391983,◉,y,SYM,0,1,26472,[410],[48],S,text
391989,◉,y,SYM,0,1,26475,[410],[49],S,text

In [19]:
def process_textblocks(textblocks):
    filepath = os.path.join(source_path, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        textblocks = json.load(f)
    doc, doc_margins = pth.process_with_source_tracking(textblocks[:], pth.nlp_latin)
    work_id = filename[:6]
    sent_dicts = pth.doc_to_sent_dicts(doc, work_id)
    sent_dicts_margins = pth.doc_to_sent_dicts(doc_margins, work_id)
    sent_dicts_with_coords = pth.attach_coordinates_to_sent_dicts(sent_dicts, textblocks)
    sent_dicts_margins_with_coords = pth.attach_coordinates_to_sent_dicts(sent_dicts_margins, textblocks)
    merged_sentences = pth.merge_main_and_margin_sentences(
        sent_dicts_with_coords,
        sent_dicts_margins_with_coords
    )
    merged_sentences_uncoord = []
    for sent_data in merged_sentences:
        for token_data in sent_data["tokens_data"]:
            del token_data["coordinates"]
    return merged_sentences

In [ ]:
sents_data = process_textblocks(textblocks)

In [ ]:
target_path = "../data/sents_data_jsons_dicts/"
os.makedirs(target_path, exist_ok=True)

In [27]:
for filename in os.listdir(source_path):
    id = filename[:6]
    outfile = id + ".json"
    if outfile not in os.listdir(target_path):
        filepath = os.path.join(source_path, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            textblocks = json.load(f)
        sent_dicts = process_textblocks(textblocks)
        outpath = os.path.join(target_path, outfile)
        with open(outpath, 'w', encoding='utf-8') as f:
            json.dump(sent_dicts, f, ensure_ascii=False, indent=2)